// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package transferdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCorridorMetrics = `-- name: GetCorridorMetrics :many
SELECT
    source_currency,
    dest_currency,
    COUNT(*) AS transfer_count,
    COALESCE(SUM(source_amount) FILTER (WHERE status NOT IN ('FAILED','REFUNDED')), 0)::NUMERIC(28,8) AS volume_usd,
    COALESCE(SUM((fees->>'total_fee_usd')::NUMERIC(28,8)) FILTER (WHERE status NOT IN ('FAILED','REFUNDED')), 0)::NUMERIC(28,8) AS fees_usd,
    COUNT(*) FILTER (WHERE status = 'COMPLETED') AS completed,
    COUNT(*) FILTER (WHERE status = 'FAILED') AS failed,
    CASE
        WHEN COUNT(*) FILTER (WHERE status IN ('COMPLETED','FAILED')) = 0 THEN 0
        ELSE ROUND(
            100.0 * COUNT(*) FILTER (WHERE status = 'COMPLETED')
            / COUNT(*) FILTER (WHERE status IN ('COMPLETED','FAILED')),
            2
        )
    END::NUMERIC(5,2) AS success_rate,
    COALESCE(
        AVG(EXTRACT(EPOCH FROM (completed_at - created_at)) * 1000)
        FILTER (WHERE status = 'COMPLETED' AND completed_at IS NOT NULL),
        0
    )::INTEGER AS avg_latency_ms
FROM transfers
WHERE tenant_id = $1
  AND created_at >= $2::timestamptz
  AND created_at < $3::timestamptz
GROUP BY source_currency, dest_currency
ORDER BY volume_usd DESC
`

type GetCorridorMetricsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	FromTime time.Time `json:"from_time"`
	ToTime   time.Time `json:"to_time"`
}

type GetCorridorMetricsRow struct {
	SourceCurrency string         `json:"source_currency"`
	DestCurrency   string         `json:"dest_currency"`
	TransferCount  int64          `json:"transfer_count"`
	VolumeUsd      pgtype.Numeric `json:"volume_usd"`
	FeesUsd        pgtype.Numeric `json:"fees_usd"`
	Completed      int64          `json:"completed"`
	Failed         int64          `json:"failed"`
	SuccessRate    pgtype.Numeric `json:"success_rate"`
	AvgLatencyMs   int32          `json:"avg_latency_ms"`
}

// Per-corridor volume, count, success rate, and average latency.
func (q *Queries) GetCorridorMetrics(ctx context.Context, arg GetCorridorMetricsParams) ([]GetCorridorMetricsRow, error) {
	rows, err := q.db.Query(ctx, getCorridorMetrics, arg.TenantID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCorridorMetricsRow{}
	for rows.Next() {
		var i GetCorridorMetricsRow
		if err := rows.Scan(
			&i.SourceCurrency,
			&i.DestCurrency,
			&i.TransferCount,
			&i.VolumeUsd,
			&i.FeesUsd,
			&i.Completed,
			&i.Failed,
			&i.SuccessRate,
			&i.AvgLatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentActivity = `-- name: GetRecentActivity :many
SELECT
    t.id AS transfer_id,
    t.external_ref,
    t.status,
    t.source_currency,
    t.source_amount,
    t.dest_currency,
    t.dest_amount,
    t.updated_at,
    t.failure_reason
FROM transfers t
WHERE t.tenant_id = $1
ORDER BY t.updated_at DESC
LIMIT $2
`

type GetRecentActivityParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PageSize int32     `json:"page_size"`
}

type GetRecentActivityRow struct {
	TransferID     uuid.UUID          `json:"transfer_id"`
	ExternalRef    pgtype.Text        `json:"external_ref"`
	Status         TransferStatusEnum `json:"status"`
	SourceCurrency string             `json:"source_currency"`
	SourceAmount   pgtype.Numeric     `json:"source_amount"`
	DestCurrency   string             `json:"dest_currency"`
	DestAmount     pgtype.Numeric     `json:"dest_amount"`
	UpdatedAt      time.Time          `json:"updated_at"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
}

// Recent transfer activity feed (latest state changes).
func (q *Queries) GetRecentActivity(ctx context.Context, arg GetRecentActivityParams) ([]GetRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, getRecentActivity, arg.TenantID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentActivityRow{}
	for rows.Next() {
		var i GetRecentActivityRow
		if err := rows.Scan(
			&i.TransferID,
			&i.ExternalRef,
			&i.Status,
			&i.SourceCurrency,
			&i.SourceAmount,
			&i.DestCurrency,
			&i.DestAmount,
			&i.UpdatedAt,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransferLatencyPercentiles = `-- name: GetTransferLatencyPercentiles :one
SELECT
    COUNT(*) FILTER (WHERE status = 'COMPLETED')::bigint AS sample_count,
    COALESCE(PERCENTILE_CONT(0.50) WITHIN GROUP (
        ORDER BY EXTRACT(EPOCH FROM (completed_at - created_at)) * 1000
    ) FILTER (WHERE status = 'COMPLETED' AND completed_at IS NOT NULL), 0)::INTEGER AS p50_ms,
    COALESCE(PERCENTILE_CONT(0.90) WITHIN GROUP (
        ORDER BY EXTRACT(EPOCH FROM (completed_at - created_at)) * 1000
    ) FILTER (WHERE status = 'COMPLETED' AND completed_at IS NOT NULL), 0)::INTEGER AS p90_ms,
    COALESCE(PERCENTILE_CONT(0.95) WITHIN GROUP (
        ORDER BY EXTRACT(EPOCH FROM (completed_at - created_at)) * 1000
    ) FILTER (WHERE status = 'COMPLETED' AND completed_at IS NOT NULL), 0)::INTEGER AS p95_ms,
    COALESCE(PERCENTILE_CONT(0.99) WITHIN GROUP (
        ORDER BY EXTRACT(EPOCH FROM (completed_at - created_at)) * 1000
    ) FILTER (WHERE status = 'COMPLETED' AND completed_at IS NOT NULL), 0)::INTEGER AS p99_ms
FROM transfers
WHERE tenant_id = $1
  AND created_at >= $2::timestamptz
  AND created_at < $3::timestamptz
`

type GetTransferLatencyPercentilesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	FromTime time.Time `json:"from_time"`
	ToTime   time.Time `json:"to_time"`
}

type GetTransferLatencyPercentilesRow struct {
	SampleCount int64 `json:"sample_count"`
	P50Ms       int32 `json:"p50_ms"`
	P90Ms       int32 `json:"p90_ms"`
	P95Ms       int32 `json:"p95_ms"`
	P99Ms       int32 `json:"p99_ms"`
}

// Transfer completion latency percentiles (p50, p90, p95, p99) for completed transfers.
func (q *Queries) GetTransferLatencyPercentiles(ctx context.Context, arg GetTransferLatencyPercentilesParams) (GetTransferLatencyPercentilesRow, error) {
	row := q.db.QueryRow(ctx, getTransferLatencyPercentiles, arg.TenantID, arg.FromTime, arg.ToTime)
	var i GetTransferLatencyPercentilesRow
	err := row.Scan(
		&i.SampleCount,
		&i.P50Ms,
		&i.P90Ms,
		&i.P95Ms,
		&i.P99Ms,
	)
	return i, err
}

const getTransferStatusDistribution = `-- name: GetTransferStatusDistribution :many

SELECT
    status,
    COUNT(*) AS count
FROM transfers
WHERE tenant_id = $1
  AND created_at >= $2::timestamptz
  AND created_at < $3::timestamptz
GROUP BY status
ORDER BY count DESC
`

type GetTransferStatusDistributionParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	FromTime time.Time `json:"from_time"`
	ToTime   time.Time `json:"to_time"`
}

type GetTransferStatusDistributionRow struct {
	Status TransferStatusEnum `json:"status"`
	Count  int64              `json:"count"`
}

// ============================================================================
// Analytics queries — enhanced metrics for the tenant portal analytics page.
// All queries are tenant-scoped per the tenant isolation invariant.
// ============================================================================
// Count of transfers by current status for a given period.
func (q *Queries) GetTransferStatusDistribution(ctx context.Context, arg GetTransferStatusDistributionParams) ([]GetTransferStatusDistributionRow, error) {
	rows, err := q.db.Query(ctx, getTransferStatusDistribution, arg.TenantID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransferStatusDistributionRow{}
	for rows.Next() {
		var i GetTransferStatusDistributionRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVolumeComparison = `-- name: GetVolumeComparison :one
SELECT
    -- Current period
    COUNT(*) FILTER (WHERE created_at >= $1::timestamptz) AS current_count,
    COALESCE(SUM(source_amount) FILTER (WHERE created_at >= $1::timestamptz AND status NOT IN ('FAILED','REFUNDED')), 0)::NUMERIC(28,8) AS current_volume_usd,
    COALESCE(SUM((fees->>'total_fee_usd')::NUMERIC(28,8)) FILTER (WHERE created_at >= $1::timestamptz AND status NOT IN ('FAILED','REFUNDED')), 0)::NUMERIC(28,8) AS current_fees_usd,
    -- Previous period
    COUNT(*) FILTER (WHERE created_at < $1::timestamptz) AS previous_count,
    COALESCE(SUM(source_amount) FILTER (WHERE created_at < $1::timestamptz AND status NOT IN ('FAILED','REFUNDED')), 0)::NUMERIC(28,8) AS previous_volume_usd,
    COALESCE(SUM((fees->>'total_fee_usd')::NUMERIC(28,8)) FILTER (WHERE created_at < $1::timestamptz AND status NOT IN ('FAILED','REFUNDED')), 0)::NUMERIC(28,8) AS previous_fees_usd
FROM transfers
WHERE tenant_id = $2
  AND created_at >= $3::timestamptz
  AND created_at < $4::timestamptz
`

type GetVolumeComparisonParams struct {
	CurrentStart  time.Time `json:"current_start"`
	TenantID      uuid.UUID `json:"tenant_id"`
	PreviousStart time.Time `json:"previous_start"`
	CurrentEnd    time.Time `json:"current_end"`
}

type GetVolumeComparisonRow struct {
	CurrentCount      int64          `json:"current_count"`
	CurrentVolumeUsd  pgtype.Numeric `json:"current_volume_usd"`
	CurrentFeesUsd    pgtype.Numeric `json:"current_fees_usd"`
	PreviousCount     int64          `json:"previous_count"`
	PreviousVolumeUsd pgtype.Numeric `json:"previous_volume_usd"`
	PreviousFeesUsd   pgtype.Numeric `json:"previous_fees_usd"`
}

// Compare current period volume/count vs. previous period (for week-over-week or month-over-month).
func (q *Queries) GetVolumeComparison(ctx context.Context, arg GetVolumeComparisonParams) (GetVolumeComparisonRow, error) {
	row := q.db.QueryRow(ctx, getVolumeComparison,
		arg.CurrentStart,
		arg.TenantID,
		arg.PreviousStart,
		arg.CurrentEnd,
	)
	var i GetVolumeComparisonRow
	err := row.Scan(
		&i.CurrentCount,
		&i.CurrentVolumeUsd,
		&i.CurrentFeesUsd,
		&i.PreviousCount,
		&i.PreviousVolumeUsd,
		&i.PreviousFeesUsd,
	)
	return i, err
}
