// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package transferdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_log (tenant_id, actor_type, actor_id, action, entity_type, entity_id, old_value, new_value, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAuditEntryParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	ActorType  string      `json:"actor_type"`
	ActorID    string      `json:"actor_id"`
	Action     string      `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	OldValue   []byte      `json:"old_value"`
	NewValue   []byte      `json:"new_value"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.Exec(ctx, insertAuditEntry,
		arg.TenantID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.OldValue,
		arg.NewValue,
		arg.Metadata,
	)
	return err
}

const listAuditEntriesByEntity = `-- name: ListAuditEntriesByEntity :many
SELECT id, tenant_id, actor_type, actor_id, action, entity_type, entity_id, old_value, new_value, metadata, created_at FROM audit_log
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListAuditEntriesByEntityParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) ListAuditEntriesByEntity(ctx context.Context, arg ListAuditEntriesByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesByEntity, arg.EntityType, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OldValue,
			&i.NewValue,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEntriesByTenant = `-- name: ListAuditEntriesByTenant :many
SELECT id, tenant_id, actor_type, actor_id, action, entity_type, entity_id, old_value, new_value, metadata, created_at FROM audit_log
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditEntriesByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListAuditEntriesByTenant(ctx context.Context, arg ListAuditEntriesByTenantParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntriesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OldValue,
			&i.NewValue,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
