// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bank_deposit_transactions.sql

package transferdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBankDepositTransaction = `-- name: CreateBankDepositTransaction :one
INSERT INTO bank_deposit_transactions (
    session_id, tenant_id, bank_reference, payer_name,
    payer_account_number, amount, currency, received_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, created_at
`

type CreateBankDepositTransactionParams struct {
	SessionID          uuid.UUID      `json:"session_id"`
	TenantID           uuid.UUID      `json:"tenant_id"`
	BankReference      string         `json:"bank_reference"`
	PayerName          string         `json:"payer_name"`
	PayerAccountNumber string         `json:"payer_account_number"`
	Amount             pgtype.Numeric `json:"amount"`
	Currency           string         `json:"currency"`
	ReceivedAt         time.Time      `json:"received_at"`
}

type CreateBankDepositTransactionRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateBankDepositTransaction(ctx context.Context, arg CreateBankDepositTransactionParams) (CreateBankDepositTransactionRow, error) {
	row := q.db.QueryRow(ctx, createBankDepositTransaction,
		arg.SessionID,
		arg.TenantID,
		arg.BankReference,
		arg.PayerName,
		arg.PayerAccountNumber,
		arg.Amount,
		arg.Currency,
		arg.ReceivedAt,
	)
	var i CreateBankDepositTransactionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getBankDepositTransactionByRef = `-- name: GetBankDepositTransactionByRef :one
SELECT id, session_id, tenant_id, bank_reference, payer_name, payer_account_number, amount, currency, received_at, created_at FROM bank_deposit_transactions
WHERE bank_reference = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetBankDepositTransactionByRef(ctx context.Context, bankReference string) (BankDepositTransaction, error) {
	row := q.db.QueryRow(ctx, getBankDepositTransactionByRef, bankReference)
	var i BankDepositTransaction
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TenantID,
		&i.BankReference,
		&i.PayerName,
		&i.PayerAccountNumber,
		&i.Amount,
		&i.Currency,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listBankDepositTransactionsBySession = `-- name: ListBankDepositTransactionsBySession :many
SELECT id, session_id, tenant_id, bank_reference, payer_name, payer_account_number, amount, currency, received_at, created_at FROM bank_deposit_transactions
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListBankDepositTransactionsBySession(ctx context.Context, sessionID uuid.UUID) ([]BankDepositTransaction, error) {
	rows, err := q.db.Query(ctx, listBankDepositTransactionsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BankDepositTransaction{}
	for rows.Next() {
		var i BankDepositTransaction
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TenantID,
			&i.BankReference,
			&i.PayerName,
			&i.PayerAccountNumber,
			&i.Amount,
			&i.Currency,
			&i.ReceivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
