// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: banking_partners.sql

package transferdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBankingPartner = `-- name: CreateBankingPartner :one
INSERT INTO banking_partners (name, webhook_secret, supported_currencies, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, name, webhook_secret, supported_currencies, is_active, metadata, created_at, updated_at
`

type CreateBankingPartnerParams struct {
	Name                string      `json:"name"`
	WebhookSecret       pgtype.Text `json:"webhook_secret"`
	SupportedCurrencies []string    `json:"supported_currencies"`
	Metadata            []byte      `json:"metadata"`
}

func (q *Queries) CreateBankingPartner(ctx context.Context, arg CreateBankingPartnerParams) (BankingPartner, error) {
	row := q.db.QueryRow(ctx, createBankingPartner,
		arg.Name,
		arg.WebhookSecret,
		arg.SupportedCurrencies,
		arg.Metadata,
	)
	var i BankingPartner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WebhookSecret,
		&i.SupportedCurrencies,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBankingPartner = `-- name: GetBankingPartner :one
SELECT id, name, webhook_secret, supported_currencies, is_active, metadata, created_at, updated_at FROM banking_partners
WHERE id = $1
`

func (q *Queries) GetBankingPartner(ctx context.Context, id uuid.UUID) (BankingPartner, error) {
	row := q.db.QueryRow(ctx, getBankingPartner, id)
	var i BankingPartner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WebhookSecret,
		&i.SupportedCurrencies,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBankingPartners = `-- name: ListBankingPartners :many
SELECT id, name, webhook_secret, supported_currencies, is_active, metadata, created_at, updated_at FROM banking_partners
WHERE is_active = true
ORDER BY name ASC
`

func (q *Queries) ListBankingPartners(ctx context.Context) ([]BankingPartner, error) {
	rows, err := q.db.Query(ctx, listBankingPartners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BankingPartner{}
	for rows.Next() {
		var i BankingPartner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WebhookSecret,
			&i.SupportedCurrencies,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
