// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package transferdb

import (
	"context"
)

// iteratorForInsertOutboxEntries implements pgx.CopyFromSource.
type iteratorForInsertOutboxEntries struct {
	rows                 []InsertOutboxEntriesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertOutboxEntries) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertOutboxEntries) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].AggregateType,
		r.rows[0].AggregateID,
		r.rows[0].TenantID,
		r.rows[0].EventType,
		r.rows[0].Payload,
		r.rows[0].IsIntent,
		r.rows[0].MaxRetries,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForInsertOutboxEntries) Err() error {
	return nil
}

func (q *Queries) InsertOutboxEntries(ctx context.Context, arg []InsertOutboxEntriesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"outbox"}, []string{"id", "aggregate_type", "aggregate_id", "tenant_id", "event_type", "payload", "is_intent", "max_retries", "created_at"}, &iteratorForInsertOutboxEntries{rows: arg})
}
