// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: crypto_addresses.sql

package transferdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAvailablePoolAddresses = `-- name: CountAvailablePoolAddresses :one
SELECT COUNT(*) FROM crypto_address_pool
WHERE tenant_id = $1 AND chain = $2 AND dispensed = false
`

type CountAvailablePoolAddressesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Chain    string    `json:"chain"`
}

func (q *Queries) CountAvailablePoolAddresses(ctx context.Context, arg CountAvailablePoolAddressesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAvailablePoolAddresses, arg.TenantID, arg.Chain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dispensePoolAddress = `-- name: DispensePoolAddress :one
UPDATE crypto_address_pool AS cap
SET dispensed = true, dispensed_at = now(), session_id = $1
WHERE cap.id = (
    SELECT cap2.id FROM crypto_address_pool cap2
    WHERE cap2.tenant_id = $2 AND cap2.chain = $3 AND cap2.dispensed = false
    ORDER BY cap2.derivation_index ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, tenant_id, chain, address, derivation_index, dispensed, dispensed_at, session_id, created_at
`

type DispensePoolAddressParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
	Chain     string      `json:"chain"`
}

// Dispenses a pre-generated address from the pool using SKIP LOCKED to avoid contention.
// Returns the dispensed address row.
func (q *Queries) DispensePoolAddress(ctx context.Context, arg DispensePoolAddressParams) (CryptoAddressPool, error) {
	row := q.db.QueryRow(ctx, dispensePoolAddress, arg.SessionID, arg.TenantID, arg.Chain)
	var i CryptoAddressPool
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Chain,
		&i.Address,
		&i.DerivationIndex,
		&i.Dispensed,
		&i.DispensedAt,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const getAddressIndex = `-- name: GetAddressIndex :one
SELECT id, chain, address, tenant_id, session_id, created_at FROM crypto_deposit_address_index
WHERE chain = $1 AND address = $2
`

type GetAddressIndexParams struct {
	Chain   string `json:"chain"`
	Address string `json:"address"`
}

func (q *Queries) GetAddressIndex(ctx context.Context, arg GetAddressIndexParams) (CryptoDepositAddressIndex, error) {
	row := q.db.QueryRow(ctx, getAddressIndex, arg.Chain, arg.Address)
	var i CryptoDepositAddressIndex
	err := row.Scan(
		&i.ID,
		&i.Chain,
		&i.Address,
		&i.TenantID,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const getDerivationCounter = `-- name: GetDerivationCounter :one
SELECT next_index FROM crypto_derivation_counters
WHERE tenant_id = $1 AND chain = $2
`

type GetDerivationCounterParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Chain    string    `json:"chain"`
}

func (q *Queries) GetDerivationCounter(ctx context.Context, arg GetDerivationCounterParams) (int64, error) {
	row := q.db.QueryRow(ctx, getDerivationCounter, arg.TenantID, arg.Chain)
	var next_index int64
	err := row.Scan(&next_index)
	return next_index, err
}

const incrementDerivationCounter = `-- name: IncrementDerivationCounter :one
INSERT INTO crypto_derivation_counters (tenant_id, chain, next_index)
VALUES ($1, $2, 1)
ON CONFLICT (tenant_id, chain)
DO UPDATE SET next_index = crypto_derivation_counters.next_index + 1
RETURNING next_index - 1 AS current_index
`

type IncrementDerivationCounterParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Chain    string    `json:"chain"`
}

// Atomically increments the derivation counter and returns the new index.
func (q *Queries) IncrementDerivationCounter(ctx context.Context, arg IncrementDerivationCounterParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementDerivationCounter, arg.TenantID, arg.Chain)
	var current_index int32
	err := row.Scan(&current_index)
	return current_index, err
}

const insertAddressIndex = `-- name: InsertAddressIndex :one
INSERT INTO crypto_deposit_address_index (
    chain, address, tenant_id, session_id
) VALUES (
    $1, $2, $3, $4
) RETURNING id, chain, address, tenant_id, session_id, created_at
`

type InsertAddressIndexParams struct {
	Chain     string    `json:"chain"`
	Address   string    `json:"address"`
	TenantID  uuid.UUID `json:"tenant_id"`
	SessionID uuid.UUID `json:"session_id"`
}

func (q *Queries) InsertAddressIndex(ctx context.Context, arg InsertAddressIndexParams) (CryptoDepositAddressIndex, error) {
	row := q.db.QueryRow(ctx, insertAddressIndex,
		arg.Chain,
		arg.Address,
		arg.TenantID,
		arg.SessionID,
	)
	var i CryptoDepositAddressIndex
	err := row.Scan(
		&i.ID,
		&i.Chain,
		&i.Address,
		&i.TenantID,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const insertPoolAddress = `-- name: InsertPoolAddress :one
INSERT INTO crypto_address_pool (
    tenant_id, chain, address, derivation_index
) VALUES (
    $1, $2, $3, $4
) RETURNING id, tenant_id, chain, address, derivation_index, dispensed, dispensed_at, session_id, created_at
`

type InsertPoolAddressParams struct {
	TenantID        uuid.UUID `json:"tenant_id"`
	Chain           string    `json:"chain"`
	Address         string    `json:"address"`
	DerivationIndex int64     `json:"derivation_index"`
}

func (q *Queries) InsertPoolAddress(ctx context.Context, arg InsertPoolAddressParams) (CryptoAddressPool, error) {
	row := q.db.QueryRow(ctx, insertPoolAddress,
		arg.TenantID,
		arg.Chain,
		arg.Address,
		arg.DerivationIndex,
	)
	var i CryptoAddressPool
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Chain,
		&i.Address,
		&i.DerivationIndex,
		&i.Dispensed,
		&i.DispensedAt,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const listPoolAddressesByTenant = `-- name: ListPoolAddressesByTenant :many
SELECT id, tenant_id, chain, address, derivation_index, dispensed, dispensed_at, session_id, created_at FROM crypto_address_pool
WHERE tenant_id = $1 AND chain = $2
ORDER BY derivation_index ASC
LIMIT $3 OFFSET $4
`

type ListPoolAddressesByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Chain    string    `json:"chain"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListPoolAddressesByTenant(ctx context.Context, arg ListPoolAddressesByTenantParams) ([]CryptoAddressPool, error) {
	rows, err := q.db.Query(ctx, listPoolAddressesByTenant,
		arg.TenantID,
		arg.Chain,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CryptoAddressPool{}
	for rows.Next() {
		var i CryptoAddressPool
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Chain,
			&i.Address,
			&i.DerivationIndex,
			&i.Dispensed,
			&i.DispensedAt,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
