// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package transferdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	KeyHash     string             `json:"key_hash"`
	KeyPrefix   string             `json:"key_prefix"`
	Environment string             `json:"environment"`
	Name        pgtype.Text        `json:"name"`
	IsActive    bool               `json:"is_active"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type ProviderTransaction struct {
	ID         uuid.UUID      `json:"id"`
	TenantID   uuid.UUID      `json:"tenant_id"`
	Provider   string         `json:"provider"`
	TxType     string         `json:"tx_type"`
	ExternalID pgtype.Text    `json:"external_id"`
	TransferID uuid.UUID      `json:"transfer_id"`
	Status     string         `json:"status"`
	Amount     pgtype.Numeric `json:"amount"`
	Currency   string         `json:"currency"`
	Chain      pgtype.Text    `json:"chain"`
	TxHash     pgtype.Text    `json:"tx_hash"`
	Metadata   []byte         `json:"metadata"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Quote struct {
	ID             uuid.UUID      `json:"id"`
	TenantID       uuid.UUID      `json:"tenant_id"`
	SourceCurrency string         `json:"source_currency"`
	SourceAmount   pgtype.Numeric `json:"source_amount"`
	DestCurrency   string         `json:"dest_currency"`
	DestAmount     pgtype.Numeric `json:"dest_amount"`
	FxRate         pgtype.Numeric `json:"fx_rate"`
	Fees           []byte         `json:"fees"`
	Route          []byte         `json:"route"`
	ExpiresAt      time.Time      `json:"expires_at"`
	CreatedAt      time.Time      `json:"created_at"`
	StableAmount   pgtype.Numeric `json:"stable_amount"`
}

type Tenant struct {
	ID               uuid.UUID          `json:"id"`
	Name             string             `json:"name"`
	Slug             string             `json:"slug"`
	Status           string             `json:"status"`
	FeeSchedule      []byte             `json:"fee_schedule"`
	SettlementModel  string             `json:"settlement_model"`
	WebhookUrl       pgtype.Text        `json:"webhook_url"`
	WebhookSecret    pgtype.Text        `json:"webhook_secret"`
	DailyLimitUsd    pgtype.Numeric     `json:"daily_limit_usd"`
	PerTransferLimit pgtype.Numeric     `json:"per_transfer_limit"`
	KybStatus        string             `json:"kyb_status"`
	KybVerifiedAt    pgtype.Timestamptz `json:"kyb_verified_at"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type Transfer struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	ExternalRef       pgtype.Text        `json:"external_ref"`
	IdempotencyKey    pgtype.Text        `json:"idempotency_key"`
	Status            string             `json:"status"`
	Version           int64              `json:"version"`
	SourceCurrency    string             `json:"source_currency"`
	SourceAmount      pgtype.Numeric     `json:"source_amount"`
	DestCurrency      string             `json:"dest_currency"`
	DestAmount        pgtype.Numeric     `json:"dest_amount"`
	StableCoin        pgtype.Text        `json:"stable_coin"`
	StableAmount      pgtype.Numeric     `json:"stable_amount"`
	Chain             pgtype.Text        `json:"chain"`
	FxRate            pgtype.Numeric     `json:"fx_rate"`
	Fees              []byte             `json:"fees"`
	Sender            []byte             `json:"sender"`
	Recipient         []byte             `json:"recipient"`
	QuoteID           pgtype.UUID        `json:"quote_id"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	FundedAt          pgtype.Timestamptz `json:"funded_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	FailedAt          pgtype.Timestamptz `json:"failed_at"`
	FailureReason     pgtype.Text        `json:"failure_reason"`
	FailureCode       pgtype.Text        `json:"failure_code"`
	OnRampProviderID  pgtype.Text        `json:"on_ramp_provider_id"`
	OffRampProviderID pgtype.Text        `json:"off_ramp_provider_id"`
}

type TransferEvent struct {
	ID          uuid.UUID   `json:"id"`
	TransferID  uuid.UUID   `json:"transfer_id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	FromStatus  pgtype.Text `json:"from_status"`
	ToStatus    string      `json:"to_status"`
	OccurredAt  time.Time   `json:"occurred_at"`
	Metadata    []byte      `json:"metadata"`
	ProviderRef pgtype.Text `json:"provider_ref"`
	CreatedAt   time.Time   `json:"created_at"`
}

type TransferEventsDefault struct {
	ID          uuid.UUID   `json:"id"`
	TransferID  uuid.UUID   `json:"transfer_id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	FromStatus  pgtype.Text `json:"from_status"`
	ToStatus    string      `json:"to_status"`
	OccurredAt  time.Time   `json:"occurred_at"`
	Metadata    []byte      `json:"metadata"`
	ProviderRef pgtype.Text `json:"provider_ref"`
	CreatedAt   time.Time   `json:"created_at"`
}

type TransferEventsY2026m03 struct {
	ID          uuid.UUID   `json:"id"`
	TransferID  uuid.UUID   `json:"transfer_id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	FromStatus  pgtype.Text `json:"from_status"`
	ToStatus    string      `json:"to_status"`
	OccurredAt  time.Time   `json:"occurred_at"`
	Metadata    []byte      `json:"metadata"`
	ProviderRef pgtype.Text `json:"provider_ref"`
	CreatedAt   time.Time   `json:"created_at"`
}

type TransferEventsY2026m04 struct {
	ID          uuid.UUID   `json:"id"`
	TransferID  uuid.UUID   `json:"transfer_id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	FromStatus  pgtype.Text `json:"from_status"`
	ToStatus    string      `json:"to_status"`
	OccurredAt  time.Time   `json:"occurred_at"`
	Metadata    []byte      `json:"metadata"`
	ProviderRef pgtype.Text `json:"provider_ref"`
	CreatedAt   time.Time   `json:"created_at"`
}

type TransferEventsY2026m05 struct {
	ID          uuid.UUID   `json:"id"`
	TransferID  uuid.UUID   `json:"transfer_id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	FromStatus  pgtype.Text `json:"from_status"`
	ToStatus    string      `json:"to_status"`
	OccurredAt  time.Time   `json:"occurred_at"`
	Metadata    []byte      `json:"metadata"`
	ProviderRef pgtype.Text `json:"provider_ref"`
	CreatedAt   time.Time   `json:"created_at"`
}

type TransferEventsY2026m06 struct {
	ID          uuid.UUID   `json:"id"`
	TransferID  uuid.UUID   `json:"transfer_id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	FromStatus  pgtype.Text `json:"from_status"`
	ToStatus    string      `json:"to_status"`
	OccurredAt  time.Time   `json:"occurred_at"`
	Metadata    []byte      `json:"metadata"`
	ProviderRef pgtype.Text `json:"provider_ref"`
	CreatedAt   time.Time   `json:"created_at"`
}

type TransferEventsY2026m07 struct {
	ID          uuid.UUID   `json:"id"`
	TransferID  uuid.UUID   `json:"transfer_id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	FromStatus  pgtype.Text `json:"from_status"`
	ToStatus    string      `json:"to_status"`
	OccurredAt  time.Time   `json:"occurred_at"`
	Metadata    []byte      `json:"metadata"`
	ProviderRef pgtype.Text `json:"provider_ref"`
	CreatedAt   time.Time   `json:"created_at"`
}

type TransferEventsY2026m08 struct {
	ID          uuid.UUID   `json:"id"`
	TransferID  uuid.UUID   `json:"transfer_id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	FromStatus  pgtype.Text `json:"from_status"`
	ToStatus    string      `json:"to_status"`
	OccurredAt  time.Time   `json:"occurred_at"`
	Metadata    []byte      `json:"metadata"`
	ProviderRef pgtype.Text `json:"provider_ref"`
	CreatedAt   time.Time   `json:"created_at"`
}

type TransfersDefault struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	ExternalRef    pgtype.Text        `json:"external_ref"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	Status         string             `json:"status"`
	Version        int64              `json:"version"`
	SourceCurrency string             `json:"source_currency"`
	SourceAmount   pgtype.Numeric     `json:"source_amount"`
	DestCurrency   string             `json:"dest_currency"`
	DestAmount     pgtype.Numeric     `json:"dest_amount"`
	StableCoin     pgtype.Text        `json:"stable_coin"`
	StableAmount   pgtype.Numeric     `json:"stable_amount"`
	Chain          pgtype.Text        `json:"chain"`
	FxRate         pgtype.Numeric     `json:"fx_rate"`
	Fees           []byte             `json:"fees"`
	Sender         []byte             `json:"sender"`
	Recipient      []byte             `json:"recipient"`
	QuoteID        pgtype.UUID        `json:"quote_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	FundedAt       pgtype.Timestamptz `json:"funded_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	FailedAt       pgtype.Timestamptz `json:"failed_at"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
	FailureCode    pgtype.Text        `json:"failure_code"`
}

type TransfersY2026m03 struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	ExternalRef    pgtype.Text        `json:"external_ref"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	Status         string             `json:"status"`
	Version        int64              `json:"version"`
	SourceCurrency string             `json:"source_currency"`
	SourceAmount   pgtype.Numeric     `json:"source_amount"`
	DestCurrency   string             `json:"dest_currency"`
	DestAmount     pgtype.Numeric     `json:"dest_amount"`
	StableCoin     pgtype.Text        `json:"stable_coin"`
	StableAmount   pgtype.Numeric     `json:"stable_amount"`
	Chain          pgtype.Text        `json:"chain"`
	FxRate         pgtype.Numeric     `json:"fx_rate"`
	Fees           []byte             `json:"fees"`
	Sender         []byte             `json:"sender"`
	Recipient      []byte             `json:"recipient"`
	QuoteID        pgtype.UUID        `json:"quote_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	FundedAt       pgtype.Timestamptz `json:"funded_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	FailedAt       pgtype.Timestamptz `json:"failed_at"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
	FailureCode    pgtype.Text        `json:"failure_code"`
}

type TransfersY2026m04 struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	ExternalRef    pgtype.Text        `json:"external_ref"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	Status         string             `json:"status"`
	Version        int64              `json:"version"`
	SourceCurrency string             `json:"source_currency"`
	SourceAmount   pgtype.Numeric     `json:"source_amount"`
	DestCurrency   string             `json:"dest_currency"`
	DestAmount     pgtype.Numeric     `json:"dest_amount"`
	StableCoin     pgtype.Text        `json:"stable_coin"`
	StableAmount   pgtype.Numeric     `json:"stable_amount"`
	Chain          pgtype.Text        `json:"chain"`
	FxRate         pgtype.Numeric     `json:"fx_rate"`
	Fees           []byte             `json:"fees"`
	Sender         []byte             `json:"sender"`
	Recipient      []byte             `json:"recipient"`
	QuoteID        pgtype.UUID        `json:"quote_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	FundedAt       pgtype.Timestamptz `json:"funded_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	FailedAt       pgtype.Timestamptz `json:"failed_at"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
	FailureCode    pgtype.Text        `json:"failure_code"`
}

type TransfersY2026m05 struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	ExternalRef    pgtype.Text        `json:"external_ref"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	Status         string             `json:"status"`
	Version        int64              `json:"version"`
	SourceCurrency string             `json:"source_currency"`
	SourceAmount   pgtype.Numeric     `json:"source_amount"`
	DestCurrency   string             `json:"dest_currency"`
	DestAmount     pgtype.Numeric     `json:"dest_amount"`
	StableCoin     pgtype.Text        `json:"stable_coin"`
	StableAmount   pgtype.Numeric     `json:"stable_amount"`
	Chain          pgtype.Text        `json:"chain"`
	FxRate         pgtype.Numeric     `json:"fx_rate"`
	Fees           []byte             `json:"fees"`
	Sender         []byte             `json:"sender"`
	Recipient      []byte             `json:"recipient"`
	QuoteID        pgtype.UUID        `json:"quote_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	FundedAt       pgtype.Timestamptz `json:"funded_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	FailedAt       pgtype.Timestamptz `json:"failed_at"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
	FailureCode    pgtype.Text        `json:"failure_code"`
}

type TransfersY2026m06 struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	ExternalRef    pgtype.Text        `json:"external_ref"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	Status         string             `json:"status"`
	Version        int64              `json:"version"`
	SourceCurrency string             `json:"source_currency"`
	SourceAmount   pgtype.Numeric     `json:"source_amount"`
	DestCurrency   string             `json:"dest_currency"`
	DestAmount     pgtype.Numeric     `json:"dest_amount"`
	StableCoin     pgtype.Text        `json:"stable_coin"`
	StableAmount   pgtype.Numeric     `json:"stable_amount"`
	Chain          pgtype.Text        `json:"chain"`
	FxRate         pgtype.Numeric     `json:"fx_rate"`
	Fees           []byte             `json:"fees"`
	Sender         []byte             `json:"sender"`
	Recipient      []byte             `json:"recipient"`
	QuoteID        pgtype.UUID        `json:"quote_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	FundedAt       pgtype.Timestamptz `json:"funded_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	FailedAt       pgtype.Timestamptz `json:"failed_at"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
	FailureCode    pgtype.Text        `json:"failure_code"`
}

type TransfersY2026m07 struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	ExternalRef    pgtype.Text        `json:"external_ref"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	Status         string             `json:"status"`
	Version        int64              `json:"version"`
	SourceCurrency string             `json:"source_currency"`
	SourceAmount   pgtype.Numeric     `json:"source_amount"`
	DestCurrency   string             `json:"dest_currency"`
	DestAmount     pgtype.Numeric     `json:"dest_amount"`
	StableCoin     pgtype.Text        `json:"stable_coin"`
	StableAmount   pgtype.Numeric     `json:"stable_amount"`
	Chain          pgtype.Text        `json:"chain"`
	FxRate         pgtype.Numeric     `json:"fx_rate"`
	Fees           []byte             `json:"fees"`
	Sender         []byte             `json:"sender"`
	Recipient      []byte             `json:"recipient"`
	QuoteID        pgtype.UUID        `json:"quote_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	FundedAt       pgtype.Timestamptz `json:"funded_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	FailedAt       pgtype.Timestamptz `json:"failed_at"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
	FailureCode    pgtype.Text        `json:"failure_code"`
}

type TransfersY2026m08 struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	ExternalRef    pgtype.Text        `json:"external_ref"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	Status         string             `json:"status"`
	Version        int64              `json:"version"`
	SourceCurrency string             `json:"source_currency"`
	SourceAmount   pgtype.Numeric     `json:"source_amount"`
	DestCurrency   string             `json:"dest_currency"`
	DestAmount     pgtype.Numeric     `json:"dest_amount"`
	StableCoin     pgtype.Text        `json:"stable_coin"`
	StableAmount   pgtype.Numeric     `json:"stable_amount"`
	Chain          pgtype.Text        `json:"chain"`
	FxRate         pgtype.Numeric     `json:"fx_rate"`
	Fees           []byte             `json:"fees"`
	Sender         []byte             `json:"sender"`
	Recipient      []byte             `json:"recipient"`
	QuoteID        pgtype.UUID        `json:"quote_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	FundedAt       pgtype.Timestamptz `json:"funded_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	FailedAt       pgtype.Timestamptz `json:"failed_at"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
	FailureCode    pgtype.Text        `json:"failure_code"`
}
