// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operational.sql

package transferdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompensationRecord = `-- name: CreateCompensationRecord :one

INSERT INTO compensation_records (
    transfer_id, tenant_id, strategy, refund_amount, refund_currency
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, transfer_id, tenant_id, strategy, steps_completed, steps_failed, refund_amount, refund_currency, fx_loss, status, created_at, completed_at
`

type CreateCompensationRecordParams struct {
	TransferID     uuid.UUID                `json:"transfer_id"`
	TenantID       uuid.UUID                `json:"tenant_id"`
	Strategy       CompensationStrategyEnum `json:"strategy"`
	RefundAmount   pgtype.Numeric           `json:"refund_amount"`
	RefundCurrency pgtype.Text              `json:"refund_currency"`
}

// ============================================================================
// compensation_records
// ============================================================================
func (q *Queries) CreateCompensationRecord(ctx context.Context, arg CreateCompensationRecordParams) (CompensationRecord, error) {
	row := q.db.QueryRow(ctx, createCompensationRecord,
		arg.TransferID,
		arg.TenantID,
		arg.Strategy,
		arg.RefundAmount,
		arg.RefundCurrency,
	)
	var i CompensationRecord
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.TenantID,
		&i.Strategy,
		&i.StepsCompleted,
		&i.StepsFailed,
		&i.RefundAmount,
		&i.RefundCurrency,
		&i.FxLoss,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createManualReview = `-- name: CreateManualReview :one

INSERT INTO manual_reviews (
    transfer_id, tenant_id, status, transfer_status,
    stuck_since, attempted_recoveries
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, transfer_id, tenant_id, status, transfer_status, stuck_since, attempted_recoveries, resolution, resolved_by, resolved_at, created_at
`

type CreateManualReviewParams struct {
	TransferID          uuid.UUID        `json:"transfer_id"`
	TenantID            uuid.UUID        `json:"tenant_id"`
	Status              ReviewStatusEnum `json:"status"`
	TransferStatus      string           `json:"transfer_status"`
	StuckSince          time.Time        `json:"stuck_since"`
	AttemptedRecoveries int32            `json:"attempted_recoveries"`
}

// ============================================================================
// manual_reviews
// ============================================================================
func (q *Queries) CreateManualReview(ctx context.Context, arg CreateManualReviewParams) (ManualReview, error) {
	row := q.db.QueryRow(ctx, createManualReview,
		arg.TransferID,
		arg.TenantID,
		arg.Status,
		arg.TransferStatus,
		arg.StuckSince,
		arg.AttemptedRecoveries,
	)
	var i ManualReview
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.TenantID,
		&i.Status,
		&i.TransferStatus,
		&i.StuckSince,
		&i.AttemptedRecoveries,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createNetSettlementOps = `-- name: CreateNetSettlementOps :one

INSERT INTO net_settlements (
    tenant_id, period_start, period_end, corridors,
    net_by_currency, total_fees_usd, instructions, status, due_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, tenant_id, period_start, period_end, corridors, net_by_currency, total_fees_usd, instructions, status, due_date, settled_at, created_at
`

type CreateNetSettlementOpsParams struct {
	TenantID      uuid.UUID      `json:"tenant_id"`
	PeriodStart   time.Time      `json:"period_start"`
	PeriodEnd     time.Time      `json:"period_end"`
	Corridors     []byte         `json:"corridors"`
	NetByCurrency []byte         `json:"net_by_currency"`
	TotalFeesUsd  pgtype.Numeric `json:"total_fees_usd"`
	Instructions  []byte         `json:"instructions"`
	Status        string         `json:"status"`
	DueDate       pgtype.Date    `json:"due_date"`
}

// ============================================================================
// net_settlements
// ============================================================================
func (q *Queries) CreateNetSettlementOps(ctx context.Context, arg CreateNetSettlementOpsParams) (NetSettlement, error) {
	row := q.db.QueryRow(ctx, createNetSettlementOps,
		arg.TenantID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Corridors,
		arg.NetByCurrency,
		arg.TotalFeesUsd,
		arg.Instructions,
		arg.Status,
		arg.DueDate,
	)
	var i NetSettlement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Corridors,
		&i.NetByCurrency,
		&i.TotalFeesUsd,
		&i.Instructions,
		&i.Status,
		&i.DueDate,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const createReconciliationReport = `-- name: CreateReconciliationReport :one

INSERT INTO reconciliation_reports (
    job_name, run_at, duration_ms, checks_run, checks_passed,
    discrepancies, auto_corrected, needs_review
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, job_name, run_at, duration_ms, checks_run, checks_passed, discrepancies, auto_corrected, needs_review, created_at
`

type CreateReconciliationReportParams struct {
	JobName       string    `json:"job_name"`
	RunAt         time.Time `json:"run_at"`
	DurationMs    int32     `json:"duration_ms"`
	ChecksRun     int32     `json:"checks_run"`
	ChecksPassed  int32     `json:"checks_passed"`
	Discrepancies []byte    `json:"discrepancies"`
	AutoCorrected int32     `json:"auto_corrected"`
	NeedsReview   bool      `json:"needs_review"`
}

// ============================================================================
// reconciliation_reports
// ============================================================================
func (q *Queries) CreateReconciliationReport(ctx context.Context, arg CreateReconciliationReportParams) (ReconciliationReport, error) {
	row := q.db.QueryRow(ctx, createReconciliationReport,
		arg.JobName,
		arg.RunAt,
		arg.DurationMs,
		arg.ChecksRun,
		arg.ChecksPassed,
		arg.Discrepancies,
		arg.AutoCorrected,
		arg.NeedsReview,
	)
	var i ReconciliationReport
	err := row.Scan(
		&i.ID,
		&i.JobName,
		&i.RunAt,
		&i.DurationMs,
		&i.ChecksRun,
		&i.ChecksPassed,
		&i.Discrepancies,
		&i.AutoCorrected,
		&i.NeedsReview,
		&i.CreatedAt,
	)
	return i, err
}

const getCompensationRecord = `-- name: GetCompensationRecord :one
SELECT id, transfer_id, tenant_id, strategy, steps_completed, steps_failed, refund_amount, refund_currency, fx_loss, status, created_at, completed_at FROM compensation_records
WHERE id = $1
`

func (q *Queries) GetCompensationRecord(ctx context.Context, id uuid.UUID) (CompensationRecord, error) {
	row := q.db.QueryRow(ctx, getCompensationRecord, id)
	var i CompensationRecord
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.TenantID,
		&i.Strategy,
		&i.StepsCompleted,
		&i.StepsFailed,
		&i.RefundAmount,
		&i.RefundCurrency,
		&i.FxLoss,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getManualReview = `-- name: GetManualReview :one
SELECT id, transfer_id, tenant_id, status, transfer_status, stuck_since, attempted_recoveries, resolution, resolved_by, resolved_at, created_at FROM manual_reviews
WHERE id = $1
`

func (q *Queries) GetManualReview(ctx context.Context, id uuid.UUID) (ManualReview, error) {
	row := q.db.QueryRow(ctx, getManualReview, id)
	var i ManualReview
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.TenantID,
		&i.Status,
		&i.TransferStatus,
		&i.StuckSince,
		&i.AttemptedRecoveries,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNetSettlementOps = `-- name: GetNetSettlementOps :one
SELECT id, tenant_id, period_start, period_end, corridors, net_by_currency, total_fees_usd, instructions, status, due_date, settled_at, created_at FROM net_settlements
WHERE id = $1
`

func (q *Queries) GetNetSettlementOps(ctx context.Context, id uuid.UUID) (NetSettlement, error) {
	row := q.db.QueryRow(ctx, getNetSettlementOps, id)
	var i NetSettlement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Corridors,
		&i.NetByCurrency,
		&i.TotalFeesUsd,
		&i.Instructions,
		&i.Status,
		&i.DueDate,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getReconciliationReport = `-- name: GetReconciliationReport :one
SELECT id, job_name, run_at, duration_ms, checks_run, checks_passed, discrepancies, auto_corrected, needs_review, created_at FROM reconciliation_reports
WHERE id = $1
`

func (q *Queries) GetReconciliationReport(ctx context.Context, id uuid.UUID) (ReconciliationReport, error) {
	row := q.db.QueryRow(ctx, getReconciliationReport, id)
	var i ReconciliationReport
	err := row.Scan(
		&i.ID,
		&i.JobName,
		&i.RunAt,
		&i.DurationMs,
		&i.ChecksRun,
		&i.ChecksPassed,
		&i.Discrepancies,
		&i.AutoCorrected,
		&i.NeedsReview,
		&i.CreatedAt,
	)
	return i, err
}

const listManualReviewsByStatus = `-- name: ListManualReviewsByStatus :many
SELECT id, transfer_id, tenant_id, status, transfer_status, stuck_since, attempted_recoveries, resolution, resolved_by, resolved_at, created_at FROM manual_reviews
WHERE tenant_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListManualReviewsByStatusParams struct {
	TenantID uuid.UUID        `json:"tenant_id"`
	Status   ReviewStatusEnum `json:"status"`
	Limit    int32            `json:"limit"`
	Offset   int32            `json:"offset"`
}

func (q *Queries) ListManualReviewsByStatus(ctx context.Context, arg ListManualReviewsByStatusParams) ([]ManualReview, error) {
	rows, err := q.db.Query(ctx, listManualReviewsByStatus,
		arg.TenantID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManualReview{}
	for rows.Next() {
		var i ManualReview
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.TenantID,
			&i.Status,
			&i.TransferStatus,
			&i.StuckSince,
			&i.AttemptedRecoveries,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualReviewsByStatusCursor = `-- name: ListManualReviewsByStatusCursor :many

SELECT id, transfer_id, tenant_id, status, transfer_status, stuck_since, attempted_recoveries, resolution, resolved_by, resolved_at, created_at FROM manual_reviews
WHERE tenant_id = $1 AND status = $2
  AND ($3::timestamptz IS NULL OR created_at < $3)
ORDER BY created_at DESC
LIMIT $4
`

type ListManualReviewsByStatusCursorParams struct {
	TenantID        uuid.UUID        `json:"tenant_id"`
	Status          ReviewStatusEnum `json:"status"`
	CursorCreatedAt time.Time        `json:"cursor_created_at"`
	PageSize        int32            `json:"page_size"`
}

// ============================================================================
// Cursor-based pagination queries
// ============================================================================
func (q *Queries) ListManualReviewsByStatusCursor(ctx context.Context, arg ListManualReviewsByStatusCursorParams) ([]ManualReview, error) {
	rows, err := q.db.Query(ctx, listManualReviewsByStatusCursor,
		arg.TenantID,
		arg.Status,
		arg.CursorCreatedAt,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManualReview{}
	for rows.Next() {
		var i ManualReview
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.TenantID,
			&i.Status,
			&i.TransferStatus,
			&i.StuckSince,
			&i.AttemptedRecoveries,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualReviewsByTenant = `-- name: ListManualReviewsByTenant :many
SELECT id, transfer_id, tenant_id, status, transfer_status, stuck_since, attempted_recoveries, resolution, resolved_by, resolved_at, created_at FROM manual_reviews
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListManualReviewsByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListManualReviewsByTenant(ctx context.Context, arg ListManualReviewsByTenantParams) ([]ManualReview, error) {
	rows, err := q.db.Query(ctx, listManualReviewsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManualReview{}
	for rows.Next() {
		var i ManualReview
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.TenantID,
			&i.Status,
			&i.TransferStatus,
			&i.StuckSince,
			&i.AttemptedRecoveries,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualReviewsByTenantCursor = `-- name: ListManualReviewsByTenantCursor :many
SELECT id, transfer_id, tenant_id, status, transfer_status, stuck_since, attempted_recoveries, resolution, resolved_by, resolved_at, created_at FROM manual_reviews
WHERE tenant_id = $1
  AND ($2::timestamptz IS NULL OR created_at < $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListManualReviewsByTenantCursorParams struct {
	TenantID        uuid.UUID `json:"tenant_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	PageSize        int32     `json:"page_size"`
}

func (q *Queries) ListManualReviewsByTenantCursor(ctx context.Context, arg ListManualReviewsByTenantCursorParams) ([]ManualReview, error) {
	rows, err := q.db.Query(ctx, listManualReviewsByTenantCursor, arg.TenantID, arg.CursorCreatedAt, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManualReview{}
	for rows.Next() {
		var i ManualReview
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.TenantID,
			&i.Status,
			&i.TransferStatus,
			&i.StuckSince,
			&i.AttemptedRecoveries,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetSettlementsByStatus = `-- name: ListNetSettlementsByStatus :many
SELECT id, tenant_id, period_start, period_end, corridors, net_by_currency, total_fees_usd, instructions, status, due_date, settled_at, created_at FROM net_settlements
WHERE tenant_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListNetSettlementsByStatusParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Status   string    `json:"status"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListNetSettlementsByStatus(ctx context.Context, arg ListNetSettlementsByStatusParams) ([]NetSettlement, error) {
	rows, err := q.db.Query(ctx, listNetSettlementsByStatus,
		arg.TenantID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NetSettlement{}
	for rows.Next() {
		var i NetSettlement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Corridors,
			&i.NetByCurrency,
			&i.TotalFeesUsd,
			&i.Instructions,
			&i.Status,
			&i.DueDate,
			&i.SettledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetSettlementsByStatusCursor = `-- name: ListNetSettlementsByStatusCursor :many
SELECT id, tenant_id, period_start, period_end, corridors, net_by_currency, total_fees_usd, instructions, status, due_date, settled_at, created_at FROM net_settlements
WHERE tenant_id = $1 AND status = $2
  AND ($3::timestamptz IS NULL OR created_at < $3)
ORDER BY created_at DESC
LIMIT $4
`

type ListNetSettlementsByStatusCursorParams struct {
	TenantID        uuid.UUID `json:"tenant_id"`
	Status          string    `json:"status"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	PageSize        int32     `json:"page_size"`
}

func (q *Queries) ListNetSettlementsByStatusCursor(ctx context.Context, arg ListNetSettlementsByStatusCursorParams) ([]NetSettlement, error) {
	rows, err := q.db.Query(ctx, listNetSettlementsByStatusCursor,
		arg.TenantID,
		arg.Status,
		arg.CursorCreatedAt,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NetSettlement{}
	for rows.Next() {
		var i NetSettlement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Corridors,
			&i.NetByCurrency,
			&i.TotalFeesUsd,
			&i.Instructions,
			&i.Status,
			&i.DueDate,
			&i.SettledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetSettlementsByTenant = `-- name: ListNetSettlementsByTenant :many
SELECT id, tenant_id, period_start, period_end, corridors, net_by_currency, total_fees_usd, instructions, status, due_date, settled_at, created_at FROM net_settlements
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNetSettlementsByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListNetSettlementsByTenant(ctx context.Context, arg ListNetSettlementsByTenantParams) ([]NetSettlement, error) {
	rows, err := q.db.Query(ctx, listNetSettlementsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NetSettlement{}
	for rows.Next() {
		var i NetSettlement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Corridors,
			&i.NetByCurrency,
			&i.TotalFeesUsd,
			&i.Instructions,
			&i.Status,
			&i.DueDate,
			&i.SettledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetSettlementsByTenantCursor = `-- name: ListNetSettlementsByTenantCursor :many
SELECT id, tenant_id, period_start, period_end, corridors, net_by_currency, total_fees_usd, instructions, status, due_date, settled_at, created_at FROM net_settlements
WHERE tenant_id = $1
  AND ($2::timestamptz IS NULL OR created_at < $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListNetSettlementsByTenantCursorParams struct {
	TenantID        uuid.UUID `json:"tenant_id"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	PageSize        int32     `json:"page_size"`
}

func (q *Queries) ListNetSettlementsByTenantCursor(ctx context.Context, arg ListNetSettlementsByTenantCursorParams) ([]NetSettlement, error) {
	rows, err := q.db.Query(ctx, listNetSettlementsByTenantCursor, arg.TenantID, arg.CursorCreatedAt, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NetSettlement{}
	for rows.Next() {
		var i NetSettlement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Corridors,
			&i.NetByCurrency,
			&i.TotalFeesUsd,
			&i.Instructions,
			&i.Status,
			&i.DueDate,
			&i.SettledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationReports = `-- name: ListReconciliationReports :many
SELECT id, job_name, run_at, duration_ms, checks_run, checks_passed, discrepancies, auto_corrected, needs_review, created_at FROM reconciliation_reports
ORDER BY run_at DESC
LIMIT $1 OFFSET $2
`

type ListReconciliationReportsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListReconciliationReports(ctx context.Context, arg ListReconciliationReportsParams) ([]ReconciliationReport, error) {
	rows, err := q.db.Query(ctx, listReconciliationReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconciliationReport{}
	for rows.Next() {
		var i ReconciliationReport
		if err := rows.Scan(
			&i.ID,
			&i.JobName,
			&i.RunAt,
			&i.DurationMs,
			&i.ChecksRun,
			&i.ChecksPassed,
			&i.Discrepancies,
			&i.AutoCorrected,
			&i.NeedsReview,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationReportsCursor = `-- name: ListReconciliationReportsCursor :many
SELECT id, job_name, run_at, duration_ms, checks_run, checks_passed, discrepancies, auto_corrected, needs_review, created_at FROM reconciliation_reports
WHERE ($1::timestamptz IS NULL OR run_at < $1)
ORDER BY run_at DESC
LIMIT $2
`

type ListReconciliationReportsCursorParams struct {
	CursorRunAt time.Time `json:"cursor_run_at"`
	PageSize    int32     `json:"page_size"`
}

func (q *Queries) ListReconciliationReportsCursor(ctx context.Context, arg ListReconciliationReportsCursorParams) ([]ReconciliationReport, error) {
	rows, err := q.db.Query(ctx, listReconciliationReportsCursor, arg.CursorRunAt, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconciliationReport{}
	for rows.Next() {
		var i ReconciliationReport
		if err := rows.Scan(
			&i.ID,
			&i.JobName,
			&i.RunAt,
			&i.DurationMs,
			&i.ChecksRun,
			&i.ChecksPassed,
			&i.Discrepancies,
			&i.AutoCorrected,
			&i.NeedsReview,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompensationRecord = `-- name: UpdateCompensationRecord :exec
UPDATE compensation_records
SET steps_completed = $2,
    steps_failed = $3,
    fx_loss = $4,
    status = $5,
    completed_at = CASE WHEN $5 = 'completed' THEN now() ELSE completed_at END
WHERE id = $1
`

type UpdateCompensationRecordParams struct {
	ID             uuid.UUID      `json:"id"`
	StepsCompleted []byte         `json:"steps_completed"`
	StepsFailed    []byte         `json:"steps_failed"`
	FxLoss         pgtype.Numeric `json:"fx_loss"`
	Status         string         `json:"status"`
}

func (q *Queries) UpdateCompensationRecord(ctx context.Context, arg UpdateCompensationRecordParams) error {
	_, err := q.db.Exec(ctx, updateCompensationRecord,
		arg.ID,
		arg.StepsCompleted,
		arg.StepsFailed,
		arg.FxLoss,
		arg.Status,
	)
	return err
}

const updateManualReview = `-- name: UpdateManualReview :exec
UPDATE manual_reviews
SET status = $2,
    resolution = $3,
    resolved_by = $4,
    resolved_at = CASE WHEN $2 = 'resolved' THEN now() ELSE resolved_at END
WHERE id = $1
`

type UpdateManualReviewParams struct {
	ID         uuid.UUID        `json:"id"`
	Status     ReviewStatusEnum `json:"status"`
	Resolution pgtype.Text      `json:"resolution"`
	ResolvedBy pgtype.Text      `json:"resolved_by"`
}

func (q *Queries) UpdateManualReview(ctx context.Context, arg UpdateManualReviewParams) error {
	_, err := q.db.Exec(ctx, updateManualReview,
		arg.ID,
		arg.Status,
		arg.Resolution,
		arg.ResolvedBy,
	)
	return err
}
