// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package transferdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getOutboxEntriesByAggregate = `-- name: GetOutboxEntriesByAggregate :many
SELECT id, aggregate_type, aggregate_id, tenant_id, event_type,
    payload, is_intent, published, published_at, retry_count, max_retries, created_at
FROM outbox
WHERE aggregate_type = $1 AND aggregate_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetOutboxEntriesByAggregateParams struct {
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

func (q *Queries) GetOutboxEntriesByAggregate(ctx context.Context, arg GetOutboxEntriesByAggregateParams) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getOutboxEntriesByAggregate,
		arg.AggregateType,
		arg.AggregateID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.TenantID,
			&i.EventType,
			&i.Payload,
			&i.IsIntent,
			&i.Published,
			&i.PublishedAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnpublishedEntries = `-- name: GetUnpublishedEntries :many
SELECT id, aggregate_type, aggregate_id, tenant_id, event_type,
    payload, is_intent, published, published_at, retry_count, max_retries, created_at
FROM outbox
WHERE published = false
  AND retry_count < max_retries
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetUnpublishedEntries(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getUnpublishedEntries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.TenantID,
			&i.EventType,
			&i.Payload,
			&i.IsIntent,
			&i.Published,
			&i.PublishedAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertOutboxEntriesParams struct {
	ID            uuid.UUID `json:"id"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
	IsIntent      bool      `json:"is_intent"`
	MaxRetries    int32     `json:"max_retries"`
	CreatedAt     time.Time `json:"created_at"`
}

const insertOutboxEntry = `-- name: InsertOutboxEntry :one
INSERT INTO outbox (
    aggregate_type, aggregate_id, tenant_id, event_type,
    payload, is_intent, max_retries, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, now()
) RETURNING id, aggregate_type, aggregate_id, tenant_id, event_type,
    payload, is_intent, published, published_at, retry_count, max_retries, created_at
`

type InsertOutboxEntryParams struct {
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
	IsIntent      bool      `json:"is_intent"`
	MaxRetries    int32     `json:"max_retries"`
}

func (q *Queries) InsertOutboxEntry(ctx context.Context, arg InsertOutboxEntryParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, insertOutboxEntry,
		arg.AggregateType,
		arg.AggregateID,
		arg.TenantID,
		arg.EventType,
		arg.Payload,
		arg.IsIntent,
		arg.MaxRetries,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.TenantID,
		&i.EventType,
		&i.Payload,
		&i.IsIntent,
		&i.Published,
		&i.PublishedAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CreatedAt,
	)
	return i, err
}

const markFailed = `-- name: MarkFailed :exec
UPDATE outbox
SET retry_count = retry_count + 1
WHERE id = $1 AND created_at = $2
`

type MarkFailedParams struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) error {
	_, err := q.db.Exec(ctx, markFailed, arg.ID, arg.CreatedAt)
	return err
}

const markPublished = `-- name: MarkPublished :exec
UPDATE outbox
SET published = true, published_at = now()
WHERE id = $1 AND created_at = $2 AND published = false
`

type MarkPublishedParams struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) MarkPublished(ctx context.Context, arg MarkPublishedParams) error {
	_, err := q.db.Exec(ctx, markPublished, arg.ID, arg.CreatedAt)
	return err
}
