// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_links.sql

package transferdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPaymentLinksByTenant = `-- name: CountPaymentLinksByTenant :one
SELECT count(*) FROM payment_links
WHERE tenant_id = $1
`

func (q *Queries) CountPaymentLinksByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentLinksByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPaymentLink = `-- name: CreatePaymentLink :one
INSERT INTO payment_links (
    tenant_id, short_code, description, session_config,
    use_limit, expires_at, redirect_url, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, tenant_id, short_code, description, session_config, use_limit, use_count, expires_at, redirect_url, status, created_at, updated_at
`

type CreatePaymentLinkParams struct {
	TenantID      uuid.UUID          `json:"tenant_id"`
	ShortCode     string             `json:"short_code"`
	Description   string             `json:"description"`
	SessionConfig []byte             `json:"session_config"`
	UseLimit      pgtype.Int4        `json:"use_limit"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	RedirectUrl   string             `json:"redirect_url"`
	Status        string             `json:"status"`
}

func (q *Queries) CreatePaymentLink(ctx context.Context, arg CreatePaymentLinkParams) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, createPaymentLink,
		arg.TenantID,
		arg.ShortCode,
		arg.Description,
		arg.SessionConfig,
		arg.UseLimit,
		arg.ExpiresAt,
		arg.RedirectUrl,
		arg.Status,
	)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ShortCode,
		&i.Description,
		&i.SessionConfig,
		&i.UseLimit,
		&i.UseCount,
		&i.ExpiresAt,
		&i.RedirectUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentLinkByID = `-- name: GetPaymentLinkByID :one
SELECT id, tenant_id, short_code, description, session_config, use_limit, use_count, expires_at, redirect_url, status, created_at, updated_at FROM payment_links
WHERE id = $1 AND tenant_id = $2
`

type GetPaymentLinkByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetPaymentLinkByID(ctx context.Context, arg GetPaymentLinkByIDParams) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, getPaymentLinkByID, arg.ID, arg.TenantID)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ShortCode,
		&i.Description,
		&i.SessionConfig,
		&i.UseLimit,
		&i.UseCount,
		&i.ExpiresAt,
		&i.RedirectUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentLinkByShortCode = `-- name: GetPaymentLinkByShortCode :one
SELECT id, tenant_id, short_code, description, session_config, use_limit, use_count, expires_at, redirect_url, status, created_at, updated_at FROM payment_links
WHERE short_code = $1
`

func (q *Queries) GetPaymentLinkByShortCode(ctx context.Context, shortCode string) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, getPaymentLinkByShortCode, shortCode)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ShortCode,
		&i.Description,
		&i.SessionConfig,
		&i.UseLimit,
		&i.UseCount,
		&i.ExpiresAt,
		&i.RedirectUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementPaymentLinkUseCount = `-- name: IncrementPaymentLinkUseCount :exec
UPDATE payment_links
SET use_count = use_count + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementPaymentLinkUseCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementPaymentLinkUseCount, id)
	return err
}

const listPaymentLinksByTenant = `-- name: ListPaymentLinksByTenant :many
SELECT id, tenant_id, short_code, description, session_config, use_limit, use_count, expires_at, redirect_url, status, created_at, updated_at FROM payment_links
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentLinksByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListPaymentLinksByTenant(ctx context.Context, arg ListPaymentLinksByTenantParams) ([]PaymentLink, error) {
	rows, err := q.db.Query(ctx, listPaymentLinksByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentLink{}
	for rows.Next() {
		var i PaymentLink
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ShortCode,
			&i.Description,
			&i.SessionConfig,
			&i.UseLimit,
			&i.UseCount,
			&i.ExpiresAt,
			&i.RedirectUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentLinkStatus = `-- name: UpdatePaymentLinkStatus :exec
UPDATE payment_links
SET status = $2, updated_at = now()
WHERE id = $1 AND tenant_id = $3
`

type UpdatePaymentLinkStatusParams struct {
	ID       uuid.UUID `json:"id"`
	Status   string    `json:"status"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdatePaymentLinkStatus(ctx context.Context, arg UpdatePaymentLinkStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentLinkStatus, arg.ID, arg.Status, arg.TenantID)
	return err
}
