// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portal_users.sql

package transferdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPortalUser = `-- name: CreatePortalUser :one
INSERT INTO portal_users (
    tenant_id, email, password_hash, display_name, role,
    email_token_hash, email_token_expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, tenant_id, email, password_hash, display_name, role, email_verified, email_token_hash, email_token_expires_at, last_login_at, created_at, updated_at
`

type CreatePortalUserParams struct {
	TenantID            uuid.UUID          `json:"tenant_id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	DisplayName         string             `json:"display_name"`
	Role                string             `json:"role"`
	EmailTokenHash      pgtype.Text        `json:"email_token_hash"`
	EmailTokenExpiresAt pgtype.Timestamptz `json:"email_token_expires_at"`
}

func (q *Queries) CreatePortalUser(ctx context.Context, arg CreatePortalUserParams) (PortalUser, error) {
	row := q.db.QueryRow(ctx, createPortalUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Role,
		arg.EmailTokenHash,
		arg.EmailTokenExpiresAt,
	)
	var i PortalUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.EmailVerified,
		&i.EmailTokenHash,
		&i.EmailTokenExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPortalUserByEmail = `-- name: GetPortalUserByEmail :one
SELECT pu.id, pu.tenant_id, pu.email, pu.password_hash, pu.display_name, pu.role, pu.email_verified, pu.email_token_hash, pu.email_token_expires_at, pu.last_login_at, pu.created_at, pu.updated_at, t.name AS tenant_name, t.slug AS tenant_slug,
       t.status AS tenant_status, t.kyb_status
FROM portal_users pu
JOIN tenants t ON t.id = pu.tenant_id
WHERE pu.email = $1
`

type GetPortalUserByEmailRow struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	DisplayName         string             `json:"display_name"`
	Role                string             `json:"role"`
	EmailVerified       bool               `json:"email_verified"`
	EmailTokenHash      pgtype.Text        `json:"email_token_hash"`
	EmailTokenExpiresAt pgtype.Timestamptz `json:"email_token_expires_at"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	TenantName          string             `json:"tenant_name"`
	TenantSlug          string             `json:"tenant_slug"`
	TenantStatus        string             `json:"tenant_status"`
	KybStatus           string             `json:"kyb_status"`
}

func (q *Queries) GetPortalUserByEmail(ctx context.Context, email string) (GetPortalUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getPortalUserByEmail, email)
	var i GetPortalUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.EmailVerified,
		&i.EmailTokenHash,
		&i.EmailTokenExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantName,
		&i.TenantSlug,
		&i.TenantStatus,
		&i.KybStatus,
	)
	return i, err
}

const getPortalUserByID = `-- name: GetPortalUserByID :one
SELECT pu.id, pu.tenant_id, pu.email, pu.password_hash, pu.display_name, pu.role, pu.email_verified, pu.email_token_hash, pu.email_token_expires_at, pu.last_login_at, pu.created_at, pu.updated_at, t.name AS tenant_name, t.slug AS tenant_slug,
       t.status AS tenant_status, t.kyb_status
FROM portal_users pu
JOIN tenants t ON t.id = pu.tenant_id
WHERE pu.id = $1
`

type GetPortalUserByIDRow struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	DisplayName         string             `json:"display_name"`
	Role                string             `json:"role"`
	EmailVerified       bool               `json:"email_verified"`
	EmailTokenHash      pgtype.Text        `json:"email_token_hash"`
	EmailTokenExpiresAt pgtype.Timestamptz `json:"email_token_expires_at"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	TenantName          string             `json:"tenant_name"`
	TenantSlug          string             `json:"tenant_slug"`
	TenantStatus        string             `json:"tenant_status"`
	KybStatus           string             `json:"kyb_status"`
}

func (q *Queries) GetPortalUserByID(ctx context.Context, id uuid.UUID) (GetPortalUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getPortalUserByID, id)
	var i GetPortalUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.EmailVerified,
		&i.EmailTokenHash,
		&i.EmailTokenExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantName,
		&i.TenantSlug,
		&i.TenantStatus,
		&i.KybStatus,
	)
	return i, err
}

const getPortalUsersByTenant = `-- name: GetPortalUsersByTenant :many
SELECT id, tenant_id, email, display_name, role, email_verified,
       last_login_at, created_at, updated_at
FROM portal_users
WHERE tenant_id = $1
ORDER BY created_at ASC
`

type GetPortalUsersByTenantRow struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	Role          string             `json:"role"`
	EmailVerified bool               `json:"email_verified"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

func (q *Queries) GetPortalUsersByTenant(ctx context.Context, tenantID uuid.UUID) ([]GetPortalUsersByTenantRow, error) {
	rows, err := q.db.Query(ctx, getPortalUsersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPortalUsersByTenantRow{}
	for rows.Next() {
		var i GetPortalUsersByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.EmailVerified,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePortalUserLastLogin = `-- name: UpdatePortalUserLastLogin :exec
UPDATE portal_users
SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdatePortalUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updatePortalUserLastLogin, id)
	return err
}

const verifyPortalUserEmail = `-- name: VerifyPortalUserEmail :exec
UPDATE portal_users
SET email_verified = true,
    email_token_hash = NULL,
    email_token_expires_at = NULL,
    updated_at = now()
WHERE email_token_hash = $1
  AND email_token_expires_at > now()
`

func (q *Queries) VerifyPortalUserEmail(ctx context.Context, emailTokenHash pgtype.Text) error {
	_, err := q.db.Exec(ctx, verifyPortalUserEmail, emailTokenHash)
	return err
}
