// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: position_transactions.sql

package transferdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPositionTransactionsByTenant = `-- name: CountPositionTransactionsByTenant :one
SELECT count(*) FROM position_transactions
WHERE tenant_id = $1
`

func (q *Queries) CountPositionTransactionsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPositionTransactionsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPositionTransaction = `-- name: CreatePositionTransaction :one
INSERT INTO position_transactions (
    id, tenant_id, type, currency, location, amount, status, method, destination, reference, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, tenant_id, type, currency, location, amount, status, method, destination, reference, failure_reason, version, created_at, updated_at
`

type CreatePositionTransactionParams struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Type        string         `json:"type"`
	Currency    string         `json:"currency"`
	Location    string         `json:"location"`
	Amount      pgtype.Numeric `json:"amount"`
	Status      string         `json:"status"`
	Method      string         `json:"method"`
	Destination string         `json:"destination"`
	Reference   string         `json:"reference"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) CreatePositionTransaction(ctx context.Context, arg CreatePositionTransactionParams) (PositionTransaction, error) {
	row := q.db.QueryRow(ctx, createPositionTransaction,
		arg.ID,
		arg.TenantID,
		arg.Type,
		arg.Currency,
		arg.Location,
		arg.Amount,
		arg.Status,
		arg.Method,
		arg.Destination,
		arg.Reference,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PositionTransaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Currency,
		&i.Location,
		&i.Amount,
		&i.Status,
		&i.Method,
		&i.Destination,
		&i.Reference,
		&i.FailureReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPositionTransaction = `-- name: GetPositionTransaction :one
SELECT id, tenant_id, type, currency, location, amount, status, method, destination, reference, failure_reason, version, created_at, updated_at FROM position_transactions
WHERE id = $1 AND tenant_id = $2
`

type GetPositionTransactionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetPositionTransaction(ctx context.Context, arg GetPositionTransactionParams) (PositionTransaction, error) {
	row := q.db.QueryRow(ctx, getPositionTransaction, arg.ID, arg.TenantID)
	var i PositionTransaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Currency,
		&i.Location,
		&i.Amount,
		&i.Status,
		&i.Method,
		&i.Destination,
		&i.Reference,
		&i.FailureReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPositionTransactionsByTenant = `-- name: ListPositionTransactionsByTenant :many
SELECT id, tenant_id, type, currency, location, amount, status, method, destination, reference, failure_reason, version, created_at, updated_at FROM position_transactions
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPositionTransactionsByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListPositionTransactionsByTenant(ctx context.Context, arg ListPositionTransactionsByTenantParams) ([]PositionTransaction, error) {
	rows, err := q.db.Query(ctx, listPositionTransactionsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PositionTransaction{}
	for rows.Next() {
		var i PositionTransaction
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Currency,
			&i.Location,
			&i.Amount,
			&i.Status,
			&i.Method,
			&i.Destination,
			&i.Reference,
			&i.FailureReason,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionTransactionsByTenantAndStatus = `-- name: ListPositionTransactionsByTenantAndStatus :many
SELECT id, tenant_id, type, currency, location, amount, status, method, destination, reference, failure_reason, version, created_at, updated_at FROM position_transactions
WHERE tenant_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListPositionTransactionsByTenantAndStatusParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Status   string    `json:"status"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListPositionTransactionsByTenantAndStatus(ctx context.Context, arg ListPositionTransactionsByTenantAndStatusParams) ([]PositionTransaction, error) {
	rows, err := q.db.Query(ctx, listPositionTransactionsByTenantAndStatus,
		arg.TenantID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PositionTransaction{}
	for rows.Next() {
		var i PositionTransaction
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Currency,
			&i.Location,
			&i.Amount,
			&i.Status,
			&i.Method,
			&i.Destination,
			&i.Reference,
			&i.FailureReason,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePositionTransactionStatus = `-- name: UpdatePositionTransactionStatus :exec
UPDATE position_transactions
SET status = $3, failure_reason = $4, version = version + 1, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdatePositionTransactionStatusParams struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	Status        string    `json:"status"`
	FailureReason string    `json:"failure_reason"`
}

func (q *Queries) UpdatePositionTransactionStatus(ctx context.Context, arg UpdatePositionTransactionStatusParams) error {
	_, err := q.db.Exec(ctx, updatePositionTransactionStatus,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.FailureReason,
	)
	return err
}
