// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_webhook_logs.sql

package transferdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkWebhookDuplicate = `-- name: CheckWebhookDuplicate :one
SELECT id, status FROM provider_webhook_logs
WHERE provider_slug = $1 AND idempotency_key = $2 AND status = 'processed'
ORDER BY created_at DESC LIMIT 1
`

type CheckWebhookDuplicateParams struct {
	ProviderSlug   string `json:"provider_slug"`
	IdempotencyKey string `json:"idempotency_key"`
}

type CheckWebhookDuplicateRow struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) CheckWebhookDuplicate(ctx context.Context, arg CheckWebhookDuplicateParams) (CheckWebhookDuplicateRow, error) {
	row := q.db.QueryRow(ctx, checkWebhookDuplicate, arg.ProviderSlug, arg.IdempotencyKey)
	var i CheckWebhookDuplicateRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getProviderWebhookLog = `-- name: GetProviderWebhookLog :one
SELECT id, provider_slug, idempotency_key, transfer_id, tenant_id,
       raw_body, normalized, status, error_message, http_headers,
       source_ip, created_at, processed_at
FROM provider_webhook_logs
WHERE id = $1 AND created_at = $2
`

type GetProviderWebhookLogParams struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetProviderWebhookLog(ctx context.Context, arg GetProviderWebhookLogParams) (ProviderWebhookLog, error) {
	row := q.db.QueryRow(ctx, getProviderWebhookLog, arg.ID, arg.CreatedAt)
	var i ProviderWebhookLog
	err := row.Scan(
		&i.ID,
		&i.ProviderSlug,
		&i.IdempotencyKey,
		&i.TransferID,
		&i.TenantID,
		&i.RawBody,
		&i.Normalized,
		&i.Status,
		&i.ErrorMessage,
		&i.HttpHeaders,
		&i.SourceIp,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const insertProviderWebhookLog = `-- name: InsertProviderWebhookLog :one
INSERT INTO provider_webhook_logs (
    provider_slug, idempotency_key, raw_body, http_headers, source_ip, status
) VALUES ($1, $2, $3, $4, $5, 'received')
ON CONFLICT (provider_slug, idempotency_key, created_at) DO NOTHING
RETURNING id, created_at
`

type InsertProviderWebhookLogParams struct {
	ProviderSlug   string      `json:"provider_slug"`
	IdempotencyKey string      `json:"idempotency_key"`
	RawBody        []byte      `json:"raw_body"`
	HttpHeaders    []byte      `json:"http_headers"`
	SourceIp       pgtype.Text `json:"source_ip"`
}

type InsertProviderWebhookLogRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertProviderWebhookLog(ctx context.Context, arg InsertProviderWebhookLogParams) (InsertProviderWebhookLogRow, error) {
	row := q.db.QueryRow(ctx, insertProviderWebhookLog,
		arg.ProviderSlug,
		arg.IdempotencyKey,
		arg.RawBody,
		arg.HttpHeaders,
		arg.SourceIp,
	)
	var i InsertProviderWebhookLogRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listProviderWebhookLogsByProvider = `-- name: ListProviderWebhookLogsByProvider :many
SELECT id, provider_slug, idempotency_key, transfer_id, tenant_id,
       status, error_message, created_at, processed_at
FROM provider_webhook_logs
WHERE provider_slug = $1 AND status = COALESCE($4, status)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProviderWebhookLogsByProviderParams struct {
	ProviderSlug string      `json:"provider_slug"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
	StatusFilter pgtype.Text `json:"status_filter"`
}

type ListProviderWebhookLogsByProviderRow struct {
	ID             uuid.UUID          `json:"id"`
	ProviderSlug   string             `json:"provider_slug"`
	IdempotencyKey string             `json:"idempotency_key"`
	TransferID     pgtype.UUID        `json:"transfer_id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Status         string             `json:"status"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	CreatedAt      time.Time          `json:"created_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
}

func (q *Queries) ListProviderWebhookLogsByProvider(ctx context.Context, arg ListProviderWebhookLogsByProviderParams) ([]ListProviderWebhookLogsByProviderRow, error) {
	rows, err := q.db.Query(ctx, listProviderWebhookLogsByProvider,
		arg.ProviderSlug,
		arg.Limit,
		arg.Offset,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProviderWebhookLogsByProviderRow{}
	for rows.Next() {
		var i ListProviderWebhookLogsByProviderRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderSlug,
			&i.IdempotencyKey,
			&i.TransferID,
			&i.TenantID,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderWebhookLogsByTransfer = `-- name: ListProviderWebhookLogsByTransfer :many
SELECT id, provider_slug, idempotency_key, transfer_id, tenant_id,
       status, error_message, created_at, processed_at
FROM provider_webhook_logs
WHERE transfer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProviderWebhookLogsByTransferParams struct {
	TransferID pgtype.UUID `json:"transfer_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListProviderWebhookLogsByTransferRow struct {
	ID             uuid.UUID          `json:"id"`
	ProviderSlug   string             `json:"provider_slug"`
	IdempotencyKey string             `json:"idempotency_key"`
	TransferID     pgtype.UUID        `json:"transfer_id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Status         string             `json:"status"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	CreatedAt      time.Time          `json:"created_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
}

func (q *Queries) ListProviderWebhookLogsByTransfer(ctx context.Context, arg ListProviderWebhookLogsByTransferParams) ([]ListProviderWebhookLogsByTransferRow, error) {
	rows, err := q.db.Query(ctx, listProviderWebhookLogsByTransfer, arg.TransferID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProviderWebhookLogsByTransferRow{}
	for rows.Next() {
		var i ListProviderWebhookLogsByTransferRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderSlug,
			&i.IdempotencyKey,
			&i.TransferID,
			&i.TenantID,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookLogProcessed = `-- name: UpdateWebhookLogProcessed :exec
UPDATE provider_webhook_logs
SET transfer_id = $2,
    tenant_id = $3,
    normalized = $4,
    status = $5,
    error_message = $6,
    processed_at = now()
WHERE id = $1 AND created_at = $7
`

type UpdateWebhookLogProcessedParams struct {
	ID           uuid.UUID   `json:"id"`
	TransferID   pgtype.UUID `json:"transfer_id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	Normalized   []byte      `json:"normalized"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	CreatedAt    time.Time   `json:"created_at"`
}

func (q *Queries) UpdateWebhookLogProcessed(ctx context.Context, arg UpdateWebhookLogProcessedParams) error {
	_, err := q.db.Exec(ctx, updateWebhookLogProcessed,
		arg.ID,
		arg.TransferID,
		arg.TenantID,
		arg.Normalized,
		arg.Status,
		arg.ErrorMessage,
		arg.CreatedAt,
	)
	return err
}
