// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package transferdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountTransfersByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateProviderTransaction(ctx context.Context, arg CreateProviderTransactionParams) (ProviderTransaction, error)
	CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateTransferEvent(ctx context.Context, arg CreateTransferEventParams) (TransferEvent, error)
	DeactivateAPIKey(ctx context.Context, id uuid.UUID) error
	GetActiveQuote(ctx context.Context, arg GetActiveQuoteParams) (Quote, error)
	GetQuote(ctx context.Context, arg GetQuoteParams) (Quote, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetTransfer(ctx context.Context, arg GetTransferParams) (Transfer, error)
	GetTransferByExternalRef(ctx context.Context, arg GetTransferByExternalRefParams) (Transfer, error)
	GetTransferByID(ctx context.Context, id uuid.UUID) (Transfer, error)
	GetTransferByIdempotencyKey(ctx context.Context, arg GetTransferByIdempotencyKeyParams) (Transfer, error)
	ListAPIKeysByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListAPIKeysByTenantRow, error)
	ListProviderTransactions(ctx context.Context, arg ListProviderTransactionsParams) ([]ProviderTransaction, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	ListTransferEvents(ctx context.Context, arg ListTransferEventsParams) ([]TransferEvent, error)
	ListTransfersByStatus(ctx context.Context, arg ListTransfersByStatusParams) ([]Transfer, error)
	ListTransfersByTenant(ctx context.Context, arg ListTransfersByTenantParams) ([]Transfer, error)
	ListTransfersInDateRange(ctx context.Context, arg ListTransfersInDateRangeParams) ([]Transfer, error)
	SumDailyVolumeByTenant(ctx context.Context, arg SumDailyVolumeByTenantParams) (pgtype.Numeric, error)
	UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateProviderTransactionHash(ctx context.Context, arg UpdateProviderTransactionHashParams) error
	UpdateProviderTransactionStatus(ctx context.Context, arg UpdateProviderTransactionStatusParams) error
	UpdateTenantFeeSchedule(ctx context.Context, arg UpdateTenantFeeScheduleParams) error
	UpdateTenantKYB(ctx context.Context, arg UpdateTenantKYBParams) error
	UpdateTenantLimits(ctx context.Context, arg UpdateTenantLimitsParams) error
	UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) error
	UpdateTenantWebhook(ctx context.Context, arg UpdateTenantWebhookParams) error
	UpdateTransferDestAmount(ctx context.Context, arg UpdateTransferDestAmountParams) error
	UpdateTransferFailure(ctx context.Context, arg UpdateTransferFailureParams) error
	UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) error
	UpdateTransferStatusWithVersion(ctx context.Context, arg UpdateTransferStatusWithVersionParams) error
	ValidateAPIKey(ctx context.Context, keyHash string) (ValidateAPIKeyRow, error)
}

var _ Querier = (*Queries)(nil)
