// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reconciliation.sql

package transferdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAvailablePoolAddressesAll = `-- name: CountAvailablePoolAddressesAll :one
SELECT COUNT(*)::int AS count
FROM crypto_address_pool
WHERE dispensed = false
`

// Count undispensed addresses across all tenants and chains.
func (q *Queries) CountAvailablePoolAddressesAll(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countAvailablePoolAddressesAll)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countDefaultPartitionRows = `-- name: CountDefaultPartitionRows :one
SELECT COUNT(*)::int AS count
FROM outbox_default
`

// Count rows in the outbox_default partition (should always be zero).
func (q *Queries) CountDefaultPartitionRows(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countDefaultPartitionRows)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countDepositTxAmountMismatches = `-- name: CountDepositTxAmountMismatches :one
SELECT COUNT(*)::int AS count
FROM crypto_deposit_sessions s
WHERE s.status IN ('CONFIRMED', 'CREDITED', 'SETTLING', 'SETTLED', 'HELD')
  AND s.received_amount != COALESCE(
    (SELECT SUM(t.amount) FROM crypto_deposit_transactions t
     WHERE t.session_id = s.id AND t.confirmed = true),
    0
  )
`

// Count sessions where received_amount doesn't match sum of confirmed tx amounts.
func (q *Queries) CountDepositTxAmountMismatches(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countDepositTxAmountMismatches)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countOrphanedVirtualAccounts = `-- name: CountOrphanedVirtualAccounts :one
SELECT COUNT(*)::int AS count
FROM virtual_account_pool p
WHERE p.available = false
  AND EXISTS (
    SELECT 1 FROM bank_deposit_sessions s
    WHERE s.account_number = p.account_number
      AND s.status IN ('EXPIRED', 'FAILED', 'CANCELLED', 'SETTLED', 'HELD')
  )
`

// Count virtual accounts marked unavailable whose session reached terminal state.
func (q *Queries) CountOrphanedVirtualAccounts(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countOrphanedVirtualAccounts)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countPendingProviderTxOlderThan = `-- name: CountPendingProviderTxOlderThan :one
SELECT COUNT(*)::int AS count
FROM provider_transactions
WHERE status = 'pending'
  AND created_at < $1
`

// Count provider transactions stuck in pending status older than a threshold.
func (q *Queries) CountPendingProviderTxOlderThan(ctx context.Context, createdAt time.Time) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingProviderTxOlderThan, createdAt)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countStaleBlockCheckpoints = `-- name: CountStaleBlockCheckpoints :one
SELECT COUNT(*)::int AS count
FROM block_checkpoints
WHERE updated_at < $1
`

// Count chain monitors whose checkpoint has not been updated since threshold.
func (q *Queries) CountStaleBlockCheckpoints(ctx context.Context, updatedAt time.Time) (int32, error) {
	row := q.db.QueryRow(ctx, countStaleBlockCheckpoints, updatedAt)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countStuckBankDepositCrediting = `-- name: CountStuckBankDepositCrediting :one
SELECT COUNT(*)::int AS count
FROM bank_deposit_sessions
WHERE status = 'CREDITING'
  AND updated_at < $1
`

// Count bank deposit sessions in CREDITING status older than threshold.
func (q *Queries) CountStuckBankDepositCrediting(ctx context.Context, updatedAt time.Time) (int32, error) {
	row := q.db.QueryRow(ctx, countStuckBankDepositCrediting, updatedAt)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countStuckBankDepositSessions = `-- name: CountStuckBankDepositSessions :one
SELECT COUNT(*)::int AS count
FROM bank_deposit_sessions
WHERE status = 'PENDING_PAYMENT'
  AND updated_at < $1
`

// Count bank deposit sessions in PENDING_PAYMENT older than threshold.
func (q *Queries) CountStuckBankDepositSessions(ctx context.Context, updatedAt time.Time) (int32, error) {
	row := q.db.QueryRow(ctx, countStuckBankDepositSessions, updatedAt)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countStuckDepositSessions = `-- name: CountStuckDepositSessions :one
SELECT COUNT(*)::int AS count
FROM crypto_deposit_sessions
WHERE status NOT IN ('SETTLED', 'HELD', 'EXPIRED', 'FAILED', 'CANCELLED')
  AND updated_at < $1
`

// Count deposit sessions in non-terminal status older than a threshold.
func (q *Queries) CountStuckDepositSessions(ctx context.Context, updatedAt time.Time) (int32, error) {
	row := q.db.QueryRow(ctx, countStuckDepositSessions, updatedAt)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countTransfersInStatus = `-- name: CountTransfersInStatus :one

SELECT COUNT(*)::int AS count
FROM transfers
WHERE status = $1
  AND updated_at < $2
`

type CountTransfersInStatusParams struct {
	Status    TransferStatusEnum `json:"status"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// ============================================================================
// Reconciliation queries — used by the automated reconciliation system.
// These are admin-only system queries that scan across all tenants.
// ============================================================================
// Count transfers stuck in a given status older than a threshold.
func (q *Queries) CountTransfersInStatus(ctx context.Context, arg CountTransfersInStatusParams) (int32, error) {
	row := q.db.QueryRow(ctx, countTransfersInStatus, arg.Status, arg.UpdatedAt)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countUnpublishedOlderThan = `-- name: CountUnpublishedOlderThan :one
SELECT COUNT(*)::int AS count
FROM outbox
WHERE published = false
  AND created_at < $1
`

// Count unpublished outbox entries older than a threshold.
func (q *Queries) CountUnpublishedOlderThan(ctx context.Context, createdAt time.Time) (int32, error) {
	row := q.db.QueryRow(ctx, countUnpublishedOlderThan, createdAt)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getAverageDailyTransferCount = `-- name: GetAverageDailyTransferCount :one
SELECT COALESCE(
    CAST(COUNT(*) AS float) / GREATEST(
        EXTRACT(EPOCH FROM (CAST($1 AS timestamptz) - CAST($2 AS timestamptz))) / 86400,
        1
    ),
    0
)::float AS avg_count
FROM transfers
WHERE created_at >= $2
  AND created_at < $1
`

type GetAverageDailyTransferCountParams struct {
	EndDate   time.Time `json:"end_date"`
	StartDate time.Time `json:"start_date"`
}

// Average number of transfers per day over [start, end).
func (q *Queries) GetAverageDailyTransferCount(ctx context.Context, arg GetAverageDailyTransferCountParams) (float64, error) {
	row := q.db.QueryRow(ctx, getAverageDailyTransferCount, arg.EndDate, arg.StartDate)
	var avg_count float64
	err := row.Scan(&avg_count)
	return avg_count, err
}

const getDailyTransferCount = `-- name: GetDailyTransferCount :one
SELECT COUNT(*)::int AS count
FROM transfers
WHERE created_at >= $1
  AND created_at < $2
`

type GetDailyTransferCountParams struct {
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

// Count transfers created on a given UTC date [start, end).
func (q *Queries) GetDailyTransferCount(ctx context.Context, arg GetDailyTransferCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, getDailyTransferCount, arg.StartTime, arg.EndTime)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getLatestNetSettlement = `-- name: GetLatestNetSettlement :one
SELECT id, tenant_id, period_start, period_end, total_fees_usd
FROM net_settlements
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestNetSettlementRow struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	PeriodStart  time.Time      `json:"period_start"`
	PeriodEnd    time.Time      `json:"period_end"`
	TotalFeesUsd pgtype.Numeric `json:"total_fees_usd"`
}

// Get the most recently created net settlement across all tenants.
func (q *Queries) GetLatestNetSettlement(ctx context.Context) (GetLatestNetSettlementRow, error) {
	row := q.db.QueryRow(ctx, getLatestNetSettlement)
	var i GetLatestNetSettlementRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TotalFeesUsd,
	)
	return i, err
}

const getTenantSlug = `-- name: GetTenantSlug :one
SELECT slug FROM tenants WHERE id = $1
`

// Get the slug for a tenant by ID.
func (q *Queries) GetTenantSlug(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTenantSlug, id)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const hasActiveReview = `-- name: HasActiveReview :one
SELECT EXISTS (
    SELECT 1 FROM manual_reviews
    WHERE transfer_id = $1
      AND status IN ('pending', 'investigating')
) AS has_review
`

// Check if an open review exists for a given transfer.
func (q *Queries) HasActiveReview(ctx context.Context, transferID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveReview, transferID)
	var has_review bool
	err := row.Scan(&has_review)
	return has_review, err
}

const listOpsManualReviews = `-- name: ListOpsManualReviews :many
SELECT
    mr.id,
    mr.transfer_id,
    mr.tenant_id,
    COALESCE(t.name, '') AS tenant_name,
    mr.status,
    mr.transfer_status,
    mr.attempted_recoveries,
    COALESCE(tr.source_amount, 0) AS source_amount,
    COALESCE(tr.source_currency, '') AS source_currency,
    COALESCE(tr.dest_currency, '') AS dest_currency,
    COALESCE(tr.failure_code, '') AS failure_code,
    mr.created_at AS escalated_at,
    mr.resolved_at,
    COALESCE(mr.resolved_by, '') AS resolved_by,
    COALESCE(mr.resolution, '') AS resolution
FROM manual_reviews mr
LEFT JOIN tenants t ON t.id = mr.tenant_id
LEFT JOIN transfers tr ON tr.id = mr.transfer_id
WHERE ($1::uuid IS NULL OR mr.tenant_id = $1)
  AND ($2::text IS NULL OR mr.status = $2)
ORDER BY mr.created_at DESC
LIMIT 100
`

type ListOpsManualReviewsParams struct {
	FilterTenantID pgtype.UUID `json:"filter_tenant_id"`
	FilterStatus   pgtype.Text `json:"filter_status"`
}

type ListOpsManualReviewsRow struct {
	ID                  uuid.UUID          `json:"id"`
	TransferID          uuid.UUID          `json:"transfer_id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	TenantName          string             `json:"tenant_name"`
	Status              ReviewStatusEnum   `json:"status"`
	TransferStatus      string             `json:"transfer_status"`
	AttemptedRecoveries int32              `json:"attempted_recoveries"`
	SourceAmount        pgtype.Numeric     `json:"source_amount"`
	SourceCurrency      string             `json:"source_currency"`
	DestCurrency        string             `json:"dest_currency"`
	FailureCode         string             `json:"failure_code"`
	EscalatedAt         time.Time          `json:"escalated_at"`
	ResolvedAt          pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy          string             `json:"resolved_by"`
	Resolution          string             `json:"resolution"`
}

// List manual reviews for ops dashboard with tenant and transfer details.
// Use sqlc.narg for optional filters: pass NULL to skip filtering.
func (q *Queries) ListOpsManualReviews(ctx context.Context, arg ListOpsManualReviewsParams) ([]ListOpsManualReviewsRow, error) {
	rows, err := q.db.Query(ctx, listOpsManualReviews, arg.FilterTenantID, arg.FilterStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpsManualReviewsRow{}
	for rows.Next() {
		var i ListOpsManualReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.TenantID,
			&i.TenantName,
			&i.Status,
			&i.TransferStatus,
			&i.AttemptedRecoveries,
			&i.SourceAmount,
			&i.SourceCurrency,
			&i.DestCurrency,
			&i.FailureCode,
			&i.EscalatedAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.Resolution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpsNetSettlements = `-- name: ListOpsNetSettlements :many
SELECT
    ns.id,
    ns.tenant_id,
    COALESCE(t.name, '') AS tenant_name,
    ns.period_start,
    ns.period_end,
    ns.corridors,
    ns.net_by_currency,
    ns.total_fees_usd,
    ns.instructions,
    ns.status,
    ns.due_date,
    ns.settled_at
FROM net_settlements ns
LEFT JOIN tenants t ON t.id = ns.tenant_id
WHERE ($1::uuid IS NULL OR ns.tenant_id = $1)
ORDER BY ns.created_at DESC
LIMIT 50
`

type ListOpsNetSettlementsRow struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	TenantName    string             `json:"tenant_name"`
	PeriodStart   time.Time          `json:"period_start"`
	PeriodEnd     time.Time          `json:"period_end"`
	Corridors     []byte             `json:"corridors"`
	NetByCurrency []byte             `json:"net_by_currency"`
	TotalFeesUsd  pgtype.Numeric     `json:"total_fees_usd"`
	Instructions  []byte             `json:"instructions"`
	Status        string             `json:"status"`
	DueDate       pgtype.Date        `json:"due_date"`
	SettledAt     pgtype.Timestamptz `json:"settled_at"`
}

// List net settlements for ops dashboard with tenant names.
// Use sqlc.narg for optional tenant filter: pass NULL for all tenants.
func (q *Queries) ListOpsNetSettlements(ctx context.Context, filterTenantID pgtype.UUID) ([]ListOpsNetSettlementsRow, error) {
	rows, err := q.db.Query(ctx, listOpsNetSettlements, filterTenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpsNetSettlementsRow{}
	for rows.Next() {
		var i ListOpsNetSettlementsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TenantName,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Corridors,
			&i.NetByCurrency,
			&i.TotalFeesUsd,
			&i.Instructions,
			&i.Status,
			&i.DueDate,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSettlementPaid = `-- name: MarkSettlementPaid :exec
UPDATE net_settlements
SET status = 'paid',
    settled_at = now(),
    instructions = jsonb_set(
        COALESCE(instructions, '[]'::jsonb),
        '{payment_ref}',
        to_jsonb($1::text)
    )
WHERE id = $2
`

type MarkSettlementPaidParams struct {
	PaymentRef string    `json:"payment_ref"`
	ID         uuid.UUID `json:"id"`
}

// Mark a net settlement as paid with a payment reference.
func (q *Queries) MarkSettlementPaid(ctx context.Context, arg MarkSettlementPaidParams) error {
	_, err := q.db.Exec(ctx, markSettlementPaid, arg.PaymentRef, arg.ID)
	return err
}

const resolveManualReview = `-- name: ResolveManualReview :exec
UPDATE manual_reviews
SET status = $2, resolution = $3, resolved_by = $4, resolved_at = now()
WHERE id = $1
`

type ResolveManualReviewParams struct {
	ID         uuid.UUID        `json:"id"`
	Status     ReviewStatusEnum `json:"status"`
	Resolution pgtype.Text      `json:"resolution"`
	ResolvedBy pgtype.Text      `json:"resolved_by"`
}

// Resolve a manual review by updating its status and recording the resolution.
func (q *Queries) ResolveManualReview(ctx context.Context, arg ResolveManualReviewParams) error {
	_, err := q.db.Exec(ctx, resolveManualReview,
		arg.ID,
		arg.Status,
		arg.Resolution,
		arg.ResolvedBy,
	)
	return err
}

const sumCompletedTransferFeesUSD = `-- name: SumCompletedTransferFeesUSD :one
SELECT COALESCE(SUM((fees->>'TotalFeeUSD')::numeric), 0)::NUMERIC(28,8) AS total_fees
FROM transfers
WHERE tenant_id = $1
  AND status = 'COMPLETED'
  AND completed_at >= $2
  AND completed_at < $3
`

type SumCompletedTransferFeesUSDParams struct {
	TenantID  uuid.UUID          `json:"tenant_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

// Sum fees from completed transfers for a tenant in [start, end).
func (q *Queries) SumCompletedTransferFeesUSD(ctx context.Context, arg SumCompletedTransferFeesUSDParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumCompletedTransferFeesUSD, arg.TenantID, arg.StartTime, arg.EndTime)
	var total_fees pgtype.Numeric
	err := row.Scan(&total_fees)
	return total_fees, err
}

const updateTenantMetadata = `-- name: UpdateTenantMetadata :exec
UPDATE tenants
SET metadata = $2, updated_at = now()
WHERE id = $1
`

type UpdateTenantMetadataParams struct {
	ID       uuid.UUID `json:"id"`
	Metadata []byte    `json:"metadata"`
}

// Update the metadata JSONB field for a tenant.
func (q *Queries) UpdateTenantMetadata(ctx context.Context, arg UpdateTenantMetadataParams) error {
	_, err := q.db.Exec(ctx, updateTenantMetadata, arg.ID, arg.Metadata)
	return err
}
