// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package transferdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
    tenant_id, key_hash, key_prefix, environment, name, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_id, key_hash, key_prefix, environment, name, is_active, last_used_at, expires_at, created_at
`

type CreateAPIKeyParams struct {
	TenantID    uuid.UUID          `json:"tenant_id"`
	KeyHash     string             `json:"key_hash"`
	KeyPrefix   string             `json:"key_prefix"`
	Environment string             `json:"environment"`
	Name        pgtype.Text        `json:"name"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.TenantID,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Environment,
		arg.Name,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Environment,
		&i.Name,
		&i.IsActive,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    name, slug, status, fee_schedule, settlement_model,
    webhook_url, webhook_secret, daily_limit_usd, per_transfer_limit,
    kyb_status, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, name, slug, status, fee_schedule, settlement_model, webhook_url, webhook_secret, daily_limit_usd, per_transfer_limit, kyb_status, kyb_verified_at, metadata, created_at, updated_at, webhook_events, crypto_enabled, default_settlement_pref, supported_chains, min_confirmations_tron, min_confirmations_eth, min_confirmations_base, payment_tolerance_bps, default_session_ttl_secs, bank_deposits_enabled, default_banking_partner, bank_supported_currencies, default_mismatch_policy, bank_default_session_ttl_secs, fee_schedule_version
`

type CreateTenantParams struct {
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Status           string         `json:"status"`
	FeeSchedule      []byte         `json:"fee_schedule"`
	SettlementModel  string         `json:"settlement_model"`
	WebhookUrl       pgtype.Text    `json:"webhook_url"`
	WebhookSecret    pgtype.Text    `json:"webhook_secret"`
	DailyLimitUsd    pgtype.Numeric `json:"daily_limit_usd"`
	PerTransferLimit pgtype.Numeric `json:"per_transfer_limit"`
	KybStatus        string         `json:"kyb_status"`
	Metadata         []byte         `json:"metadata"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.Status,
		arg.FeeSchedule,
		arg.SettlementModel,
		arg.WebhookUrl,
		arg.WebhookSecret,
		arg.DailyLimitUsd,
		arg.PerTransferLimit,
		arg.KybStatus,
		arg.Metadata,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.FeeSchedule,
		&i.SettlementModel,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.DailyLimitUsd,
		&i.PerTransferLimit,
		&i.KybStatus,
		&i.KybVerifiedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookEvents,
		&i.CryptoEnabled,
		&i.DefaultSettlementPref,
		&i.SupportedChains,
		&i.MinConfirmationsTron,
		&i.MinConfirmationsEth,
		&i.MinConfirmationsBase,
		&i.PaymentToleranceBps,
		&i.DefaultSessionTtlSecs,
		&i.BankDepositsEnabled,
		&i.DefaultBankingPartner,
		&i.BankSupportedCurrencies,
		&i.DefaultMismatchPolicy,
		&i.BankDefaultSessionTtlSecs,
		&i.FeeScheduleVersion,
	)
	return i, err
}

const deactivateAPIKey = `-- name: DeactivateAPIKey :exec
UPDATE api_keys SET is_active = false WHERE id = $1
`

func (q *Queries) DeactivateAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateAPIKey, id)
	return err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, slug, status, fee_schedule, settlement_model, webhook_url, webhook_secret, daily_limit_usd, per_transfer_limit, kyb_status, kyb_verified_at, metadata, created_at, updated_at, webhook_events, crypto_enabled, default_settlement_pref, supported_chains, min_confirmations_tron, min_confirmations_eth, min_confirmations_base, payment_tolerance_bps, default_session_ttl_secs, bank_deposits_enabled, default_banking_partner, bank_supported_currencies, default_mismatch_policy, bank_default_session_ttl_secs, fee_schedule_version FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.FeeSchedule,
		&i.SettlementModel,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.DailyLimitUsd,
		&i.PerTransferLimit,
		&i.KybStatus,
		&i.KybVerifiedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookEvents,
		&i.CryptoEnabled,
		&i.DefaultSettlementPref,
		&i.SupportedChains,
		&i.MinConfirmationsTron,
		&i.MinConfirmationsEth,
		&i.MinConfirmationsBase,
		&i.PaymentToleranceBps,
		&i.DefaultSessionTtlSecs,
		&i.BankDepositsEnabled,
		&i.DefaultBankingPartner,
		&i.BankSupportedCurrencies,
		&i.DefaultMismatchPolicy,
		&i.BankDefaultSessionTtlSecs,
		&i.FeeScheduleVersion,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, status, fee_schedule, settlement_model, webhook_url, webhook_secret, daily_limit_usd, per_transfer_limit, kyb_status, kyb_verified_at, metadata, created_at, updated_at, webhook_events, crypto_enabled, default_settlement_pref, supported_chains, min_confirmations_tron, min_confirmations_eth, min_confirmations_base, payment_tolerance_bps, default_session_ttl_secs, bank_deposits_enabled, default_banking_partner, bank_supported_currencies, default_mismatch_policy, bank_default_session_ttl_secs, fee_schedule_version FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.FeeSchedule,
		&i.SettlementModel,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.DailyLimitUsd,
		&i.PerTransferLimit,
		&i.KybStatus,
		&i.KybVerifiedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookEvents,
		&i.CryptoEnabled,
		&i.DefaultSettlementPref,
		&i.SupportedChains,
		&i.MinConfirmationsTron,
		&i.MinConfirmationsEth,
		&i.MinConfirmationsBase,
		&i.PaymentToleranceBps,
		&i.DefaultSessionTtlSecs,
		&i.BankDepositsEnabled,
		&i.DefaultBankingPartner,
		&i.BankSupportedCurrencies,
		&i.DefaultMismatchPolicy,
		&i.BankDefaultSessionTtlSecs,
		&i.FeeScheduleVersion,
	)
	return i, err
}

const listAPIKeysByTenant = `-- name: ListAPIKeysByTenant :many
SELECT id, tenant_id, key_prefix, environment, name, is_active, last_used_at, expires_at, created_at
FROM api_keys
WHERE tenant_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysByTenantRow struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	KeyPrefix   string             `json:"key_prefix"`
	Environment string             `json:"environment"`
	Name        pgtype.Text        `json:"name"`
	IsActive    bool               `json:"is_active"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

func (q *Queries) ListAPIKeysByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListAPIKeysByTenantRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysByTenantRow{}
	for rows.Next() {
		var i ListAPIKeysByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.KeyPrefix,
			&i.Environment,
			&i.Name,
			&i.IsActive,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, status, fee_schedule, settlement_model, webhook_url, webhook_secret, daily_limit_usd, per_transfer_limit, kyb_status, kyb_verified_at, metadata, created_at, updated_at, webhook_events, crypto_enabled, default_settlement_pref, supported_chains, min_confirmations_tron, min_confirmations_eth, min_confirmations_base, payment_tolerance_bps, default_session_ttl_secs, bank_deposits_enabled, default_banking_partner, bank_supported_currencies, default_mismatch_policy, bank_default_session_ttl_secs, fee_schedule_version FROM tenants
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTenantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.FeeSchedule,
			&i.SettlementModel,
			&i.WebhookUrl,
			&i.WebhookSecret,
			&i.DailyLimitUsd,
			&i.PerTransferLimit,
			&i.KybStatus,
			&i.KybVerifiedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WebhookEvents,
			&i.CryptoEnabled,
			&i.DefaultSettlementPref,
			&i.SupportedChains,
			&i.MinConfirmationsTron,
			&i.MinConfirmationsEth,
			&i.MinConfirmationsBase,
			&i.PaymentToleranceBps,
			&i.DefaultSessionTtlSecs,
			&i.BankDepositsEnabled,
			&i.DefaultBankingPartner,
			&i.BankSupportedCurrencies,
			&i.DefaultMismatchPolicy,
			&i.BankDefaultSessionTtlSecs,
			&i.FeeScheduleVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}

const updateTenantFeeSchedule = `-- name: UpdateTenantFeeSchedule :exec
UPDATE tenants
SET fee_schedule = $2, updated_at = now()
WHERE id = $1
`

type UpdateTenantFeeScheduleParams struct {
	ID          uuid.UUID `json:"id"`
	FeeSchedule []byte    `json:"fee_schedule"`
}

func (q *Queries) UpdateTenantFeeSchedule(ctx context.Context, arg UpdateTenantFeeScheduleParams) error {
	_, err := q.db.Exec(ctx, updateTenantFeeSchedule, arg.ID, arg.FeeSchedule)
	return err
}

const updateTenantKYB = `-- name: UpdateTenantKYB :exec
UPDATE tenants
SET kyb_status = $2,
    kyb_verified_at = CASE WHEN $2 = 'VERIFIED' THEN now() ELSE kyb_verified_at END,
    updated_at = now()
WHERE id = $1
`

type UpdateTenantKYBParams struct {
	ID        uuid.UUID `json:"id"`
	KybStatus string    `json:"kyb_status"`
}

func (q *Queries) UpdateTenantKYB(ctx context.Context, arg UpdateTenantKYBParams) error {
	_, err := q.db.Exec(ctx, updateTenantKYB, arg.ID, arg.KybStatus)
	return err
}

const updateTenantLimits = `-- name: UpdateTenantLimits :exec
UPDATE tenants
SET daily_limit_usd = $2, per_transfer_limit = $3, updated_at = now()
WHERE id = $1
`

type UpdateTenantLimitsParams struct {
	ID               uuid.UUID      `json:"id"`
	DailyLimitUsd    pgtype.Numeric `json:"daily_limit_usd"`
	PerTransferLimit pgtype.Numeric `json:"per_transfer_limit"`
}

func (q *Queries) UpdateTenantLimits(ctx context.Context, arg UpdateTenantLimitsParams) error {
	_, err := q.db.Exec(ctx, updateTenantLimits, arg.ID, arg.DailyLimitUsd, arg.PerTransferLimit)
	return err
}

const updateTenantStatus = `-- name: UpdateTenantStatus :exec
UPDATE tenants
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateTenantStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) error {
	_, err := q.db.Exec(ctx, updateTenantStatus, arg.ID, arg.Status)
	return err
}

const updateTenantWebhook = `-- name: UpdateTenantWebhook :exec
UPDATE tenants
SET webhook_url = $2, webhook_secret = $3, updated_at = now()
WHERE id = $1
`

type UpdateTenantWebhookParams struct {
	ID            uuid.UUID   `json:"id"`
	WebhookUrl    pgtype.Text `json:"webhook_url"`
	WebhookSecret pgtype.Text `json:"webhook_secret"`
}

func (q *Queries) UpdateTenantWebhook(ctx context.Context, arg UpdateTenantWebhookParams) error {
	_, err := q.db.Exec(ctx, updateTenantWebhook, arg.ID, arg.WebhookUrl, arg.WebhookSecret)
	return err
}

const validateAPIKey = `-- name: ValidateAPIKey :one
SELECT ak.id, ak.tenant_id, ak.environment, ak.is_active, ak.expires_at,
       t.id AS tenant_uuid, t.slug, t.status AS tenant_status,
       t.fee_schedule, t.settlement_model,
       t.daily_limit_usd, t.per_transfer_limit,
       t.webhook_url, t.webhook_secret
FROM api_keys ak
JOIN tenants t ON t.id = ak.tenant_id
WHERE ak.key_hash = $1
  AND ak.is_active = true
  AND (ak.expires_at IS NULL OR ak.expires_at > now())
`

type ValidateAPIKeyRow struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	Environment      string             `json:"environment"`
	IsActive         bool               `json:"is_active"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	TenantUuid       uuid.UUID          `json:"tenant_uuid"`
	Slug             string             `json:"slug"`
	TenantStatus     string             `json:"tenant_status"`
	FeeSchedule      []byte             `json:"fee_schedule"`
	SettlementModel  string             `json:"settlement_model"`
	DailyLimitUsd    pgtype.Numeric     `json:"daily_limit_usd"`
	PerTransferLimit pgtype.Numeric     `json:"per_transfer_limit"`
	WebhookUrl       pgtype.Text        `json:"webhook_url"`
	WebhookSecret    pgtype.Text        `json:"webhook_secret"`
}

func (q *Queries) ValidateAPIKey(ctx context.Context, keyHash string) (ValidateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, validateAPIKey, keyHash)
	var i ValidateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Environment,
		&i.IsActive,
		&i.ExpiresAt,
		&i.TenantUuid,
		&i.Slug,
		&i.TenantStatus,
		&i.FeeSchedule,
		&i.SettlementModel,
		&i.DailyLimitUsd,
		&i.PerTransferLimit,
		&i.WebhookUrl,
		&i.WebhookSecret,
	)
	return i, err
}
