// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_portal.sql

package transferdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateAPIKeyByTenant = `-- name: DeactivateAPIKeyByTenant :exec
UPDATE api_keys SET is_active = false
WHERE id = $1 AND tenant_id = $2
`

type DeactivateAPIKeyByTenantParams struct {
	KeyID    uuid.UUID `json:"key_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Deactivate an API key, ensuring it belongs to the tenant.
func (q *Queries) DeactivateAPIKeyByTenant(ctx context.Context, arg DeactivateAPIKeyByTenantParams) error {
	_, err := q.db.Exec(ctx, deactivateAPIKeyByTenant, arg.KeyID, arg.TenantID)
	return err
}

const getAPIKeyByIDAndTenant = `-- name: GetAPIKeyByIDAndTenant :one
SELECT id, tenant_id, key_prefix, environment, name, is_active, last_used_at, expires_at, created_at
FROM api_keys
WHERE id = $1 AND tenant_id = $2
`

type GetAPIKeyByIDAndTenantParams struct {
	KeyID    uuid.UUID `json:"key_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetAPIKeyByIDAndTenantRow struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	KeyPrefix   string             `json:"key_prefix"`
	Environment string             `json:"environment"`
	Name        pgtype.Text        `json:"name"`
	IsActive    bool               `json:"is_active"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

// Get a specific API key ensuring tenant ownership.
func (q *Queries) GetAPIKeyByIDAndTenant(ctx context.Context, arg GetAPIKeyByIDAndTenantParams) (GetAPIKeyByIDAndTenantRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByIDAndTenant, arg.KeyID, arg.TenantID)
	var i GetAPIKeyByIDAndTenantRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.KeyPrefix,
		&i.Environment,
		&i.Name,
		&i.IsActive,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFeeReportByCorridor = `-- name: GetFeeReportByCorridor :many
SELECT
    source_currency,
    dest_currency,
    COUNT(*) AS transfer_count,
    COALESCE(SUM(source_amount), 0)::NUMERIC(28,8) AS total_volume_usd,
    COALESCE(SUM((fees->>'on_ramp_fee')::NUMERIC(28,8)), 0)::NUMERIC(28,8) AS on_ramp_fees_usd,
    COALESCE(SUM((fees->>'off_ramp_fee')::NUMERIC(28,8)), 0)::NUMERIC(28,8) AS off_ramp_fees_usd,
    COALESCE(SUM((fees->>'network_fee')::NUMERIC(28,8)), 0)::NUMERIC(28,8) AS network_fees_usd,
    COALESCE(SUM((fees->>'total_fee_usd')::NUMERIC(28,8)), 0)::NUMERIC(28,8) AS total_fees_usd
FROM transfers
WHERE tenant_id = $1
  AND created_at >= $2::timestamptz
  AND created_at < $3::timestamptz
  AND status NOT IN ('FAILED', 'REFUNDED')
GROUP BY source_currency, dest_currency
ORDER BY total_fees_usd DESC
`

type GetFeeReportByCorridorParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	FromTime time.Time `json:"from_time"`
	ToTime   time.Time `json:"to_time"`
}

type GetFeeReportByCorridorRow struct {
	SourceCurrency string         `json:"source_currency"`
	DestCurrency   string         `json:"dest_currency"`
	TransferCount  int64          `json:"transfer_count"`
	TotalVolumeUsd pgtype.Numeric `json:"total_volume_usd"`
	OnRampFeesUsd  pgtype.Numeric `json:"on_ramp_fees_usd"`
	OffRampFeesUsd pgtype.Numeric `json:"off_ramp_fees_usd"`
	NetworkFeesUsd pgtype.Numeric `json:"network_fees_usd"`
	TotalFeesUsd   pgtype.Numeric `json:"total_fees_usd"`
}

// Fee breakdown grouped by currency corridor for a given period.
func (q *Queries) GetFeeReportByCorridor(ctx context.Context, arg GetFeeReportByCorridorParams) ([]GetFeeReportByCorridorRow, error) {
	rows, err := q.db.Query(ctx, getFeeReportByCorridor, arg.TenantID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFeeReportByCorridorRow{}
	for rows.Next() {
		var i GetFeeReportByCorridorRow
		if err := rows.Scan(
			&i.SourceCurrency,
			&i.DestCurrency,
			&i.TransferCount,
			&i.TotalVolumeUsd,
			&i.OnRampFeesUsd,
			&i.OffRampFeesUsd,
			&i.NetworkFeesUsd,
			&i.TotalFeesUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantDashboardMetrics = `-- name: GetTenantDashboardMetrics :one

SELECT
    -- Today
    COUNT(*) FILTER (WHERE created_at >= $1::timestamptz) AS transfers_today,
    COALESCE(SUM(source_amount) FILTER (WHERE created_at >= $1::timestamptz AND status NOT IN ('FAILED','REFUNDED')), 0)::NUMERIC(28,8) AS volume_today_usd,
    COUNT(*) FILTER (WHERE created_at >= $1::timestamptz AND status = 'COMPLETED') AS completed_today,
    COUNT(*) FILTER (WHERE created_at >= $1::timestamptz AND status = 'FAILED') AS failed_today,
    -- 7 days
    COUNT(*) FILTER (WHERE created_at >= $2::timestamptz) AS transfers_7d,
    COALESCE(SUM(source_amount) FILTER (WHERE created_at >= $2::timestamptz AND status NOT IN ('FAILED','REFUNDED')), 0)::NUMERIC(28,8) AS volume_7d_usd,
    COALESCE(SUM((fees->>'total_fee_usd')::NUMERIC(28,8)) FILTER (WHERE created_at >= $2::timestamptz AND status NOT IN ('FAILED','REFUNDED')), 0)::NUMERIC(28,8) AS fees_7d_usd,
    -- 30 days
    COUNT(*) FILTER (WHERE created_at >= $3::timestamptz) AS transfers_30d,
    COALESCE(SUM(source_amount) FILTER (WHERE created_at >= $3::timestamptz AND status NOT IN ('FAILED','REFUNDED')), 0)::NUMERIC(28,8) AS volume_30d_usd,
    COALESCE(SUM((fees->>'total_fee_usd')::NUMERIC(28,8)) FILTER (WHERE created_at >= $3::timestamptz AND status NOT IN ('FAILED','REFUNDED')), 0)::NUMERIC(28,8) AS fees_30d_usd,
    -- Success rate (30d)
    CASE
        WHEN COUNT(*) FILTER (WHERE created_at >= $3::timestamptz AND status IN ('COMPLETED','FAILED')) = 0 THEN 0
        ELSE ROUND(
            100.0 * COUNT(*) FILTER (WHERE created_at >= $3::timestamptz AND status = 'COMPLETED')
            / COUNT(*) FILTER (WHERE created_at >= $3::timestamptz AND status IN ('COMPLETED','FAILED')),
            2
        )
    END::NUMERIC(5,2) AS success_rate_30d
FROM transfers
WHERE tenant_id = $4
  AND created_at >= $3::timestamptz
`

type GetTenantDashboardMetricsParams struct {
	TodayStart    time.Time `json:"today_start"`
	SevenDaysAgo  time.Time `json:"seven_days_ago"`
	ThirtyDaysAgo time.Time `json:"thirty_days_ago"`
	TenantID      uuid.UUID `json:"tenant_id"`
}

type GetTenantDashboardMetricsRow struct {
	TransfersToday int64          `json:"transfers_today"`
	VolumeTodayUsd pgtype.Numeric `json:"volume_today_usd"`
	CompletedToday int64          `json:"completed_today"`
	FailedToday    int64          `json:"failed_today"`
	Transfers7d    int64          `json:"transfers_7d"`
	Volume7dUsd    pgtype.Numeric `json:"volume_7d_usd"`
	Fees7dUsd      pgtype.Numeric `json:"fees_7d_usd"`
	Transfers30d   int64          `json:"transfers_30d"`
	Volume30dUsd   pgtype.Numeric `json:"volume_30d_usd"`
	Fees30dUsd     pgtype.Numeric `json:"fees_30d_usd"`
	SuccessRate30d pgtype.Numeric `json:"success_rate_30d"`
}

// ============================================================================
// Tenant portal queries — self-service dashboard metrics and analytics.
// All queries are tenant-scoped (tenant_id filter) per the tenant isolation invariant.
// ============================================================================
// Aggregated metrics for the last N days. Runs one scan for multiple aggregation windows.
func (q *Queries) GetTenantDashboardMetrics(ctx context.Context, arg GetTenantDashboardMetricsParams) (GetTenantDashboardMetricsRow, error) {
	row := q.db.QueryRow(ctx, getTenantDashboardMetrics,
		arg.TodayStart,
		arg.SevenDaysAgo,
		arg.ThirtyDaysAgo,
		arg.TenantID,
	)
	var i GetTenantDashboardMetricsRow
	err := row.Scan(
		&i.TransfersToday,
		&i.VolumeTodayUsd,
		&i.CompletedToday,
		&i.FailedToday,
		&i.Transfers7d,
		&i.Volume7dUsd,
		&i.Fees7dUsd,
		&i.Transfers30d,
		&i.Volume30dUsd,
		&i.Fees30dUsd,
		&i.SuccessRate30d,
	)
	return i, err
}

const getTransferStatsDaily = `-- name: GetTransferStatsDaily :many
SELECT
    date_trunc('day', created_at)::timestamptz AS bucket,
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE status = 'COMPLETED') AS completed,
    COUNT(*) FILTER (WHERE status = 'FAILED') AS failed,
    COALESCE(SUM(source_amount) FILTER (WHERE status NOT IN ('FAILED','REFUNDED')), 0)::NUMERIC(28,8) AS volume_usd,
    COALESCE(SUM((fees->>'total_fee_usd')::NUMERIC(28,8)) FILTER (WHERE status NOT IN ('FAILED','REFUNDED')), 0)::NUMERIC(28,8) AS fees_usd
FROM transfers
WHERE tenant_id = $1
  AND created_at >= $2::timestamptz
  AND created_at < $3::timestamptz
GROUP BY bucket
ORDER BY bucket
`

type GetTransferStatsDailyParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	FromTime time.Time `json:"from_time"`
	ToTime   time.Time `json:"to_time"`
}

type GetTransferStatsDailyRow struct {
	Bucket    time.Time      `json:"bucket"`
	Total     int64          `json:"total"`
	Completed int64          `json:"completed"`
	Failed    int64          `json:"failed"`
	VolumeUsd pgtype.Numeric `json:"volume_usd"`
	FeesUsd   pgtype.Numeric `json:"fees_usd"`
}

// Daily bucketed transfer stats for a given date range (for charts).
func (q *Queries) GetTransferStatsDaily(ctx context.Context, arg GetTransferStatsDailyParams) ([]GetTransferStatsDailyRow, error) {
	rows, err := q.db.Query(ctx, getTransferStatsDaily, arg.TenantID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransferStatsDailyRow{}
	for rows.Next() {
		var i GetTransferStatsDailyRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Total,
			&i.Completed,
			&i.Failed,
			&i.VolumeUsd,
			&i.FeesUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransferStatsHourly = `-- name: GetTransferStatsHourly :many
SELECT
    date_trunc('hour', created_at)::timestamptz AS bucket,
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE status = 'COMPLETED') AS completed,
    COUNT(*) FILTER (WHERE status = 'FAILED') AS failed,
    COALESCE(SUM(source_amount) FILTER (WHERE status NOT IN ('FAILED','REFUNDED')), 0)::NUMERIC(28,8) AS volume_usd,
    COALESCE(SUM((fees->>'total_fee_usd')::NUMERIC(28,8)) FILTER (WHERE status NOT IN ('FAILED','REFUNDED')), 0)::NUMERIC(28,8) AS fees_usd
FROM transfers
WHERE tenant_id = $1
  AND created_at >= $2::timestamptz
  AND created_at < $3::timestamptz
GROUP BY bucket
ORDER BY bucket
`

type GetTransferStatsHourlyParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	FromTime time.Time `json:"from_time"`
	ToTime   time.Time `json:"to_time"`
}

type GetTransferStatsHourlyRow struct {
	Bucket    time.Time      `json:"bucket"`
	Total     int64          `json:"total"`
	Completed int64          `json:"completed"`
	Failed    int64          `json:"failed"`
	VolumeUsd pgtype.Numeric `json:"volume_usd"`
	FeesUsd   pgtype.Numeric `json:"fees_usd"`
}

// Hourly bucketed transfer stats for a given date range (for charts).
func (q *Queries) GetTransferStatsHourly(ctx context.Context, arg GetTransferStatsHourlyParams) ([]GetTransferStatsHourlyRow, error) {
	rows, err := q.db.Query(ctx, getTransferStatsHourly, arg.TenantID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransferStatsHourlyRow{}
	for rows.Next() {
		var i GetTransferStatsHourlyRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Total,
			&i.Completed,
			&i.Failed,
			&i.VolumeUsd,
			&i.FeesUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
