// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package transferdb

import (
	"context"
)

const getToken = `-- name: GetToken :one
SELECT id, chain, symbol, contract_address, decimals, is_active, created_at, updated_at FROM tokens WHERE chain = $1 AND symbol = $2
`

type GetTokenParams struct {
	Chain  string `json:"chain"`
	Symbol string `json:"symbol"`
}

func (q *Queries) GetToken(ctx context.Context, arg GetTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, getToken, arg.Chain, arg.Symbol)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Chain,
		&i.Symbol,
		&i.ContractAddress,
		&i.Decimals,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTokenByContract = `-- name: GetTokenByContract :one
SELECT id, chain, symbol, contract_address, decimals, is_active, created_at, updated_at FROM tokens WHERE chain = $1 AND contract_address = $2
`

type GetTokenByContractParams struct {
	Chain           string `json:"chain"`
	ContractAddress string `json:"contract_address"`
}

func (q *Queries) GetTokenByContract(ctx context.Context, arg GetTokenByContractParams) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByContract, arg.Chain, arg.ContractAddress)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Chain,
		&i.Symbol,
		&i.ContractAddress,
		&i.Decimals,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllActiveTokens = `-- name: ListAllActiveTokens :many
SELECT id, chain, symbol, contract_address, decimals, is_active, created_at, updated_at FROM tokens WHERE is_active = true ORDER BY chain, symbol
`

func (q *Queries) ListAllActiveTokens(ctx context.Context) ([]Token, error) {
	rows, err := q.db.Query(ctx, listAllActiveTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.Chain,
			&i.Symbol,
			&i.ContractAddress,
			&i.Decimals,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensByChain = `-- name: ListTokensByChain :many
SELECT id, chain, symbol, contract_address, decimals, is_active, created_at, updated_at FROM tokens WHERE chain = $1 AND is_active = true ORDER BY symbol
`

func (q *Queries) ListTokensByChain(ctx context.Context, chain string) ([]Token, error) {
	rows, err := q.db.Query(ctx, listTokensByChain, chain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.Chain,
			&i.Symbol,
			&i.ContractAddress,
			&i.Decimals,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertToken = `-- name: UpsertToken :one
INSERT INTO tokens (chain, symbol, contract_address, decimals, is_active)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (chain, symbol)
DO UPDATE SET contract_address = $3, decimals = $4, is_active = $5, updated_at = now()
RETURNING id, chain, symbol, contract_address, decimals, is_active, created_at, updated_at
`

type UpsertTokenParams struct {
	Chain           string `json:"chain"`
	Symbol          string `json:"symbol"`
	ContractAddress string `json:"contract_address"`
	Decimals        int32  `json:"decimals"`
	IsActive        bool   `json:"is_active"`
}

func (q *Queries) UpsertToken(ctx context.Context, arg UpsertTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, upsertToken,
		arg.Chain,
		arg.Symbol,
		arg.ContractAddress,
		arg.Decimals,
		arg.IsActive,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Chain,
		&i.Symbol,
		&i.ContractAddress,
		&i.Decimals,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
