// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfers.sql

package transferdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimProviderTransaction = `-- name: ClaimProviderTransaction :one
INSERT INTO provider_transactions (
    tenant_id, provider, tx_type,
    transfer_id, status, amount, currency, metadata
) VALUES (
    $1, $2, $3,
    $4, 'claiming', 0, '', '{}'
)
ON CONFLICT (tenant_id, transfer_id, tx_type) DO NOTHING
RETURNING id
`

type ClaimProviderTransactionParams struct {
	TenantID   uuid.UUID          `json:"tenant_id"`
	Provider   string             `json:"provider"`
	TxType     ProviderTxTypeEnum `json:"tx_type"`
	TransferID uuid.UUID          `json:"transfer_id"`
}

// Atomically claims a provider transaction slot using INSERT ON CONFLICT DO NOTHING.
// Returns the row id if the claim succeeded, or no row if already claimed.
// NOTE: executed as raw SQL in the adapter because SQLC cannot handle
// INSERT ON CONFLICT DO NOTHING RETURNING :one (returns no rows on conflict).
func (q *Queries) ClaimProviderTransaction(ctx context.Context, arg ClaimProviderTransactionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimProviderTransaction,
		arg.TenantID,
		arg.Provider,
		arg.TxType,
		arg.TransferID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const countPendingTransfers = `-- name: CountPendingTransfers :one
SELECT COUNT(*)::int FROM transfers
WHERE tenant_id = $1 AND status NOT IN ('COMPLETED', 'FAILED', 'REFUNDED')
`

// Counts non-terminal transfers for a tenant (used for per-tenant resource limits).
func (q *Queries) CountPendingTransfers(ctx context.Context, tenantID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingTransfers, tenantID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countTransfersByTenant = `-- name: CountTransfersByTenant :one
SELECT count(*) FROM transfers
WHERE tenant_id = $1
`

func (q *Queries) CountTransfersByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransfersByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProviderTransaction = `-- name: CreateProviderTransaction :one
INSERT INTO provider_transactions (
    tenant_id, provider, tx_type, external_id,
    transfer_id, status, amount, currency,
    chain, tx_hash, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, tenant_id, provider, tx_type, external_id, transfer_id, status, amount, currency, chain, tx_hash, metadata, created_at, updated_at
`

type CreateProviderTransactionParams struct {
	TenantID   uuid.UUID          `json:"tenant_id"`
	Provider   string             `json:"provider"`
	TxType     ProviderTxTypeEnum `json:"tx_type"`
	ExternalID pgtype.Text        `json:"external_id"`
	TransferID uuid.UUID          `json:"transfer_id"`
	Status     string             `json:"status"`
	Amount     pgtype.Numeric     `json:"amount"`
	Currency   string             `json:"currency"`
	Chain      pgtype.Text        `json:"chain"`
	TxHash     pgtype.Text        `json:"tx_hash"`
	Metadata   []byte             `json:"metadata"`
}

func (q *Queries) CreateProviderTransaction(ctx context.Context, arg CreateProviderTransactionParams) (ProviderTransaction, error) {
	row := q.db.QueryRow(ctx, createProviderTransaction,
		arg.TenantID,
		arg.Provider,
		arg.TxType,
		arg.ExternalID,
		arg.TransferID,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.Chain,
		arg.TxHash,
		arg.Metadata,
	)
	var i ProviderTransaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.TxType,
		&i.ExternalID,
		&i.TransferID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Chain,
		&i.TxHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuote = `-- name: CreateQuote :one
INSERT INTO quotes (
    tenant_id, source_currency, source_amount,
    dest_currency, dest_amount, stable_amount, fx_rate,
    fees, route, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, tenant_id, source_currency, source_amount, dest_currency, dest_amount, fx_rate, fees, route, expires_at, created_at, stable_amount
`

type CreateQuoteParams struct {
	TenantID       uuid.UUID      `json:"tenant_id"`
	SourceCurrency string         `json:"source_currency"`
	SourceAmount   pgtype.Numeric `json:"source_amount"`
	DestCurrency   string         `json:"dest_currency"`
	DestAmount     pgtype.Numeric `json:"dest_amount"`
	StableAmount   pgtype.Numeric `json:"stable_amount"`
	FxRate         pgtype.Numeric `json:"fx_rate"`
	Fees           []byte         `json:"fees"`
	Route          []byte         `json:"route"`
	ExpiresAt      time.Time      `json:"expires_at"`
}

func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, createQuote,
		arg.TenantID,
		arg.SourceCurrency,
		arg.SourceAmount,
		arg.DestCurrency,
		arg.DestAmount,
		arg.StableAmount,
		arg.FxRate,
		arg.Fees,
		arg.Route,
		arg.ExpiresAt,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceCurrency,
		&i.SourceAmount,
		&i.DestCurrency,
		&i.DestAmount,
		&i.FxRate,
		&i.Fees,
		&i.Route,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.StableAmount,
	)
	return i, err
}

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
    tenant_id, external_ref, idempotency_key, status,
    source_currency, source_amount, dest_currency, dest_amount,
    stable_coin, stable_amount, chain, fx_rate, fees,
    sender, recipient, quote_id,
    on_ramp_provider_id, off_ramp_provider_id, pii_encryption_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16,
    $17, $18, $19
) RETURNING id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id, fee_schedule_snapshot, pii_encryption_version
`

type CreateTransferParams struct {
	TenantID             uuid.UUID          `json:"tenant_id"`
	ExternalRef          pgtype.Text        `json:"external_ref"`
	IdempotencyKey       pgtype.Text        `json:"idempotency_key"`
	Status               TransferStatusEnum `json:"status"`
	SourceCurrency       string             `json:"source_currency"`
	SourceAmount         pgtype.Numeric     `json:"source_amount"`
	DestCurrency         string             `json:"dest_currency"`
	DestAmount           pgtype.Numeric     `json:"dest_amount"`
	StableCoin           pgtype.Text        `json:"stable_coin"`
	StableAmount         pgtype.Numeric     `json:"stable_amount"`
	Chain                pgtype.Text        `json:"chain"`
	FxRate               pgtype.Numeric     `json:"fx_rate"`
	Fees                 []byte             `json:"fees"`
	Sender               []byte             `json:"sender"`
	Recipient            []byte             `json:"recipient"`
	QuoteID              pgtype.UUID        `json:"quote_id"`
	OnRampProviderID     pgtype.Text        `json:"on_ramp_provider_id"`
	OffRampProviderID    pgtype.Text        `json:"off_ramp_provider_id"`
	PiiEncryptionVersion int16              `json:"pii_encryption_version"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.TenantID,
		arg.ExternalRef,
		arg.IdempotencyKey,
		arg.Status,
		arg.SourceCurrency,
		arg.SourceAmount,
		arg.DestCurrency,
		arg.DestAmount,
		arg.StableCoin,
		arg.StableAmount,
		arg.Chain,
		arg.FxRate,
		arg.Fees,
		arg.Sender,
		arg.Recipient,
		arg.QuoteID,
		arg.OnRampProviderID,
		arg.OffRampProviderID,
		arg.PiiEncryptionVersion,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.Version,
		&i.SourceCurrency,
		&i.SourceAmount,
		&i.DestCurrency,
		&i.DestAmount,
		&i.StableCoin,
		&i.StableAmount,
		&i.Chain,
		&i.FxRate,
		&i.Fees,
		&i.Sender,
		&i.Recipient,
		&i.QuoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FundedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.FailureCode,
		&i.OnRampProviderID,
		&i.OffRampProviderID,
		&i.FeeScheduleSnapshot,
		&i.PiiEncryptionVersion,
	)
	return i, err
}

const createTransferEvent = `-- name: CreateTransferEvent :one
INSERT INTO transfer_events (
    transfer_id, tenant_id, from_status, to_status,
    metadata, provider_ref
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, transfer_id, tenant_id, from_status, to_status, occurred_at, metadata, provider_ref, created_at
`

type CreateTransferEventParams struct {
	TransferID  uuid.UUID   `json:"transfer_id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	FromStatus  pgtype.Text `json:"from_status"`
	ToStatus    string      `json:"to_status"`
	Metadata    []byte      `json:"metadata"`
	ProviderRef pgtype.Text `json:"provider_ref"`
}

func (q *Queries) CreateTransferEvent(ctx context.Context, arg CreateTransferEventParams) (TransferEvent, error) {
	row := q.db.QueryRow(ctx, createTransferEvent,
		arg.TransferID,
		arg.TenantID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Metadata,
		arg.ProviderRef,
	)
	var i TransferEvent
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.TenantID,
		&i.FromStatus,
		&i.ToStatus,
		&i.OccurredAt,
		&i.Metadata,
		&i.ProviderRef,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveQuote = `-- name: GetActiveQuote :one
SELECT id, tenant_id, source_currency, source_amount, dest_currency, dest_amount, fx_rate, fees, route, expires_at, created_at, stable_amount FROM quotes
WHERE id = $1 AND tenant_id = $2
  AND expires_at > now()
`

type GetActiveQuoteParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetActiveQuote(ctx context.Context, arg GetActiveQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, getActiveQuote, arg.ID, arg.TenantID)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceCurrency,
		&i.SourceAmount,
		&i.DestCurrency,
		&i.DestAmount,
		&i.FxRate,
		&i.Fees,
		&i.Route,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.StableAmount,
	)
	return i, err
}

const getProviderTransaction = `-- name: GetProviderTransaction :one
SELECT id, tenant_id, provider, tx_type, external_id, transfer_id, status, amount, currency, chain, tx_hash, metadata, created_at, updated_at FROM provider_transactions
WHERE tenant_id = $1 AND transfer_id = $2 AND tx_type = $3
LIMIT 1
`

type GetProviderTransactionParams struct {
	TenantID   uuid.UUID          `json:"tenant_id"`
	TransferID uuid.UUID          `json:"transfer_id"`
	TxType     ProviderTxTypeEnum `json:"tx_type"`
}

func (q *Queries) GetProviderTransaction(ctx context.Context, arg GetProviderTransactionParams) (ProviderTransaction, error) {
	row := q.db.QueryRow(ctx, getProviderTransaction, arg.TenantID, arg.TransferID, arg.TxType)
	var i ProviderTransaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.TxType,
		&i.ExternalID,
		&i.TransferID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Chain,
		&i.TxHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuote = `-- name: GetQuote :one
SELECT id, tenant_id, source_currency, source_amount, dest_currency, dest_amount, fx_rate, fees, route, expires_at, created_at, stable_amount FROM quotes
WHERE id = $1 AND tenant_id = $2
`

type GetQuoteParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetQuote(ctx context.Context, arg GetQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, getQuote, arg.ID, arg.TenantID)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceCurrency,
		&i.SourceAmount,
		&i.DestCurrency,
		&i.DestAmount,
		&i.FxRate,
		&i.Fees,
		&i.Route,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.StableAmount,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id, fee_schedule_snapshot, pii_encryption_version FROM transfers
WHERE id = $1 AND tenant_id = $2
`

type GetTransferParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTransfer(ctx context.Context, arg GetTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransfer, arg.ID, arg.TenantID)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.Version,
		&i.SourceCurrency,
		&i.SourceAmount,
		&i.DestCurrency,
		&i.DestAmount,
		&i.StableCoin,
		&i.StableAmount,
		&i.Chain,
		&i.FxRate,
		&i.Fees,
		&i.Sender,
		&i.Recipient,
		&i.QuoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FundedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.FailureCode,
		&i.OnRampProviderID,
		&i.OffRampProviderID,
		&i.FeeScheduleSnapshot,
		&i.PiiEncryptionVersion,
	)
	return i, err
}

const getTransferByExternalRef = `-- name: GetTransferByExternalRef :one
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id, fee_schedule_snapshot, pii_encryption_version FROM transfers
WHERE tenant_id = $1 AND external_ref = $2
  AND created_at >= now() - INTERVAL '90 days'
LIMIT 1
`

type GetTransferByExternalRefParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	ExternalRef pgtype.Text `json:"external_ref"`
}

func (q *Queries) GetTransferByExternalRef(ctx context.Context, arg GetTransferByExternalRefParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferByExternalRef, arg.TenantID, arg.ExternalRef)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.Version,
		&i.SourceCurrency,
		&i.SourceAmount,
		&i.DestCurrency,
		&i.DestAmount,
		&i.StableCoin,
		&i.StableAmount,
		&i.Chain,
		&i.FxRate,
		&i.Fees,
		&i.Sender,
		&i.Recipient,
		&i.QuoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FundedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.FailureCode,
		&i.OnRampProviderID,
		&i.OffRampProviderID,
		&i.FeeScheduleSnapshot,
		&i.PiiEncryptionVersion,
	)
	return i, err
}

const getTransferByID = `-- name: GetTransferByID :one
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id, fee_schedule_snapshot, pii_encryption_version FROM transfers
WHERE id = $1
`

// SECURITY NOTE: This query intentionally omits tenant_id for use by internal
// worker pipelines where the tenant_id comes from the trusted event payload.
// Never expose this query path to tenant-facing API endpoints. All API endpoints
// must use GetTransfer (which includes tenant_id) instead.
func (q *Queries) GetTransferByID(ctx context.Context, id uuid.UUID) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferByID, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.Version,
		&i.SourceCurrency,
		&i.SourceAmount,
		&i.DestCurrency,
		&i.DestAmount,
		&i.StableCoin,
		&i.StableAmount,
		&i.Chain,
		&i.FxRate,
		&i.Fees,
		&i.Sender,
		&i.Recipient,
		&i.QuoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FundedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.FailureCode,
		&i.OnRampProviderID,
		&i.OffRampProviderID,
		&i.FeeScheduleSnapshot,
		&i.PiiEncryptionVersion,
	)
	return i, err
}

const getTransferByIdempotencyKey = `-- name: GetTransferByIdempotencyKey :one
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id, fee_schedule_snapshot, pii_encryption_version FROM transfers
WHERE tenant_id = $1 AND idempotency_key = $2
  AND created_at >= now() - INTERVAL '72 hours'
LIMIT 1
`

type GetTransferByIdempotencyKeyParams struct {
	TenantID       uuid.UUID   `json:"tenant_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) GetTransferByIdempotencyKey(ctx context.Context, arg GetTransferByIdempotencyKeyParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferByIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.Version,
		&i.SourceCurrency,
		&i.SourceAmount,
		&i.DestCurrency,
		&i.DestAmount,
		&i.StableCoin,
		&i.StableAmount,
		&i.Chain,
		&i.FxRate,
		&i.Fees,
		&i.Sender,
		&i.Recipient,
		&i.QuoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FundedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.FailureCode,
		&i.OnRampProviderID,
		&i.OffRampProviderID,
		&i.FeeScheduleSnapshot,
		&i.PiiEncryptionVersion,
	)
	return i, err
}

const listProviderTransactions = `-- name: ListProviderTransactions :many
SELECT id, tenant_id, provider, tx_type, external_id, transfer_id, status, amount, currency, chain, tx_hash, metadata, created_at, updated_at FROM provider_transactions
WHERE tenant_id = $1 AND transfer_id = $2
ORDER BY created_at
`

type ListProviderTransactionsParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	TransferID uuid.UUID `json:"transfer_id"`
}

func (q *Queries) ListProviderTransactions(ctx context.Context, arg ListProviderTransactionsParams) ([]ProviderTransaction, error) {
	rows, err := q.db.Query(ctx, listProviderTransactions, arg.TenantID, arg.TransferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderTransaction{}
	for rows.Next() {
		var i ProviderTransaction
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Provider,
			&i.TxType,
			&i.ExternalID,
			&i.TransferID,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.Chain,
			&i.TxHash,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckTransfers = `-- name: ListStuckTransfers :many
SELECT id, tenant_id, status, updated_at, created_at
FROM transfers
WHERE status = $1
  AND updated_at < $2
ORDER BY updated_at ASC
LIMIT $3
`

type ListStuckTransfersParams struct {
	Status    TransferStatusEnum `json:"status"`
	UpdatedAt time.Time          `json:"updated_at"`
	Limit     int32              `json:"limit"`
}

type ListStuckTransfersRow struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	Status    TransferStatusEnum `json:"status"`
	UpdatedAt time.Time          `json:"updated_at"`
	CreatedAt time.Time          `json:"created_at"`
}

// Used by recovery detector to find transfers stuck in non-terminal states.
// This is an admin-only system query that scans across all tenants.
func (q *Queries) ListStuckTransfers(ctx context.Context, arg ListStuckTransfersParams) ([]ListStuckTransfersRow, error) {
	rows, err := q.db.Query(ctx, listStuckTransfers, arg.Status, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStuckTransfersRow{}
	for rows.Next() {
		var i ListStuckTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Status,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferEvents = `-- name: ListTransferEvents :many
SELECT id, transfer_id, tenant_id, from_status, to_status, occurred_at, metadata, provider_ref, created_at FROM transfer_events
WHERE tenant_id = $1 AND transfer_id = $2
ORDER BY occurred_at DESC
`

type ListTransferEventsParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	TransferID uuid.UUID `json:"transfer_id"`
}

func (q *Queries) ListTransferEvents(ctx context.Context, arg ListTransferEventsParams) ([]TransferEvent, error) {
	rows, err := q.db.Query(ctx, listTransferEvents, arg.TenantID, arg.TransferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransferEvent{}
	for rows.Next() {
		var i TransferEvent
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.TenantID,
			&i.FromStatus,
			&i.ToStatus,
			&i.OccurredAt,
			&i.Metadata,
			&i.ProviderRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByStatus = `-- name: ListTransfersByStatus :many
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id, fee_schedule_snapshot, pii_encryption_version FROM transfers
WHERE tenant_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListTransfersByStatusParams struct {
	TenantID uuid.UUID          `json:"tenant_id"`
	Status   TransferStatusEnum `json:"status"`
	Limit    int32              `json:"limit"`
	Offset   int32              `json:"offset"`
}

func (q *Queries) ListTransfersByStatus(ctx context.Context, arg ListTransfersByStatusParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByStatus,
		arg.TenantID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalRef,
			&i.IdempotencyKey,
			&i.Status,
			&i.Version,
			&i.SourceCurrency,
			&i.SourceAmount,
			&i.DestCurrency,
			&i.DestAmount,
			&i.StableCoin,
			&i.StableAmount,
			&i.Chain,
			&i.FxRate,
			&i.Fees,
			&i.Sender,
			&i.Recipient,
			&i.QuoteID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FundedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.FailureCode,
			&i.OnRampProviderID,
			&i.OffRampProviderID,
			&i.FeeScheduleSnapshot,
			&i.PiiEncryptionVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByStatusCursor = `-- name: ListTransfersByStatusCursor :many
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id, fee_schedule_snapshot, pii_encryption_version FROM transfers
WHERE tenant_id = $1 AND status = $2
  AND created_at < $3
ORDER BY created_at DESC
LIMIT $4
`

type ListTransfersByStatusCursorParams struct {
	TenantID  uuid.UUID          `json:"tenant_id"`
	Status    TransferStatusEnum `json:"status"`
	CreatedAt time.Time          `json:"created_at"`
	Limit     int32              `json:"limit"`
}

// Cursor-based pagination: pass the created_at of the last item from the
// previous page as $3 (or a far-future timestamp for the first page).
func (q *Queries) ListTransfersByStatusCursor(ctx context.Context, arg ListTransfersByStatusCursorParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByStatusCursor,
		arg.TenantID,
		arg.Status,
		arg.CreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalRef,
			&i.IdempotencyKey,
			&i.Status,
			&i.Version,
			&i.SourceCurrency,
			&i.SourceAmount,
			&i.DestCurrency,
			&i.DestAmount,
			&i.StableCoin,
			&i.StableAmount,
			&i.Chain,
			&i.FxRate,
			&i.Fees,
			&i.Sender,
			&i.Recipient,
			&i.QuoteID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FundedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.FailureCode,
			&i.OnRampProviderID,
			&i.OffRampProviderID,
			&i.FeeScheduleSnapshot,
			&i.PiiEncryptionVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByTenant = `-- name: ListTransfersByTenant :many
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id, fee_schedule_snapshot, pii_encryption_version FROM transfers
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransfersByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListTransfersByTenant(ctx context.Context, arg ListTransfersByTenantParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalRef,
			&i.IdempotencyKey,
			&i.Status,
			&i.Version,
			&i.SourceCurrency,
			&i.SourceAmount,
			&i.DestCurrency,
			&i.DestAmount,
			&i.StableCoin,
			&i.StableAmount,
			&i.Chain,
			&i.FxRate,
			&i.Fees,
			&i.Sender,
			&i.Recipient,
			&i.QuoteID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FundedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.FailureCode,
			&i.OnRampProviderID,
			&i.OffRampProviderID,
			&i.FeeScheduleSnapshot,
			&i.PiiEncryptionVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByTenantCursor = `-- name: ListTransfersByTenantCursor :many
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id, fee_schedule_snapshot, pii_encryption_version FROM transfers
WHERE tenant_id = $1
  AND created_at < $2
ORDER BY created_at DESC
LIMIT $3
`

type ListTransfersByTenantCursorParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	CreatedAt time.Time `json:"created_at"`
	Limit     int32     `json:"limit"`
}

// Cursor-based pagination: pass the created_at of the last item from the
// previous page as $2 (or a far-future timestamp for the first page).
// This avoids OFFSET which degrades at high page numbers (50M rows/day).
func (q *Queries) ListTransfersByTenantCursor(ctx context.Context, arg ListTransfersByTenantCursorParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByTenantCursor, arg.TenantID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalRef,
			&i.IdempotencyKey,
			&i.Status,
			&i.Version,
			&i.SourceCurrency,
			&i.SourceAmount,
			&i.DestCurrency,
			&i.DestAmount,
			&i.StableCoin,
			&i.StableAmount,
			&i.Chain,
			&i.FxRate,
			&i.Fees,
			&i.Sender,
			&i.Recipient,
			&i.QuoteID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FundedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.FailureCode,
			&i.OnRampProviderID,
			&i.OffRampProviderID,
			&i.FeeScheduleSnapshot,
			&i.PiiEncryptionVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByTenantFiltered = `-- name: ListTransfersByTenantFiltered :many
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id, fee_schedule_snapshot, pii_encryption_version FROM transfers
WHERE tenant_id = $1
  AND ($2::text = '' OR status = $2)
  AND ($3::text = '' OR
       id::text ILIKE '%' || $3 || '%' OR
       COALESCE(external_ref, '') ILIKE '%' || $3 || '%' OR
       COALESCE(idempotency_key, '') ILIKE '%' || $3 || '%')
ORDER BY updated_at DESC
LIMIT $4
`

type ListTransfersByTenantFilteredParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	StatusFilter string    `json:"status_filter"`
	SearchQuery  string    `json:"search_query"`
	PageSize     int32     `json:"page_size"`
}

// Server-side filtering for dashboard: optional status exact match and
// optional substring search on id, external_ref, or idempotency_key.
// Pass empty string for @status_filter or @search_query to skip that filter.
func (q *Queries) ListTransfersByTenantFiltered(ctx context.Context, arg ListTransfersByTenantFilteredParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByTenantFiltered,
		arg.TenantID,
		arg.StatusFilter,
		arg.SearchQuery,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalRef,
			&i.IdempotencyKey,
			&i.Status,
			&i.Version,
			&i.SourceCurrency,
			&i.SourceAmount,
			&i.DestCurrency,
			&i.DestAmount,
			&i.StableCoin,
			&i.StableAmount,
			&i.Chain,
			&i.FxRate,
			&i.Fees,
			&i.Sender,
			&i.Recipient,
			&i.QuoteID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FundedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.FailureCode,
			&i.OnRampProviderID,
			&i.OffRampProviderID,
			&i.FeeScheduleSnapshot,
			&i.PiiEncryptionVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersInDateRange = `-- name: ListTransfersInDateRange :many
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id, fee_schedule_snapshot, pii_encryption_version FROM transfers
WHERE tenant_id = $1
  AND created_at >= $2
  AND created_at < $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListTransfersInDateRangeParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListTransfersInDateRange(ctx context.Context, arg ListTransfersInDateRangeParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersInDateRange,
		arg.TenantID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalRef,
			&i.IdempotencyKey,
			&i.Status,
			&i.Version,
			&i.SourceCurrency,
			&i.SourceAmount,
			&i.DestCurrency,
			&i.DestAmount,
			&i.StableCoin,
			&i.StableAmount,
			&i.Chain,
			&i.FxRate,
			&i.Fees,
			&i.Sender,
			&i.Recipient,
			&i.QuoteID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FundedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.FailureCode,
			&i.OnRampProviderID,
			&i.OffRampProviderID,
			&i.FeeScheduleSnapshot,
			&i.PiiEncryptionVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersInDateRangeCursor = `-- name: ListTransfersInDateRangeCursor :many
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id, fee_schedule_snapshot, pii_encryption_version FROM transfers
WHERE tenant_id = $1
  AND created_at >= $2
  AND created_at < $3
  AND created_at < $4
ORDER BY created_at DESC
LIMIT $5
`

type ListTransfersInDateRangeCursorParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	CreatedAt_3 time.Time `json:"created_at_3"`
	Limit       int32     `json:"limit"`
}

// Cursor-based pagination within a date range: pass the created_at of the
// last item from the previous page as $4 (must be >= $2 and < $3).
func (q *Queries) ListTransfersInDateRangeCursor(ctx context.Context, arg ListTransfersInDateRangeCursorParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersInDateRangeCursor,
		arg.TenantID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.CreatedAt_3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalRef,
			&i.IdempotencyKey,
			&i.Status,
			&i.Version,
			&i.SourceCurrency,
			&i.SourceAmount,
			&i.DestCurrency,
			&i.DestAmount,
			&i.StableCoin,
			&i.StableAmount,
			&i.Chain,
			&i.FxRate,
			&i.Fees,
			&i.Sender,
			&i.Recipient,
			&i.QuoteID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FundedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.FailureCode,
			&i.OnRampProviderID,
			&i.OffRampProviderID,
			&i.FeeScheduleSnapshot,
			&i.PiiEncryptionVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDailyVolumeByTenant = `-- name: SumDailyVolumeByTenant :one
SELECT COALESCE(SUM(stable_amount), 0)::NUMERIC(28,8) AS total_volume
FROM transfers
WHERE tenant_id = $1
  AND created_at >= $2
  AND created_at < $3
  AND status NOT IN ('FAILED', 'REFUNDED')
`

type SumDailyVolumeByTenantParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

// Sums the USD-equivalent volume (stable_amount) for daily limit enforcement.
// stable_amount is the intermediate stablecoin amount (USDT, pegged 1:1 to USD),
// set from the quote at transfer creation time.
func (q *Queries) SumDailyVolumeByTenant(ctx context.Context, arg SumDailyVolumeByTenantParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumDailyVolumeByTenant, arg.TenantID, arg.CreatedAt, arg.CreatedAt_2)
	var total_volume pgtype.Numeric
	err := row.Scan(&total_volume)
	return total_volume, err
}

const transitionTransferStatus = `-- name: TransitionTransferStatus :execresult
UPDATE transfers
SET status = $1::transfer_status_enum,
    version = version + 1,
    updated_at = now(),
    funded_at    = CASE WHEN $1::text = 'FUNDED'    THEN now() ELSE funded_at    END,
    completed_at = CASE WHEN $1::text = 'COMPLETED' THEN now() ELSE completed_at END,
    failed_at    = CASE WHEN $1::text = 'FAILED'    THEN now() ELSE failed_at    END
WHERE id = $2 AND version = $3
`

type TransitionTransferStatusParams struct {
	NewStatus       TransferStatusEnum `json:"new_status"`
	ID              uuid.UUID          `json:"id"`
	ExpectedVersion int64              `json:"expected_version"`
}

// Atomically updates transfer status with optimistic lock (version check) and
// sets status-specific timestamps. Used by outbox TransitionWithOutbox.
func (q *Queries) TransitionTransferStatus(ctx context.Context, arg TransitionTransferStatusParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, transitionTransferStatus, arg.NewStatus, arg.ID, arg.ExpectedVersion)
}

const updateProviderTransactionFull = `-- name: UpdateProviderTransactionFull :exec
UPDATE provider_transactions
SET status = $4,
    external_id = $5,
    tx_hash = $6,
    metadata = $7,
    updated_at = now()
WHERE tenant_id = $1 AND transfer_id = $2 AND tx_type = $3
`

type UpdateProviderTransactionFullParams struct {
	TenantID   uuid.UUID          `json:"tenant_id"`
	TransferID uuid.UUID          `json:"transfer_id"`
	TxType     ProviderTxTypeEnum `json:"tx_type"`
	Status     string             `json:"status"`
	ExternalID pgtype.Text        `json:"external_id"`
	TxHash     pgtype.Text        `json:"tx_hash"`
	Metadata   []byte             `json:"metadata"`
}

func (q *Queries) UpdateProviderTransactionFull(ctx context.Context, arg UpdateProviderTransactionFullParams) error {
	_, err := q.db.Exec(ctx, updateProviderTransactionFull,
		arg.TenantID,
		arg.TransferID,
		arg.TxType,
		arg.Status,
		arg.ExternalID,
		arg.TxHash,
		arg.Metadata,
	)
	return err
}

const updateProviderTransactionHash = `-- name: UpdateProviderTransactionHash :exec
UPDATE provider_transactions
SET tx_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateProviderTransactionHashParams struct {
	ID     uuid.UUID   `json:"id"`
	TxHash pgtype.Text `json:"tx_hash"`
}

func (q *Queries) UpdateProviderTransactionHash(ctx context.Context, arg UpdateProviderTransactionHashParams) error {
	_, err := q.db.Exec(ctx, updateProviderTransactionHash, arg.ID, arg.TxHash)
	return err
}

const updateProviderTransactionStatus = `-- name: UpdateProviderTransactionStatus :exec
UPDATE provider_transactions
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateProviderTransactionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateProviderTransactionStatus(ctx context.Context, arg UpdateProviderTransactionStatusParams) error {
	_, err := q.db.Exec(ctx, updateProviderTransactionStatus, arg.ID, arg.Status)
	return err
}

const updateTransferDestAmount = `-- name: UpdateTransferDestAmount :exec
UPDATE transfers
SET dest_amount = $3, fx_rate = $4, stable_coin = $5, stable_amount = $6, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateTransferDestAmountParams struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	DestAmount   pgtype.Numeric `json:"dest_amount"`
	FxRate       pgtype.Numeric `json:"fx_rate"`
	StableCoin   pgtype.Text    `json:"stable_coin"`
	StableAmount pgtype.Numeric `json:"stable_amount"`
}

func (q *Queries) UpdateTransferDestAmount(ctx context.Context, arg UpdateTransferDestAmountParams) error {
	_, err := q.db.Exec(ctx, updateTransferDestAmount,
		arg.ID,
		arg.TenantID,
		arg.DestAmount,
		arg.FxRate,
		arg.StableCoin,
		arg.StableAmount,
	)
	return err
}

const updateTransferFailure = `-- name: UpdateTransferFailure :exec
UPDATE transfers
SET status = 'FAILED',
    version = version + 1,
    updated_at = now(),
    failed_at = now(),
    failure_reason = $3,
    failure_code = $4
WHERE id = $1 AND tenant_id = $2
`

type UpdateTransferFailureParams struct {
	ID            uuid.UUID   `json:"id"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	FailureReason pgtype.Text `json:"failure_reason"`
	FailureCode   pgtype.Text `json:"failure_code"`
}

func (q *Queries) UpdateTransferFailure(ctx context.Context, arg UpdateTransferFailureParams) error {
	_, err := q.db.Exec(ctx, updateTransferFailure,
		arg.ID,
		arg.TenantID,
		arg.FailureReason,
		arg.FailureCode,
	)
	return err
}

const updateTransferStatus = `-- name: UpdateTransferStatus :exec
UPDATE transfers
SET status = $3,
    version = version + 1,
    updated_at = now(),
    funded_at = CASE WHEN $3::text = 'FUNDED' THEN now() ELSE funded_at END,
    completed_at = CASE WHEN $3::text = 'COMPLETED' THEN now() ELSE completed_at END,
    failed_at = CASE WHEN $3::text = 'FAILED' THEN now() ELSE failed_at END
WHERE id = $1 AND tenant_id = $2
`

type UpdateTransferStatusParams struct {
	ID       uuid.UUID          `json:"id"`
	TenantID uuid.UUID          `json:"tenant_id"`
	Status   TransferStatusEnum `json:"status"`
}

func (q *Queries) UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransferStatus, arg.ID, arg.TenantID, arg.Status)
	return err
}

const updateTransferStatusWithVersion = `-- name: UpdateTransferStatusWithVersion :exec
UPDATE transfers
SET status = $3,
    version = version + 1,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND version = $4
`

type UpdateTransferStatusWithVersionParams struct {
	ID       uuid.UUID          `json:"id"`
	TenantID uuid.UUID          `json:"tenant_id"`
	Status   TransferStatusEnum `json:"status"`
	Version  int64              `json:"version"`
}

func (q *Queries) UpdateTransferStatusWithVersion(ctx context.Context, arg UpdateTransferStatusWithVersionParams) error {
	_, err := q.db.Exec(ctx, updateTransferStatusWithVersion,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.Version,
	)
	return err
}
