// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfers.sql

package transferdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTransfersByTenant = `-- name: CountTransfersByTenant :one
SELECT count(*) FROM transfers
WHERE tenant_id = $1
`

func (q *Queries) CountTransfersByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransfersByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProviderTransaction = `-- name: CreateProviderTransaction :one
INSERT INTO provider_transactions (
    tenant_id, provider, tx_type, external_id,
    transfer_id, status, amount, currency,
    chain, tx_hash, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, tenant_id, provider, tx_type, external_id, transfer_id, status, amount, currency, chain, tx_hash, metadata, created_at, updated_at
`

type CreateProviderTransactionParams struct {
	TenantID   uuid.UUID      `json:"tenant_id"`
	Provider   string         `json:"provider"`
	TxType     string         `json:"tx_type"`
	ExternalID pgtype.Text    `json:"external_id"`
	TransferID uuid.UUID      `json:"transfer_id"`
	Status     string         `json:"status"`
	Amount     pgtype.Numeric `json:"amount"`
	Currency   string         `json:"currency"`
	Chain      pgtype.Text    `json:"chain"`
	TxHash     pgtype.Text    `json:"tx_hash"`
	Metadata   []byte         `json:"metadata"`
}

func (q *Queries) CreateProviderTransaction(ctx context.Context, arg CreateProviderTransactionParams) (ProviderTransaction, error) {
	row := q.db.QueryRow(ctx, createProviderTransaction,
		arg.TenantID,
		arg.Provider,
		arg.TxType,
		arg.ExternalID,
		arg.TransferID,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.Chain,
		arg.TxHash,
		arg.Metadata,
	)
	var i ProviderTransaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.TxType,
		&i.ExternalID,
		&i.TransferID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Chain,
		&i.TxHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuote = `-- name: CreateQuote :one
INSERT INTO quotes (
    tenant_id, source_currency, source_amount,
    dest_currency, dest_amount, stable_amount, fx_rate,
    fees, route, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, tenant_id, source_currency, source_amount, dest_currency, dest_amount, fx_rate, fees, route, expires_at, created_at, stable_amount
`

type CreateQuoteParams struct {
	TenantID       uuid.UUID      `json:"tenant_id"`
	SourceCurrency string         `json:"source_currency"`
	SourceAmount   pgtype.Numeric `json:"source_amount"`
	DestCurrency   string         `json:"dest_currency"`
	DestAmount     pgtype.Numeric `json:"dest_amount"`
	StableAmount   pgtype.Numeric `json:"stable_amount"`
	FxRate         pgtype.Numeric `json:"fx_rate"`
	Fees           []byte         `json:"fees"`
	Route          []byte         `json:"route"`
	ExpiresAt      time.Time      `json:"expires_at"`
}

func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, createQuote,
		arg.TenantID,
		arg.SourceCurrency,
		arg.SourceAmount,
		arg.DestCurrency,
		arg.DestAmount,
		arg.StableAmount,
		arg.FxRate,
		arg.Fees,
		arg.Route,
		arg.ExpiresAt,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceCurrency,
		&i.SourceAmount,
		&i.DestCurrency,
		&i.DestAmount,
		&i.FxRate,
		&i.Fees,
		&i.Route,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.StableAmount,
	)
	return i, err
}

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
    tenant_id, external_ref, idempotency_key, status,
    source_currency, source_amount, dest_currency, dest_amount,
    stable_coin, stable_amount, chain, fx_rate, fees,
    sender, recipient, quote_id,
    on_ramp_provider_id, off_ramp_provider_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16,
    $17, $18
) RETURNING id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id
`

type CreateTransferParams struct {
	TenantID          uuid.UUID      `json:"tenant_id"`
	ExternalRef       pgtype.Text    `json:"external_ref"`
	IdempotencyKey    pgtype.Text    `json:"idempotency_key"`
	Status            string         `json:"status"`
	SourceCurrency    string         `json:"source_currency"`
	SourceAmount      pgtype.Numeric `json:"source_amount"`
	DestCurrency      string         `json:"dest_currency"`
	DestAmount        pgtype.Numeric `json:"dest_amount"`
	StableCoin        pgtype.Text    `json:"stable_coin"`
	StableAmount      pgtype.Numeric `json:"stable_amount"`
	Chain             pgtype.Text    `json:"chain"`
	FxRate            pgtype.Numeric `json:"fx_rate"`
	Fees              []byte         `json:"fees"`
	Sender            []byte         `json:"sender"`
	Recipient         []byte         `json:"recipient"`
	QuoteID           pgtype.UUID    `json:"quote_id"`
	OnRampProviderID  pgtype.Text    `json:"on_ramp_provider_id"`
	OffRampProviderID pgtype.Text    `json:"off_ramp_provider_id"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.TenantID,
		arg.ExternalRef,
		arg.IdempotencyKey,
		arg.Status,
		arg.SourceCurrency,
		arg.SourceAmount,
		arg.DestCurrency,
		arg.DestAmount,
		arg.StableCoin,
		arg.StableAmount,
		arg.Chain,
		arg.FxRate,
		arg.Fees,
		arg.Sender,
		arg.Recipient,
		arg.QuoteID,
		arg.OnRampProviderID,
		arg.OffRampProviderID,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.Version,
		&i.SourceCurrency,
		&i.SourceAmount,
		&i.DestCurrency,
		&i.DestAmount,
		&i.StableCoin,
		&i.StableAmount,
		&i.Chain,
		&i.FxRate,
		&i.Fees,
		&i.Sender,
		&i.Recipient,
		&i.QuoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FundedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.FailureCode,
		&i.OnRampProviderID,
		&i.OffRampProviderID,
	)
	return i, err
}

const createTransferEvent = `-- name: CreateTransferEvent :one
INSERT INTO transfer_events (
    transfer_id, tenant_id, from_status, to_status,
    metadata, provider_ref
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, transfer_id, tenant_id, from_status, to_status, occurred_at, metadata, provider_ref, created_at
`

type CreateTransferEventParams struct {
	TransferID  uuid.UUID   `json:"transfer_id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	FromStatus  pgtype.Text `json:"from_status"`
	ToStatus    string      `json:"to_status"`
	Metadata    []byte      `json:"metadata"`
	ProviderRef pgtype.Text `json:"provider_ref"`
}

func (q *Queries) CreateTransferEvent(ctx context.Context, arg CreateTransferEventParams) (TransferEvent, error) {
	row := q.db.QueryRow(ctx, createTransferEvent,
		arg.TransferID,
		arg.TenantID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Metadata,
		arg.ProviderRef,
	)
	var i TransferEvent
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.TenantID,
		&i.FromStatus,
		&i.ToStatus,
		&i.OccurredAt,
		&i.Metadata,
		&i.ProviderRef,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveQuote = `-- name: GetActiveQuote :one
SELECT id, tenant_id, source_currency, source_amount, dest_currency, dest_amount, fx_rate, fees, route, expires_at, created_at, stable_amount FROM quotes
WHERE id = $1 AND tenant_id = $2
  AND expires_at > now()
`

type GetActiveQuoteParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetActiveQuote(ctx context.Context, arg GetActiveQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, getActiveQuote, arg.ID, arg.TenantID)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceCurrency,
		&i.SourceAmount,
		&i.DestCurrency,
		&i.DestAmount,
		&i.FxRate,
		&i.Fees,
		&i.Route,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.StableAmount,
	)
	return i, err
}

const getQuote = `-- name: GetQuote :one
SELECT id, tenant_id, source_currency, source_amount, dest_currency, dest_amount, fx_rate, fees, route, expires_at, created_at, stable_amount FROM quotes
WHERE id = $1 AND tenant_id = $2
`

type GetQuoteParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetQuote(ctx context.Context, arg GetQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, getQuote, arg.ID, arg.TenantID)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceCurrency,
		&i.SourceAmount,
		&i.DestCurrency,
		&i.DestAmount,
		&i.FxRate,
		&i.Fees,
		&i.Route,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.StableAmount,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id FROM transfers
WHERE id = $1 AND tenant_id = $2
`

type GetTransferParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTransfer(ctx context.Context, arg GetTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransfer, arg.ID, arg.TenantID)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.Version,
		&i.SourceCurrency,
		&i.SourceAmount,
		&i.DestCurrency,
		&i.DestAmount,
		&i.StableCoin,
		&i.StableAmount,
		&i.Chain,
		&i.FxRate,
		&i.Fees,
		&i.Sender,
		&i.Recipient,
		&i.QuoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FundedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.FailureCode,
		&i.OnRampProviderID,
		&i.OffRampProviderID,
	)
	return i, err
}

const getTransferByExternalRef = `-- name: GetTransferByExternalRef :one
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id FROM transfers
WHERE tenant_id = $1 AND external_ref = $2
LIMIT 1
`

type GetTransferByExternalRefParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	ExternalRef pgtype.Text `json:"external_ref"`
}

func (q *Queries) GetTransferByExternalRef(ctx context.Context, arg GetTransferByExternalRefParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferByExternalRef, arg.TenantID, arg.ExternalRef)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.Version,
		&i.SourceCurrency,
		&i.SourceAmount,
		&i.DestCurrency,
		&i.DestAmount,
		&i.StableCoin,
		&i.StableAmount,
		&i.Chain,
		&i.FxRate,
		&i.Fees,
		&i.Sender,
		&i.Recipient,
		&i.QuoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FundedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.FailureCode,
		&i.OnRampProviderID,
		&i.OffRampProviderID,
	)
	return i, err
}

const getTransferByID = `-- name: GetTransferByID :one
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id FROM transfers
WHERE id = $1
`

func (q *Queries) GetTransferByID(ctx context.Context, id uuid.UUID) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferByID, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.Version,
		&i.SourceCurrency,
		&i.SourceAmount,
		&i.DestCurrency,
		&i.DestAmount,
		&i.StableCoin,
		&i.StableAmount,
		&i.Chain,
		&i.FxRate,
		&i.Fees,
		&i.Sender,
		&i.Recipient,
		&i.QuoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FundedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.FailureCode,
		&i.OnRampProviderID,
		&i.OffRampProviderID,
	)
	return i, err
}

const getTransferByIdempotencyKey = `-- name: GetTransferByIdempotencyKey :one
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id FROM transfers
WHERE tenant_id = $1 AND idempotency_key = $2
LIMIT 1
`

type GetTransferByIdempotencyKeyParams struct {
	TenantID       uuid.UUID   `json:"tenant_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) GetTransferByIdempotencyKey(ctx context.Context, arg GetTransferByIdempotencyKeyParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferByIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.Version,
		&i.SourceCurrency,
		&i.SourceAmount,
		&i.DestCurrency,
		&i.DestAmount,
		&i.StableCoin,
		&i.StableAmount,
		&i.Chain,
		&i.FxRate,
		&i.Fees,
		&i.Sender,
		&i.Recipient,
		&i.QuoteID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FundedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.FailureCode,
		&i.OnRampProviderID,
		&i.OffRampProviderID,
	)
	return i, err
}

const listProviderTransactions = `-- name: ListProviderTransactions :many
SELECT id, tenant_id, provider, tx_type, external_id, transfer_id, status, amount, currency, chain, tx_hash, metadata, created_at, updated_at FROM provider_transactions
WHERE tenant_id = $1 AND transfer_id = $2
ORDER BY created_at
`

type ListProviderTransactionsParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	TransferID uuid.UUID `json:"transfer_id"`
}

func (q *Queries) ListProviderTransactions(ctx context.Context, arg ListProviderTransactionsParams) ([]ProviderTransaction, error) {
	rows, err := q.db.Query(ctx, listProviderTransactions, arg.TenantID, arg.TransferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderTransaction{}
	for rows.Next() {
		var i ProviderTransaction
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Provider,
			&i.TxType,
			&i.ExternalID,
			&i.TransferID,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.Chain,
			&i.TxHash,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferEvents = `-- name: ListTransferEvents :many
SELECT id, transfer_id, tenant_id, from_status, to_status, occurred_at, metadata, provider_ref, created_at FROM transfer_events
WHERE tenant_id = $1 AND transfer_id = $2
ORDER BY occurred_at DESC
`

type ListTransferEventsParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	TransferID uuid.UUID `json:"transfer_id"`
}

func (q *Queries) ListTransferEvents(ctx context.Context, arg ListTransferEventsParams) ([]TransferEvent, error) {
	rows, err := q.db.Query(ctx, listTransferEvents, arg.TenantID, arg.TransferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransferEvent{}
	for rows.Next() {
		var i TransferEvent
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.TenantID,
			&i.FromStatus,
			&i.ToStatus,
			&i.OccurredAt,
			&i.Metadata,
			&i.ProviderRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByStatus = `-- name: ListTransfersByStatus :many
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id FROM transfers
WHERE tenant_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListTransfersByStatusParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Status   string    `json:"status"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListTransfersByStatus(ctx context.Context, arg ListTransfersByStatusParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByStatus,
		arg.TenantID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalRef,
			&i.IdempotencyKey,
			&i.Status,
			&i.Version,
			&i.SourceCurrency,
			&i.SourceAmount,
			&i.DestCurrency,
			&i.DestAmount,
			&i.StableCoin,
			&i.StableAmount,
			&i.Chain,
			&i.FxRate,
			&i.Fees,
			&i.Sender,
			&i.Recipient,
			&i.QuoteID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FundedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.FailureCode,
			&i.OnRampProviderID,
			&i.OffRampProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByTenant = `-- name: ListTransfersByTenant :many
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id FROM transfers
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransfersByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListTransfersByTenant(ctx context.Context, arg ListTransfersByTenantParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalRef,
			&i.IdempotencyKey,
			&i.Status,
			&i.Version,
			&i.SourceCurrency,
			&i.SourceAmount,
			&i.DestCurrency,
			&i.DestAmount,
			&i.StableCoin,
			&i.StableAmount,
			&i.Chain,
			&i.FxRate,
			&i.Fees,
			&i.Sender,
			&i.Recipient,
			&i.QuoteID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FundedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.FailureCode,
			&i.OnRampProviderID,
			&i.OffRampProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersInDateRange = `-- name: ListTransfersInDateRange :many
SELECT id, tenant_id, external_ref, idempotency_key, status, version, source_currency, source_amount, dest_currency, dest_amount, stable_coin, stable_amount, chain, fx_rate, fees, sender, recipient, quote_id, created_at, updated_at, funded_at, completed_at, failed_at, failure_reason, failure_code, on_ramp_provider_id, off_ramp_provider_id FROM transfers
WHERE tenant_id = $1
  AND created_at >= $2
  AND created_at < $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListTransfersInDateRangeParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListTransfersInDateRange(ctx context.Context, arg ListTransfersInDateRangeParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersInDateRange,
		arg.TenantID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalRef,
			&i.IdempotencyKey,
			&i.Status,
			&i.Version,
			&i.SourceCurrency,
			&i.SourceAmount,
			&i.DestCurrency,
			&i.DestAmount,
			&i.StableCoin,
			&i.StableAmount,
			&i.Chain,
			&i.FxRate,
			&i.Fees,
			&i.Sender,
			&i.Recipient,
			&i.QuoteID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FundedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.FailureCode,
			&i.OnRampProviderID,
			&i.OffRampProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDailyVolumeByTenant = `-- name: SumDailyVolumeByTenant :one
SELECT COALESCE(SUM(source_amount), 0)::NUMERIC(28,8) AS total_volume
FROM transfers
WHERE tenant_id = $1
  AND created_at >= $2
  AND created_at < $3
  AND status NOT IN ('FAILED', 'REFUNDED')
`

type SumDailyVolumeByTenantParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) SumDailyVolumeByTenant(ctx context.Context, arg SumDailyVolumeByTenantParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumDailyVolumeByTenant, arg.TenantID, arg.CreatedAt, arg.CreatedAt_2)
	var total_volume pgtype.Numeric
	err := row.Scan(&total_volume)
	return total_volume, err
}

const updateProviderTransactionHash = `-- name: UpdateProviderTransactionHash :exec
UPDATE provider_transactions
SET tx_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateProviderTransactionHashParams struct {
	ID     uuid.UUID   `json:"id"`
	TxHash pgtype.Text `json:"tx_hash"`
}

func (q *Queries) UpdateProviderTransactionHash(ctx context.Context, arg UpdateProviderTransactionHashParams) error {
	_, err := q.db.Exec(ctx, updateProviderTransactionHash, arg.ID, arg.TxHash)
	return err
}

const updateProviderTransactionStatus = `-- name: UpdateProviderTransactionStatus :exec
UPDATE provider_transactions
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateProviderTransactionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateProviderTransactionStatus(ctx context.Context, arg UpdateProviderTransactionStatusParams) error {
	_, err := q.db.Exec(ctx, updateProviderTransactionStatus, arg.ID, arg.Status)
	return err
}

const updateTransferDestAmount = `-- name: UpdateTransferDestAmount :exec
UPDATE transfers
SET dest_amount = $3, fx_rate = $4, stable_coin = $5, stable_amount = $6, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateTransferDestAmountParams struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	DestAmount   pgtype.Numeric `json:"dest_amount"`
	FxRate       pgtype.Numeric `json:"fx_rate"`
	StableCoin   pgtype.Text    `json:"stable_coin"`
	StableAmount pgtype.Numeric `json:"stable_amount"`
}

func (q *Queries) UpdateTransferDestAmount(ctx context.Context, arg UpdateTransferDestAmountParams) error {
	_, err := q.db.Exec(ctx, updateTransferDestAmount,
		arg.ID,
		arg.TenantID,
		arg.DestAmount,
		arg.FxRate,
		arg.StableCoin,
		arg.StableAmount,
	)
	return err
}

const updateTransferFailure = `-- name: UpdateTransferFailure :exec
UPDATE transfers
SET status = 'FAILED',
    version = version + 1,
    updated_at = now(),
    failed_at = now(),
    failure_reason = $3,
    failure_code = $4
WHERE id = $1 AND tenant_id = $2
`

type UpdateTransferFailureParams struct {
	ID            uuid.UUID   `json:"id"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	FailureReason pgtype.Text `json:"failure_reason"`
	FailureCode   pgtype.Text `json:"failure_code"`
}

func (q *Queries) UpdateTransferFailure(ctx context.Context, arg UpdateTransferFailureParams) error {
	_, err := q.db.Exec(ctx, updateTransferFailure,
		arg.ID,
		arg.TenantID,
		arg.FailureReason,
		arg.FailureCode,
	)
	return err
}

const updateTransferStatus = `-- name: UpdateTransferStatus :exec
UPDATE transfers
SET status = $3,
    version = version + 1,
    updated_at = now(),
    funded_at = CASE WHEN $3 = 'FUNDED' THEN now() ELSE funded_at END,
    completed_at = CASE WHEN $3 = 'COMPLETED' THEN now() ELSE completed_at END,
    failed_at = CASE WHEN $3 = 'FAILED' THEN now() ELSE failed_at END
WHERE id = $1 AND tenant_id = $2
`

type UpdateTransferStatusParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Status   string    `json:"status"`
}

func (q *Queries) UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransferStatus, arg.ID, arg.TenantID, arg.Status)
	return err
}

const updateTransferStatusWithVersion = `-- name: UpdateTransferStatusWithVersion :exec
UPDATE transfers
SET status = $3,
    version = version + 1,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND version = $4
`

type UpdateTransferStatusWithVersionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Status   string    `json:"status"`
	Version  int64     `json:"version"`
}

func (q *Queries) UpdateTransferStatusWithVersion(ctx context.Context, arg UpdateTransferStatusWithVersionParams) error {
	_, err := q.db.Exec(ctx, updateTransferStatusWithVersion,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.Version,
	)
	return err
}
