// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: virtual_accounts.sql

package transferdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const dispenseVirtualAccount = `-- name: DispenseVirtualAccount :one
UPDATE virtual_account_pool
SET available = false, session_id = $3, updated_at = now()
WHERE id = (
    SELECT vap.id FROM virtual_account_pool vap
    WHERE vap.tenant_id = $1 AND vap.currency = $2 AND vap.available = true AND vap.account_type = 'TEMPORARY'
    ORDER BY vap.created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, tenant_id, banking_partner_id, account_number, account_name, sort_code, iban, currency, account_type, available, session_id, created_at, updated_at
`

type DispenseVirtualAccountParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	Currency  string      `json:"currency"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) DispenseVirtualAccount(ctx context.Context, arg DispenseVirtualAccountParams) (VirtualAccountPool, error) {
	row := q.db.QueryRow(ctx, dispenseVirtualAccount, arg.TenantID, arg.Currency, arg.SessionID)
	var i VirtualAccountPool
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BankingPartnerID,
		&i.AccountNumber,
		&i.AccountName,
		&i.SortCode,
		&i.Iban,
		&i.Currency,
		&i.AccountType,
		&i.Available,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVirtualAccountIndexByNumber = `-- name: GetVirtualAccountIndexByNumber :one
SELECT id, account_number, tenant_id, session_id, account_type, created_at FROM virtual_account_index
WHERE account_number = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetVirtualAccountIndexByNumber(ctx context.Context, accountNumber string) (VirtualAccountIndex, error) {
	row := q.db.QueryRow(ctx, getVirtualAccountIndexByNumber, accountNumber)
	var i VirtualAccountIndex
	err := row.Scan(
		&i.ID,
		&i.AccountNumber,
		&i.TenantID,
		&i.SessionID,
		&i.AccountType,
		&i.CreatedAt,
	)
	return i, err
}

const insertVirtualAccount = `-- name: InsertVirtualAccount :one
INSERT INTO virtual_account_pool (
    tenant_id, banking_partner_id, account_number, account_name,
    sort_code, iban, currency, account_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, tenant_id, banking_partner_id, account_number, account_name, sort_code, iban, currency, account_type, available, session_id, created_at, updated_at
`

type InsertVirtualAccountParams struct {
	TenantID         uuid.UUID              `json:"tenant_id"`
	BankingPartnerID uuid.UUID              `json:"banking_partner_id"`
	AccountNumber    string                 `json:"account_number"`
	AccountName      string                 `json:"account_name"`
	SortCode         string                 `json:"sort_code"`
	Iban             string                 `json:"iban"`
	Currency         string                 `json:"currency"`
	AccountType      VirtualAccountTypeEnum `json:"account_type"`
}

func (q *Queries) InsertVirtualAccount(ctx context.Context, arg InsertVirtualAccountParams) (VirtualAccountPool, error) {
	row := q.db.QueryRow(ctx, insertVirtualAccount,
		arg.TenantID,
		arg.BankingPartnerID,
		arg.AccountNumber,
		arg.AccountName,
		arg.SortCode,
		arg.Iban,
		arg.Currency,
		arg.AccountType,
	)
	var i VirtualAccountPool
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BankingPartnerID,
		&i.AccountNumber,
		&i.AccountName,
		&i.SortCode,
		&i.Iban,
		&i.Currency,
		&i.AccountType,
		&i.Available,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVirtualAccountIndex = `-- name: InsertVirtualAccountIndex :one
INSERT INTO virtual_account_index (
    account_number, tenant_id, session_id, account_type
) VALUES (
    $1, $2, $3, $4
) RETURNING id, account_number, tenant_id, session_id, account_type, created_at
`

type InsertVirtualAccountIndexParams struct {
	AccountNumber string                 `json:"account_number"`
	TenantID      uuid.UUID              `json:"tenant_id"`
	SessionID     pgtype.UUID            `json:"session_id"`
	AccountType   VirtualAccountTypeEnum `json:"account_type"`
}

func (q *Queries) InsertVirtualAccountIndex(ctx context.Context, arg InsertVirtualAccountIndexParams) (VirtualAccountIndex, error) {
	row := q.db.QueryRow(ctx, insertVirtualAccountIndex,
		arg.AccountNumber,
		arg.TenantID,
		arg.SessionID,
		arg.AccountType,
	)
	var i VirtualAccountIndex
	err := row.Scan(
		&i.ID,
		&i.AccountNumber,
		&i.TenantID,
		&i.SessionID,
		&i.AccountType,
		&i.CreatedAt,
	)
	return i, err
}

const listVirtualAccountsByTenant = `-- name: ListVirtualAccountsByTenant :many
SELECT id, tenant_id, banking_partner_id, account_number, account_name, sort_code, iban, currency, account_type, available, session_id, created_at, updated_at FROM virtual_account_pool
WHERE tenant_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListVirtualAccountsByTenant(ctx context.Context, tenantID uuid.UUID) ([]VirtualAccountPool, error) {
	rows, err := q.db.Query(ctx, listVirtualAccountsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VirtualAccountPool{}
	for rows.Next() {
		var i VirtualAccountPool
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BankingPartnerID,
			&i.AccountNumber,
			&i.AccountName,
			&i.SortCode,
			&i.Iban,
			&i.Currency,
			&i.AccountType,
			&i.Available,
			&i.SessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recycleVirtualAccount = `-- name: RecycleVirtualAccount :exec
UPDATE virtual_account_pool
SET available = true, session_id = NULL, updated_at = now()
WHERE account_number = $1
`

func (q *Queries) RecycleVirtualAccount(ctx context.Context, accountNumber string) error {
	_, err := q.db.Exec(ctx, recycleVirtualAccount, accountNumber)
	return err
}
