// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook_management.sql

package transferdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWebhookDeliveries = `-- name: CountWebhookDeliveries :one
SELECT COUNT(*)::bigint AS total
FROM webhook_deliveries
WHERE tenant_id = $1
  AND ($2::text = '' OR event_type = $2)
  AND ($3::text = '' OR status = $3)
`

type CountWebhookDeliveriesParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	EventType    string    `json:"event_type"`
	StatusFilter string    `json:"status_filter"`
}

func (q *Queries) CountWebhookDeliveries(ctx context.Context, arg CountWebhookDeliveriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookDeliveries, arg.TenantID, arg.EventType, arg.StatusFilter)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const deleteAllWebhookEventSubscriptions = `-- name: DeleteAllWebhookEventSubscriptions :exec
DELETE FROM webhook_event_subscriptions
WHERE tenant_id = $1
`

func (q *Queries) DeleteAllWebhookEventSubscriptions(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllWebhookEventSubscriptions, tenantID)
	return err
}

const deleteWebhookEventSubscription = `-- name: DeleteWebhookEventSubscription :exec
DELETE FROM webhook_event_subscriptions
WHERE tenant_id = $1 AND event_type = $2
`

type DeleteWebhookEventSubscriptionParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	EventType string    `json:"event_type"`
}

func (q *Queries) DeleteWebhookEventSubscription(ctx context.Context, arg DeleteWebhookEventSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteWebhookEventSubscription, arg.TenantID, arg.EventType)
	return err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, tenant_id, event_type, transfer_id, delivery_id,
       webhook_url, status, status_code, attempt, max_attempts,
       error_message, request_body, duration_ms,
       created_at, delivered_at, next_retry_at
FROM webhook_deliveries
WHERE id = $1 AND tenant_id = $2
`

type GetWebhookDeliveryParams struct {
	DeliveryID uuid.UUID `json:"delivery_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetWebhookDelivery(ctx context.Context, arg GetWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, arg.DeliveryID, arg.TenantID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.TransferID,
		&i.DeliveryID,
		&i.WebhookUrl,
		&i.Status,
		&i.StatusCode,
		&i.Attempt,
		&i.MaxAttempts,
		&i.ErrorMessage,
		&i.RequestBody,
		&i.DurationMs,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.NextRetryAt,
	)
	return i, err
}

const getWebhookDeliveryStats = `-- name: GetWebhookDeliveryStats :one
SELECT
    COUNT(*)::bigint AS total_deliveries,
    COUNT(*) FILTER (WHERE status = 'delivered')::bigint AS successful,
    COUNT(*) FILTER (WHERE status = 'failed')::bigint AS failed,
    COUNT(*) FILTER (WHERE status = 'dead_letter')::bigint AS dead_lettered,
    COUNT(*) FILTER (WHERE status = 'pending')::bigint AS pending,
    COALESCE(AVG(duration_ms) FILTER (WHERE status = 'delivered'), 0)::integer AS avg_latency_ms,
    COALESCE(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY duration_ms) FILTER (WHERE status = 'delivered'), 0)::integer AS p95_latency_ms
FROM webhook_deliveries
WHERE tenant_id = $1
  AND created_at >= $2::timestamptz
`

type GetWebhookDeliveryStatsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Since    time.Time `json:"since"`
}

type GetWebhookDeliveryStatsRow struct {
	TotalDeliveries int64 `json:"total_deliveries"`
	Successful      int64 `json:"successful"`
	Failed          int64 `json:"failed"`
	DeadLettered    int64 `json:"dead_lettered"`
	Pending         int64 `json:"pending"`
	AvgLatencyMs    int32 `json:"avg_latency_ms"`
	P95LatencyMs    int32 `json:"p95_latency_ms"`
}

func (q *Queries) GetWebhookDeliveryStats(ctx context.Context, arg GetWebhookDeliveryStatsParams) (GetWebhookDeliveryStatsRow, error) {
	row := q.db.QueryRow(ctx, getWebhookDeliveryStats, arg.TenantID, arg.Since)
	var i GetWebhookDeliveryStatsRow
	err := row.Scan(
		&i.TotalDeliveries,
		&i.Successful,
		&i.Failed,
		&i.DeadLettered,
		&i.Pending,
		&i.AvgLatencyMs,
		&i.P95LatencyMs,
	)
	return i, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :one
INSERT INTO webhook_deliveries (
    tenant_id, event_type, transfer_id, delivery_id,
    webhook_url, status, status_code, attempt, max_attempts,
    error_message, request_body, duration_ms, delivered_at, next_retry_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14
) RETURNING id, created_at
`

type InsertWebhookDeliveryParams struct {
	TenantID     uuid.UUID          `json:"tenant_id"`
	EventType    string             `json:"event_type"`
	TransferID   pgtype.UUID        `json:"transfer_id"`
	DeliveryID   string             `json:"delivery_id"`
	WebhookUrl   string             `json:"webhook_url"`
	Status       string             `json:"status"`
	StatusCode   pgtype.Int4        `json:"status_code"`
	Attempt      int32              `json:"attempt"`
	MaxAttempts  int32              `json:"max_attempts"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	RequestBody  []byte             `json:"request_body"`
	DurationMs   pgtype.Int4        `json:"duration_ms"`
	DeliveredAt  pgtype.Timestamptz `json:"delivered_at"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
}

type InsertWebhookDeliveryRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (InsertWebhookDeliveryRow, error) {
	row := q.db.QueryRow(ctx, insertWebhookDelivery,
		arg.TenantID,
		arg.EventType,
		arg.TransferID,
		arg.DeliveryID,
		arg.WebhookUrl,
		arg.Status,
		arg.StatusCode,
		arg.Attempt,
		arg.MaxAttempts,
		arg.ErrorMessage,
		arg.RequestBody,
		arg.DurationMs,
		arg.DeliveredAt,
		arg.NextRetryAt,
	)
	var i InsertWebhookDeliveryRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, tenant_id, event_type, transfer_id, delivery_id,
       webhook_url, status, status_code, attempt, max_attempts,
       error_message, duration_ms, created_at, delivered_at
FROM webhook_deliveries
WHERE tenant_id = $1
  AND ($2::text = '' OR event_type = $2)
  AND ($3::text = '' OR status = $3)
ORDER BY created_at DESC
LIMIT $5
OFFSET $4
`

type ListWebhookDeliveriesParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	EventType    string    `json:"event_type"`
	StatusFilter string    `json:"status_filter"`
	PageOffset   int32     `json:"page_offset"`
	PageSize     int32     `json:"page_size"`
}

type ListWebhookDeliveriesRow struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	EventType    string             `json:"event_type"`
	TransferID   pgtype.UUID        `json:"transfer_id"`
	DeliveryID   string             `json:"delivery_id"`
	WebhookUrl   string             `json:"webhook_url"`
	Status       string             `json:"status"`
	StatusCode   pgtype.Int4        `json:"status_code"`
	Attempt      int32              `json:"attempt"`
	MaxAttempts  int32              `json:"max_attempts"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	DurationMs   pgtype.Int4        `json:"duration_ms"`
	CreatedAt    time.Time          `json:"created_at"`
	DeliveredAt  pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]ListWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries,
		arg.TenantID,
		arg.EventType,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhookDeliveriesRow{}
	for rows.Next() {
		var i ListWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.TransferID,
			&i.DeliveryID,
			&i.WebhookUrl,
			&i.Status,
			&i.StatusCode,
			&i.Attempt,
			&i.MaxAttempts,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEventSubscriptions = `-- name: ListWebhookEventSubscriptions :many
SELECT id, tenant_id, event_type, created_at
FROM webhook_event_subscriptions
WHERE tenant_id = $1
ORDER BY event_type
`

func (q *Queries) ListWebhookEventSubscriptions(ctx context.Context, tenantID uuid.UUID) ([]WebhookEventSubscription, error) {
	rows, err := q.db.Query(ctx, listWebhookEventSubscriptions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEventSubscription{}
	for rows.Next() {
		var i WebhookEventSubscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantWebhookEvents = `-- name: UpdateTenantWebhookEvents :exec
UPDATE tenants
SET webhook_events = $1::text[],
    updated_at = now()
WHERE id = $2
`

type UpdateTenantWebhookEventsParams struct {
	Events   []string  `json:"events"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateTenantWebhookEvents(ctx context.Context, arg UpdateTenantWebhookEventsParams) error {
	_, err := q.db.Exec(ctx, updateTenantWebhookEvents, arg.Events, arg.TenantID)
	return err
}

const upsertWebhookEventSubscription = `-- name: UpsertWebhookEventSubscription :one
INSERT INTO webhook_event_subscriptions (tenant_id, event_type)
VALUES ($1, $2)
ON CONFLICT (tenant_id, event_type) DO NOTHING
RETURNING id, tenant_id, event_type, created_at
`

type UpsertWebhookEventSubscriptionParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	EventType string    `json:"event_type"`
}

func (q *Queries) UpsertWebhookEventSubscription(ctx context.Context, arg UpsertWebhookEventSubscriptionParams) (WebhookEventSubscription, error) {
	row := q.db.QueryRow(ctx, upsertWebhookEventSubscription, arg.TenantID, arg.EventType)
	var i WebhookEventSubscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.CreatedAt,
	)
	return i, err
}
