# Enable pprof profiling for performance analysis during load tests.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: settla-server
spec:
  template:
    spec:
      containers:
        - name: settla-server
          ports:
            - containerPort: 6060
              name: pprof
              protocol: TCP
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: settla-server
spec:
  template:
    spec:
      containers:
        - name: settla-server
          ports:
            - containerPort: 6060
              name: pprof
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: settla-server
spec:
  ports:
    - name: pprof
      port: 6060
      targetPort: pprof
      protocol: TCP
