// Package store contains database repository implementations for Settla.
//
// Each bounded context has its own sub-package corresponding to its dedicated
// PostgreSQL database:
//   - store/ledgerdb: ledger journal and account balance repositories
//   - store/transferdb: transfer and settlement repositories
//   - store/treasurydb: position and liquidity repositories
//
// Repository code is generated by SQLC from query definitions in db/queries/
// and augmented with hand-written helpers where needed.
package store
