package main

import (
	"math"
	"math/rand"
	"sort"
)

// ZipfDistribution generates tenant traffic weights following Zipf's law.
// Top 1% of tenants generate ~50% of total traffic, modeling realistic
// fintech platform usage where a few large customers dominate volume.
type ZipfDistribution struct {
	weights []float64 // Normalized weights per tenant index (sum = 1.0)
	cumul   []float64 // Cumulative distribution for sampling
	n       int
	s       float64 // Zipf exponent
}

// NewZipfDistribution creates a Zipf distribution for n tenants.
// The exponent s controls skew: s=1.0 is standard Zipf, s=1.2 gives
// heavier top-tenant concentration (~50% from top 1%).
func NewZipfDistribution(n int, s float64) *ZipfDistribution {
	if n <= 0 {
		n = 1
	}
	if s <= 0 {
		s = 1.2
	}

	weights := make([]float64, n)
	total := 0.0
	for i := 0; i < n; i++ {
		w := 1.0 / math.Pow(float64(i+1), s)
		weights[i] = w
		total += w
	}

	// Normalize to sum=1.0
	cumul := make([]float64, n)
	cumSum := 0.0
	for i := range weights {
		weights[i] /= total
		cumSum += weights[i]
		cumul[i] = cumSum
	}
	// Fix floating point: ensure last entry is exactly 1.0
	cumul[n-1] = 1.0

	return &ZipfDistribution{
		weights: weights,
		cumul:   cumul,
		n:       n,
		s:       s,
	}
}

// Sample returns a tenant index (0-based) drawn from the Zipf distribution.
func (z *ZipfDistribution) Sample() int {
	r := rand.Float64()
	idx := sort.SearchFloat64s(z.cumul, r)
	if idx >= z.n {
		idx = z.n - 1
	}
	return idx
}

// Weight returns the traffic weight for tenant at index i.
func (z *ZipfDistribution) Weight(i int) float64 {
	if i < 0 || i >= z.n {
		return 0
	}
	return z.weights[i]
}

// TopPercentTraffic returns the fraction of total traffic generated by the
// top pct% of tenants. Used for validation: TopPercentTraffic(1) should be ~0.50.
func (z *ZipfDistribution) TopPercentTraffic(pct float64) float64 {
	count := int(math.Ceil(float64(z.n) * pct / 100.0))
	if count > z.n {
		count = z.n
	}
	sum := 0.0
	for i := 0; i < count; i++ {
		sum += z.weights[i]
	}
	return sum
}

// Stats returns distribution statistics for logging.
type ZipfStats struct {
	TenantCount    int
	Exponent       float64
	Top1PctTraffic float64 // Fraction of traffic from top 1%
	Top5PctTraffic float64
	Top10PctTraffic float64
	MaxWeight      float64 // Weight of hottest tenant
	MinWeight      float64 // Weight of coldest tenant
}

// Stats computes distribution statistics.
func (z *ZipfDistribution) Stats() ZipfStats {
	return ZipfStats{
		TenantCount:     z.n,
		Exponent:        z.s,
		Top1PctTraffic:  z.TopPercentTraffic(1),
		Top5PctTraffic:  z.TopPercentTraffic(5),
		Top10PctTraffic: z.TopPercentTraffic(10),
		MaxWeight:       z.weights[0],
		MinWeight:       z.weights[z.n-1],
	}
}
