# Homelab secrets — encrypt with SOPS + age before committing.
#
# To encrypt:  sops -e -i deploy/k8s/overlays/homelab/secrets.yaml
# To decrypt:  sops -d -i deploy/k8s/overlays/homelab/secrets.yaml
# To edit:     sops deploy/k8s/overlays/homelab/secrets.yaml
#
# These mirror the shape of the ExternalSecrets in base/secrets/ so
# workloads can consume the same secretKeyRef selectors.
apiVersion: v1
kind: Secret
metadata:
    name: settla-db-credentials
    labels:
        app.kubernetes.io/name: settla-db-credentials
        app.kubernetes.io/component: secrets
        app.kubernetes.io/part-of: settla
        environment: homelab
type: Opaque
stringData:
    #ENC[AES256_GCM,data:QJPiMIM0DBdxLz9b/+2U+hBE8DS7oOqDO58H7wdwnDf9X1Y+0BBK4QyqchBjEHJo5HkA3+FMJhU/,iv:yqHK2Y7N4syk+s7j1UytB0atC3p/a3yxgRZ1Vu6SSAE=,tag:HmMl/4P7CztzDkhF7Q/p8A==,type:comment]
    #ENC[AES256_GCM,data:9OGKvk+lRwjo2BAEquLNW8P4Gaq1tU/iFyGt9weX9Pus1U6aAd46CE96igATU2b5IFeXrcLdukiCJ+wfaT/MivZ/XE37kh/uTHFbRyPCsDIcsazS/pk=,iv:RHRtAI/obEO4EaSoa4ZhhjepM6vfOYdVl56Zu/6gg38=,tag:9y7tsqMeKi2/c4pQUoIKDw==,type:comment]
    superuser-password: ENC[AES256_GCM,data:NsdFDW3ERHbcLsccRBVl1DGcuGre6PKJvejaDrkpOBKhL3HELpZOlG/USKwZUhxaoHR9DbRTSA8UE3xe1iqI5g==,iv:OKNdOedP4G+Z47UPykfqf7N9KuVM9wYMMHj53U59WDU=,tag:w/mzhQM6r0V4fLrLkbGbxQ==,type:str]
    replication-password: ENC[AES256_GCM,data:ZAV86oazP49EdTJe7bBKELXMvDyJR7qwmHAVcTAXFoejyVWqZeKH5R1SMjJCXmhgoOhmrD4E2i/LnOpIN5k0zQ==,iv:NBvqVT69bBocfNmyG0kQO9RPzso/sRPYzYiOodBO64w=,tag:Gz68ZSt2gOO39osdI2HzwQ==,type:str]
    transfer-password: ENC[AES256_GCM,data:0sUbVNLuGeC9ecmESL6NBrq1nt7zVa18h7jAcaE6YiAze/W+4aElpb2oOEP7EseIGJMqKIqF/NvcZ+wu7YD01A==,iv:Dh0d3hmc86DnU+WZJq5CPwXCCMVFKdo7hnvGJbo2XRI=,tag:npfVj59c/knpUzOtsOSO9w==,type:str]
    ledger-password: ENC[AES256_GCM,data:zazGeBKBZWQIeM+NXGOMsLRo1CNP68cUzMuBeY8qPz1MnfRn0SFwz7FdSR8RvAty3wrmREdKRTdijwXVxWs1Lg==,iv:76Bl00P+Xkym8S6Af58JENDwDnjLIW6SaGQgVvJrDa4=,tag:7xg/WNtbtFU59GcO8EUqtQ==,type:str]
    treasury-password: ENC[AES256_GCM,data:q1x1jWOm5qKL4mhvqZqQFlSCpwWdE6iO/c0zXPpxhZ/QO7nt7Chybd+ZOu6stzRWcNxSXdswrhz0m02xnIkhlQ==,iv:dm/AG2VjoRuS5Vuez8W8P5ZmbbXSrrvKQeXpwl2rhbc=,tag:E3L966ID53LUFNS+nv0n9g==,type:str]
sops:
    age:
        - recipient: age1va8cgqam4s9sfxq75j6ruacuvsr77nnr7u0626maec8g3hpm0ftqsssmsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZTRnSTlVMkJnSWZrR3Rm
            YVJ6b016aXFTR0huNkdiTUl6ZEVtYkc4MlJNCmhIcXVVN3hieGNWTzdvL2pLZXZx
            b09ORFh2amZuQTV4cndpaWVET2dmRHMKLS0tIFJnWDZjYXZid0JZTXNEeHdvamhN
            bDQ1eVN6STR3WTZXVHVTMUJEdGFRM28KpP/JxMXeMqC7ohR0rNUVd8eaAJJ5F3P6
            4ihXZAR21MRmdlabZ+OEG5AO+reGqHXgjogycYLa1kQ6WNFBsGOk/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T22:58:52Z"
    mac: ENC[AES256_GCM,data:6HI6AQq05IrGcuBuHCioLeXC/wtQ16Otxao5qItJQSEr0N53CgMcVRcNTBLV4iCMHwCAq+pEPEPqyMTDCjz12Y3BhDv7V0HaqY7GGzUNF4OEDo/5NUKLIrBzdxq41J6oWFT+/NdyyTnTIsRaZ9o3mk8Le5m31zRfQNOpq0+Er+Q=,iv:cQ52kxROvfbi2Yhf6Kzgks8EDHWzaA4yQtX9ph1ZNug=,tag:6zB9RfDee48FDIijb67Wfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: patroni-credentials
    labels:
        app.kubernetes.io/name: patroni-credentials
        app.kubernetes.io/component: secrets
        app.kubernetes.io/part-of: settla
        environment: homelab
type: Opaque
stringData:
    #ENC[AES256_GCM,data:qvUIG+mjhH547z2kGXhoUhsqHqNSv3N3dvYGbHG4cvt7EX+4RhWX3lHLThD7iblN,iv:3nswUPxUP4kO/xMmzOuJ9eXxxRuk0ZN8gPnhLZ+0/YU=,tag:HNaEUSFMpk/iQRXlLmo9Rw==,type:comment]
    superuser-password: ENC[AES256_GCM,data:moSpC+7jlRAGYxKegFkbDXS0SHehlMuCSMF6u++ba6JERpPIlFdXf2XET9IhjPb0k/zVMswV7AkGR40jLmXriw==,iv:04Kj4QSaQccEZ41+ziFvkIuQ4IMQ+ddUIkyOfIsN2mo=,tag:miJyQ374Pxt3hpAEg0ONJA==,type:str]
    replication-password: ENC[AES256_GCM,data:CwglXrtzOxtNnCeodfqYEE1avhdHRiDMebZQeGGTgpYFYlGFJxq3sHQTwG6u4Gjg778vIHOIGDTYaltuGLDfNw==,iv:Zy3muXUwxL8ix7BF2d9duq3a3xTbKZiM5lEf4D43/9M=,tag:ko2LqPbvL4PALt7Qay7Z7w==,type:str]
    transfer-password: ENC[AES256_GCM,data:BQn5ln+ieWyKhyN3MuZv5U3RnA7A3wG4LGs/Mc+LnGku17Cs+nAKDm7fkxSdeenLUZYyiMD1eG//oRkJO52KWA==,iv:Oe/1G0eSQozOvJTlI8sr8/+Qm5r3ftM6LqGNRXrK4Rs=,tag:ox4s1HaOraNtymwPbpfw6Q==,type:str]
    ledger-password: ENC[AES256_GCM,data:X7Hw6mLuMZass+P3PCpmiHUrLjL+ytm846QVHI8XeCtqxATgnZ7y+ZKeKuPwz3l7xTttkpxxU5UV2aiUgSwsEQ==,iv:0ErDLWDCgCRsSjXlVUokFJ76/y5AJ5Qcqz6zWdG9kRA=,tag:00TaVCqxmUw7iE2cTBHP5Q==,type:str]
    treasury-password: ENC[AES256_GCM,data:oxXo+KYrm/wf6fUTORktG/f3nbVjhQOUCV4gM1i71tOxLQDwvSk1wx2tk/WGIo82unka1L3nUBfXs8Z1knMd/Q==,iv:2l5A5PbzfChckD66jHqAZtW89ROIQkkT8k58KK+KYjo=,tag:tLaMR6o+qyJXsnH+F3wupw==,type:str]
sops:
    age:
        - recipient: age1va8cgqam4s9sfxq75j6ruacuvsr77nnr7u0626maec8g3hpm0ftqsssmsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZTRnSTlVMkJnSWZrR3Rm
            YVJ6b016aXFTR0huNkdiTUl6ZEVtYkc4MlJNCmhIcXVVN3hieGNWTzdvL2pLZXZx
            b09ORFh2amZuQTV4cndpaWVET2dmRHMKLS0tIFJnWDZjYXZid0JZTXNEeHdvamhN
            bDQ1eVN6STR3WTZXVHVTMUJEdGFRM28KpP/JxMXeMqC7ohR0rNUVd8eaAJJ5F3P6
            4ihXZAR21MRmdlabZ+OEG5AO+reGqHXgjogycYLa1kQ6WNFBsGOk/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T22:58:52Z"
    mac: ENC[AES256_GCM,data:6HI6AQq05IrGcuBuHCioLeXC/wtQ16Otxao5qItJQSEr0N53CgMcVRcNTBLV4iCMHwCAq+pEPEPqyMTDCjz12Y3BhDv7V0HaqY7GGzUNF4OEDo/5NUKLIrBzdxq41J6oWFT+/NdyyTnTIsRaZ9o3mk8Le5m31zRfQNOpq0+Er+Q=,iv:cQ52kxROvfbi2Yhf6Kzgks8EDHWzaA4yQtX9ph1ZNug=,tag:6zB9RfDee48FDIijb67Wfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: settla-app-secrets
    labels:
        app.kubernetes.io/name: settla-app-secrets
        app.kubernetes.io/component: secrets
        app.kubernetes.io/part-of: settla
        environment: homelab
type: Opaque
stringData:
    tyk-secret: ENC[AES256_GCM,data:HbuOpPTWGAOgy/PH3Xsvg9hNxsTO/ERT9rOmtyONkmnCTbvz+DLcK7PN6eLTyF9o3GBYDUijWBzKRZXxOfR76w==,iv:ul/Yp4FQDSoUsaCfnnAqR4kee3kGj3FrBeLNTomQG4I=,tag:dBJA2p7ADmebSKrTkoQwNw==,type:str]
    #ENC[AES256_GCM,data:XNQqHF7WCM08s11nP/TTASUVyYPrve1nJ7WRD8uu9aQLiflY,iv:JJ71gMScsuKWRpWHes0JvhzwtlrtPReOP/QYmwGpoA4=,tag:Jmzae698zKgZ9s2YswUzHw==,type:comment]
    wallet-encryption-key: ENC[AES256_GCM,data:fEX9J1oMl2531q+crzCK9qTNVagV01Yb1oE9IajWwCxZF4AevN1eRRzyfguEctnfmCasVQz+uugkowVGCWeekg==,iv:zydvtT/QCSE4h68DJTkqWsdW8EDE9zPXTAKgScOtJHU=,tag:BWUa9yMB1Yspvnzl7KNfkQ==,type:str]
    #ENC[AES256_GCM,data:VrfJ7uWfQTgjkz48ESxpwb9HnmF5eiZ3osCcXe0NiVvy7Iww,iv:3jL7GBsaMTWEbVnYnZiUbL2HvLnjeRq0FUJpOzmtOFg=,tag:/UTT2aLZqFUilFy1xdCjNQ==,type:comment]
    master-seed: ENC[AES256_GCM,data:thGL7YhgI+nazlIL8VAOf/t5iBMQl15ZZaITie0WWs/eGEPmDrarcEMdTj/AOlPy3Ene/BFhN6IRcmYfb/1d+d9j2DHIeQ0vjtiPc08tV+djH6MQ58lmycInwgRsI5OPjxup8DDSJ1xGhq6ebRdsrxyKjYaOSfaRVs1jF1q+N1U=,iv:a36yMfuZbv/qcKdQS4idydVMLKmgoPoz+I2/UzHDCyg=,tag:OuI1F2J7WGSuh1CJAiBm0w==,type:str]
    dashboard-api-key: ""
    tron-api-key: ""
    redis-password: ""
    grafana-admin-password: ENC[AES256_GCM,data:6tfghrTzDkpspFDnnds=,iv:+i7IghQP6AX9q9E8odie/TaAaQAOXI5/vvSJ0q7KWlk=,tag:X8xgzN3uo4QdGlmOeqU2SQ==,type:str]
sops:
    age:
        - recipient: age1va8cgqam4s9sfxq75j6ruacuvsr77nnr7u0626maec8g3hpm0ftqsssmsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZTRnSTlVMkJnSWZrR3Rm
            YVJ6b016aXFTR0huNkdiTUl6ZEVtYkc4MlJNCmhIcXVVN3hieGNWTzdvL2pLZXZx
            b09ORFh2amZuQTV4cndpaWVET2dmRHMKLS0tIFJnWDZjYXZid0JZTXNEeHdvamhN
            bDQ1eVN6STR3WTZXVHVTMUJEdGFRM28KpP/JxMXeMqC7ohR0rNUVd8eaAJJ5F3P6
            4ihXZAR21MRmdlabZ+OEG5AO+reGqHXgjogycYLa1kQ6WNFBsGOk/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T22:58:52Z"
    mac: ENC[AES256_GCM,data:6HI6AQq05IrGcuBuHCioLeXC/wtQ16Otxao5qItJQSEr0N53CgMcVRcNTBLV4iCMHwCAq+pEPEPqyMTDCjz12Y3BhDv7V0HaqY7GGzUNF4OEDo/5NUKLIrBzdxq41J6oWFT+/NdyyTnTIsRaZ9o3mk8Le5m31zRfQNOpq0+Er+Q=,iv:cQ52kxROvfbi2Yhf6Kzgks8EDHWzaA4yQtX9ph1ZNug=,tag:6zB9RfDee48FDIijb67Wfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: settla-webhook-secrets
    labels:
        app.kubernetes.io/name: settla-webhook-secrets
        app.kubernetes.io/component: secrets
        app.kubernetes.io/part-of: settla
        environment: homelab
type: Opaque
stringData:
    lemfi-webhook-secret: ENC[AES256_GCM,data:p4t+I8G5JvOMNSKMSQMLYUhQlJNjN6OfE3m1fhiO+dwe8KEPZ5f00oAz30QHUPwK0jxiOkdIa3gYkanOvjmuEQ==,iv:ZZ9748vaBen+YveYbC/WlNFnM7R/nDVAg0WzJR8i3vI=,tag:q3LkpwYYAJiB6myoNKyQeg==,type:str]
    fincra-webhook-secret: ENC[AES256_GCM,data:mgjTqqS6i9+AB7/oidK3UttqSnDhYin7RasF9HDtZMDfns4ziXkpjbATfOaH0LrV/BaTNV810uHwMYGt4Prpgw==,iv:09yMWnUl4AYkXmPWoGtAGs7dBnsOptOeMqz2dn7ik90=,tag:BpbgE8cSyUtIOXQPWfyGnQ==,type:str]
    paystack-webhook-secret: ENC[AES256_GCM,data:2HvCG7MTHBKiYJcxza+N03/LOXlaQ/9ZtezPTaYk35EVRCCoWKhLHTm+OtXnK7RPtABM8Dbx1g3LMZ8YcekWRw==,iv:IbRc30aJctILg7/uDCHQ7+65QgU6K9FChb6f1EoNm2k=,tag:pSmcvdXJ8ibKukhz73AlrQ==,type:str]
sops:
    age:
        - recipient: age1va8cgqam4s9sfxq75j6ruacuvsr77nnr7u0626maec8g3hpm0ftqsssmsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZTRnSTlVMkJnSWZrR3Rm
            YVJ6b016aXFTR0huNkdiTUl6ZEVtYkc4MlJNCmhIcXVVN3hieGNWTzdvL2pLZXZx
            b09ORFh2amZuQTV4cndpaWVET2dmRHMKLS0tIFJnWDZjYXZid0JZTXNEeHdvamhN
            bDQ1eVN6STR3WTZXVHVTMUJEdGFRM28KpP/JxMXeMqC7ohR0rNUVd8eaAJJ5F3P6
            4ihXZAR21MRmdlabZ+OEG5AO+reGqHXgjogycYLa1kQ6WNFBsGOk/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T22:58:52Z"
    mac: ENC[AES256_GCM,data:6HI6AQq05IrGcuBuHCioLeXC/wtQ16Otxao5qItJQSEr0N53CgMcVRcNTBLV4iCMHwCAq+pEPEPqyMTDCjz12Y3BhDv7V0HaqY7GGzUNF4OEDo/5NUKLIrBzdxq41J6oWFT+/NdyyTnTIsRaZ9o3mk8Le5m31zRfQNOpq0+Er+Q=,iv:cQ52kxROvfbi2Yhf6Kzgks8EDHWzaA4yQtX9ph1ZNug=,tag:6zB9RfDee48FDIijb67Wfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secrets
    labels:
        app.kubernetes.io/name: alertmanager-secrets
        app.kubernetes.io/component: secrets
        app.kubernetes.io/part-of: settla
        environment: homelab
type: Opaque
stringData:
    slack-webhook-url: ENC[AES256_GCM,data:JF+iRR2WNJaWvOhP0L/x6xEuviGTl5IUn46c9gE674Hqxx6Khh5OeLMnRglgRMFX6RDxm0mVIP2SSofir2P3RrbqS3w=,iv:YTaWPVjuWCMEczgMhq7JSLD23nEPBor+8PuP6eeXhus=,tag:oU80ogI13C2gKlXN0CbMmA==,type:str]
    pagerduty-service-key: ENC[AES256_GCM,data:f0OU5WIEdpuLgyaKXtggoKVa3ESPasTYioW+jR6qvnfOak6b1NnKagZUP+vlH2hiahOD6X+GczlKjgReYQBV2w==,iv:GxUZ8oMJ2AagsDvC2f6TIHRMw7Zfp9Gg0uKSW0r9D6I=,tag:+CjMMZmwRneEDG/PHFO0OA==,type:str]
    remediation-webhook-token: ENC[AES256_GCM,data:sXAiSgXZr+v6T9hK8w0PmltegoIR5+/1jEXj0+T7OPkFVZHyX5e1ZOka68wsTJhHpusiJ04g37eCXh0MKXIyBA==,iv:CFzLR1G9mGk/9M9RmLAkGeArvKc5kTV2CL+xVc7bTlo=,tag:NUrgltaKMwaHBSpkNeWYDA==,type:str]
sops:
    age:
        - recipient: age1va8cgqam4s9sfxq75j6ruacuvsr77nnr7u0626maec8g3hpm0ftqsssmsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZTRnSTlVMkJnSWZrR3Rm
            YVJ6b016aXFTR0huNkdiTUl6ZEVtYkc4MlJNCmhIcXVVN3hieGNWTzdvL2pLZXZx
            b09ORFh2amZuQTV4cndpaWVET2dmRHMKLS0tIFJnWDZjYXZid0JZTXNEeHdvamhN
            bDQ1eVN6STR3WTZXVHVTMUJEdGFRM28KpP/JxMXeMqC7ohR0rNUVd8eaAJJ5F3P6
            4ihXZAR21MRmdlabZ+OEG5AO+reGqHXgjogycYLa1kQ6WNFBsGOk/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T22:58:52Z"
    mac: ENC[AES256_GCM,data:6HI6AQq05IrGcuBuHCioLeXC/wtQ16Otxao5qItJQSEr0N53CgMcVRcNTBLV4iCMHwCAq+pEPEPqyMTDCjz12Y3BhDv7V0HaqY7GGzUNF4OEDo/5NUKLIrBzdxq41J6oWFT+/NdyyTnTIsRaZ9o3mk8Le5m31zRfQNOpq0+Er+Q=,iv:cQ52kxROvfbi2Yhf6Kzgks8EDHWzaA4yQtX9ph1ZNug=,tag:6zB9RfDee48FDIijb67Wfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: backup-secrets
    labels:
        app.kubernetes.io/name: backup-secrets
        app.kubernetes.io/component: backup
        app.kubernetes.io/part-of: settla
        environment: homelab
type: Opaque
stringData:
    POSTGRES_TRANSFER_PASSWORD: ENC[AES256_GCM,data:/lpr3eEExSKm1NChfI5+UOh5VxQHjejaCbTwRkk7D/ASyxOMUhN79VTv3Edb9o5ndkIqPaAoOLTakuGpWsMEyA==,iv:kat2B7C3luT9ssx22gWCjZPkkn84LZXbXFuiyKlCB+M=,tag:orB/MAySFcooYQ+T7UeD0g==,type:str]
    POSTGRES_LEDGER_PASSWORD: ENC[AES256_GCM,data:WA1aI9FSy06nxI2i6v9KtUB4nADk0hCNDvdgKAs61yrtKaCJnux5D3TY+zvSQArQqV3DiuxG4ZhOs83t43s8tA==,iv:cUlFDdUTv07Lokw4zoal6tBW8jb0VnpPcF5CBkf5Khc=,tag:LOWEBU0yFa3o4GGIQkLySg==,type:str]
    POSTGRES_TREASURY_PASSWORD: ENC[AES256_GCM,data:0UsCWmvQPAx6cYjaQjakxnRFxP8fkKNqnJ/4EgqzvZy97jAHSJ5dHx/pjsR3KtmTxOLFMjvTbAOKmQSIZf6vpg==,iv:oOlelI0rih4iTkwZa/s0XSJfsngrtKBtdWpG6oKCIz0=,tag:jn8e0PEOw2CkqXZ3ucS6rA==,type:str]
    VERIFY_PG_PASSWORD: ENC[AES256_GCM,data:wwgYFmkoA5I32dOWS8lGiVbIy4kJOcdTzHORQnn76tOpKahfjMaVJDzcvF+VHk/SFsMLmj8a1xCSvyaFg+sTag==,iv:nkdH19X5AwI30gumGUNRIll0ZV1T+2j1pa2FCIVObU4=,tag:lJvKCB2qq25Iekqg0iAR8g==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:/G70aLhEux9cy5287zYevJvOSU85xtLIytMC+WI0c+aidWZLyGNIv2u6/01DUq3qK04okl13SO2DOxQc8gvT1bFEx+A=,iv:9e9X7p5DierKIgXPNs16JK7RTMQlSrhBdDFs+01ivo0=,tag:NGVOgHscXGasN+YD0iwSpg==,type:str]
    PAGERDUTY_ROUTING_KEY: ""
    NATS_CREDS_CONTENT: ""
sops:
    age:
        - recipient: age1va8cgqam4s9sfxq75j6ruacuvsr77nnr7u0626maec8g3hpm0ftqsssmsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZTRnSTlVMkJnSWZrR3Rm
            YVJ6b016aXFTR0huNkdiTUl6ZEVtYkc4MlJNCmhIcXVVN3hieGNWTzdvL2pLZXZx
            b09ORFh2amZuQTV4cndpaWVET2dmRHMKLS0tIFJnWDZjYXZid0JZTXNEeHdvamhN
            bDQ1eVN6STR3WTZXVHVTMUJEdGFRM28KpP/JxMXeMqC7ohR0rNUVd8eaAJJ5F3P6
            4ihXZAR21MRmdlabZ+OEG5AO+reGqHXgjogycYLa1kQ6WNFBsGOk/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T22:58:52Z"
    mac: ENC[AES256_GCM,data:6HI6AQq05IrGcuBuHCioLeXC/wtQ16Otxao5qItJQSEr0N53CgMcVRcNTBLV4iCMHwCAq+pEPEPqyMTDCjz12Y3BhDv7V0HaqY7GGzUNF4OEDo/5NUKLIrBzdxq41J6oWFT+/NdyyTnTIsRaZ9o3mk8Le5m31zRfQNOpq0+Er+Q=,iv:cQ52kxROvfbi2Yhf6Kzgks8EDHWzaA4yQtX9ph1ZNug=,tag:6zB9RfDee48FDIijb67Wfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
