# Staging environment overrides
apiVersion: v1
kind: ConfigMap
metadata:
  name: settla-server-config
data:
  SETTLA_LOG_LEVEL: "info"
  SETTLA_PROVIDER_MODE: "testnet"
  SETTLA_PPROF: "true"
  SETTLA_PPROF_PORT: "6060"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: settla-node-config
data:
  SETTLA_LOG_LEVEL: "info"
  SETTLA_PROVIDER_MODE: "testnet"
  SETTLA_NODE_PARTITIONS: "4"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  SETTLA_LOG_LEVEL: "info"
  SETTLA_GRPC_POOL_SIZE: "20"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-config
data:
  SETTLA_LOG_LEVEL: "info"
