// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package ledgerdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    tenant_id, code, name, type, currency, normal_balance, parent_id, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, tenant_id, code, name, type, currency, normal_balance, parent_id, is_active, metadata, created_at, updated_at
`

type CreateAccountParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	Code          string      `json:"code"`
	Name          string      `json:"name"`
	Type          string      `json:"type"`
	Currency      string      `json:"currency"`
	NormalBalance string      `json:"normal_balance"`
	ParentID      pgtype.UUID `json:"parent_id"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.NormalBalance,
		arg.ParentID,
		arg.Metadata,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.NormalBalance,
		&i.ParentID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEntryLine = `-- name: CreateEntryLine :one
INSERT INTO entry_lines (
    journal_entry_id, account_id, entry_type, amount, currency, description
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, journal_entry_id, account_id, entry_type, amount, currency, description, created_at
`

type CreateEntryLineParams struct {
	JournalEntryID uuid.UUID      `json:"journal_entry_id"`
	AccountID      uuid.UUID      `json:"account_id"`
	EntryType      string         `json:"entry_type"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	Description    pgtype.Text    `json:"description"`
}

func (q *Queries) CreateEntryLine(ctx context.Context, arg CreateEntryLineParams) (EntryLine, error) {
	row := q.db.QueryRow(ctx, createEntryLine,
		arg.JournalEntryID,
		arg.AccountID,
		arg.EntryType,
		arg.Amount,
		arg.Currency,
		arg.Description,
	)
	var i EntryLine
	err := row.Scan(
		&i.ID,
		&i.JournalEntryID,
		&i.AccountID,
		&i.EntryType,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal_entries (
    tenant_id, idempotency_key, effective_date, description,
    reference_type, reference_id, reversal_of, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, tenant_id, idempotency_key, posted_at, effective_date, description, reference_type, reference_id, reversed_by, reversal_of, metadata, created_at
`

type CreateJournalEntryParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	EffectiveDate  pgtype.Date `json:"effective_date"`
	Description    string      `json:"description"`
	ReferenceType  pgtype.Text `json:"reference_type"`
	ReferenceID    pgtype.UUID `json:"reference_id"`
	ReversalOf     pgtype.UUID `json:"reversal_of"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, createJournalEntry,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.EffectiveDate,
		arg.Description,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.ReversalOf,
		arg.Metadata,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.PostedAt,
		&i.EffectiveDate,
		&i.Description,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.ReversedBy,
		&i.ReversalOf,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, tenant_id, code, name, type, currency, normal_balance, parent_id, is_active, metadata, created_at, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.NormalBalance,
		&i.ParentID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByCode = `-- name: GetAccountByCode :one
SELECT id, tenant_id, code, name, type, currency, normal_balance, parent_id, is_active, metadata, created_at, updated_at FROM accounts WHERE code = $1
`

func (q *Queries) GetAccountByCode(ctx context.Context, code string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByCode, code)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.NormalBalance,
		&i.ParentID,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBalanceSnapshot = `-- name: GetBalanceSnapshot :one
SELECT account_id, balance, last_entry_id, version, updated_at FROM balance_snapshots
WHERE account_id = $1
`

func (q *Queries) GetBalanceSnapshot(ctx context.Context, accountID uuid.UUID) (BalanceSnapshot, error) {
	row := q.db.QueryRow(ctx, getBalanceSnapshot, accountID)
	var i BalanceSnapshot
	err := row.Scan(
		&i.AccountID,
		&i.Balance,
		&i.LastEntryID,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const getJournalEntry = `-- name: GetJournalEntry :one
SELECT id, tenant_id, idempotency_key, posted_at, effective_date, description, reference_type, reference_id, reversed_by, reversal_of, metadata, created_at FROM journal_entries
WHERE id = $1 AND posted_at = $2
`

type GetJournalEntryParams struct {
	ID       uuid.UUID `json:"id"`
	PostedAt time.Time `json:"posted_at"`
}

func (q *Queries) GetJournalEntry(ctx context.Context, arg GetJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntry, arg.ID, arg.PostedAt)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.PostedAt,
		&i.EffectiveDate,
		&i.Description,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.ReversedBy,
		&i.ReversalOf,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getJournalEntryByIdempotencyKey = `-- name: GetJournalEntryByIdempotencyKey :one
SELECT id, tenant_id, idempotency_key, posted_at, effective_date, description, reference_type, reference_id, reversed_by, reversal_of, metadata, created_at FROM journal_entries
WHERE idempotency_key = $1
LIMIT 1
`

func (q *Queries) GetJournalEntryByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntryByIdempotencyKey, idempotencyKey)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.PostedAt,
		&i.EffectiveDate,
		&i.Description,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.ReversedBy,
		&i.ReversalOf,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountsByTenant = `-- name: ListAccountsByTenant :many
SELECT id, tenant_id, code, name, type, currency, normal_balance, parent_id, is_active, metadata, created_at, updated_at FROM accounts
WHERE tenant_id = $1
ORDER BY code
`

func (q *Queries) ListAccountsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.NormalBalance,
			&i.ParentID,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAccounts = `-- name: ListAllAccounts :many
SELECT id, tenant_id, code, name, type, currency, normal_balance, parent_id, is_active, metadata, created_at, updated_at FROM accounts
ORDER BY code
`

func (q *Queries) ListAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.NormalBalance,
			&i.ParentID,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBalanceSnapshots = `-- name: ListBalanceSnapshots :many
SELECT bs.account_id, bs.balance, bs.last_entry_id, bs.version, bs.updated_at, a.code, a.currency, a.type, a.tenant_id
FROM balance_snapshots bs
JOIN accounts a ON a.id = bs.account_id
ORDER BY a.code
`

type ListBalanceSnapshotsRow struct {
	AccountID   uuid.UUID      `json:"account_id"`
	Balance     pgtype.Numeric `json:"balance"`
	LastEntryID pgtype.UUID    `json:"last_entry_id"`
	Version     int64          `json:"version"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Code        string         `json:"code"`
	Currency    string         `json:"currency"`
	Type        string         `json:"type"`
	TenantID    pgtype.UUID    `json:"tenant_id"`
}

func (q *Queries) ListBalanceSnapshots(ctx context.Context) ([]ListBalanceSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listBalanceSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBalanceSnapshotsRow{}
	for rows.Next() {
		var i ListBalanceSnapshotsRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Balance,
			&i.LastEntryID,
			&i.Version,
			&i.UpdatedAt,
			&i.Code,
			&i.Currency,
			&i.Type,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBalanceSnapshotsByTenant = `-- name: ListBalanceSnapshotsByTenant :many
SELECT bs.account_id, bs.balance, bs.last_entry_id, bs.version, bs.updated_at, a.code, a.currency, a.type
FROM balance_snapshots bs
JOIN accounts a ON a.id = bs.account_id
WHERE a.tenant_id = $1
ORDER BY a.code
`

type ListBalanceSnapshotsByTenantRow struct {
	AccountID   uuid.UUID      `json:"account_id"`
	Balance     pgtype.Numeric `json:"balance"`
	LastEntryID pgtype.UUID    `json:"last_entry_id"`
	Version     int64          `json:"version"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Code        string         `json:"code"`
	Currency    string         `json:"currency"`
	Type        string         `json:"type"`
}

func (q *Queries) ListBalanceSnapshotsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListBalanceSnapshotsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listBalanceSnapshotsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBalanceSnapshotsByTenantRow{}
	for rows.Next() {
		var i ListBalanceSnapshotsByTenantRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Balance,
			&i.LastEntryID,
			&i.Version,
			&i.UpdatedAt,
			&i.Code,
			&i.Currency,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryLinesByAccount = `-- name: ListEntryLinesByAccount :many
SELECT id, journal_entry_id, account_id, entry_type, amount, currency, description, created_at FROM entry_lines
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEntryLinesByAccountParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListEntryLinesByAccount(ctx context.Context, arg ListEntryLinesByAccountParams) ([]EntryLine, error) {
	rows, err := q.db.Query(ctx, listEntryLinesByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntryLine{}
	for rows.Next() {
		var i EntryLine
		if err := rows.Scan(
			&i.ID,
			&i.JournalEntryID,
			&i.AccountID,
			&i.EntryType,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryLinesByAccountInDateRange = `-- name: ListEntryLinesByAccountInDateRange :many
SELECT id, journal_entry_id, account_id, entry_type, amount, currency, description, created_at FROM entry_lines
WHERE account_id = $1
  AND created_at >= $2
  AND created_at < $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListEntryLinesByAccountInDateRangeParams struct {
	AccountID   uuid.UUID `json:"account_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListEntryLinesByAccountInDateRange(ctx context.Context, arg ListEntryLinesByAccountInDateRangeParams) ([]EntryLine, error) {
	rows, err := q.db.Query(ctx, listEntryLinesByAccountInDateRange,
		arg.AccountID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntryLine{}
	for rows.Next() {
		var i EntryLine
		if err := rows.Scan(
			&i.ID,
			&i.JournalEntryID,
			&i.AccountID,
			&i.EntryType,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryLinesByJournal = `-- name: ListEntryLinesByJournal :many
SELECT id, journal_entry_id, account_id, entry_type, amount, currency, description, created_at FROM entry_lines
WHERE journal_entry_id = $1
ORDER BY created_at
`

func (q *Queries) ListEntryLinesByJournal(ctx context.Context, journalEntryID uuid.UUID) ([]EntryLine, error) {
	rows, err := q.db.Query(ctx, listEntryLinesByJournal, journalEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntryLine{}
	for rows.Next() {
		var i EntryLine
		if err := rows.Scan(
			&i.ID,
			&i.JournalEntryID,
			&i.AccountID,
			&i.EntryType,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntriesByReference = `-- name: ListJournalEntriesByReference :many
SELECT id, tenant_id, idempotency_key, posted_at, effective_date, description, reference_type, reference_id, reversed_by, reversal_of, metadata, created_at FROM journal_entries
WHERE reference_type = $1 AND reference_id = $2
ORDER BY posted_at DESC
`

type ListJournalEntriesByReferenceParams struct {
	ReferenceType pgtype.Text `json:"reference_type"`
	ReferenceID   pgtype.UUID `json:"reference_id"`
}

func (q *Queries) ListJournalEntriesByReference(ctx context.Context, arg ListJournalEntriesByReferenceParams) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, listJournalEntriesByReference, arg.ReferenceType, arg.ReferenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalEntry{}
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.IdempotencyKey,
			&i.PostedAt,
			&i.EffectiveDate,
			&i.Description,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.ReversedBy,
			&i.ReversalOf,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntriesByTenant = `-- name: ListJournalEntriesByTenant :many
SELECT id, tenant_id, idempotency_key, posted_at, effective_date, description, reference_type, reference_id, reversed_by, reversal_of, metadata, created_at FROM journal_entries
WHERE tenant_id = $1
ORDER BY posted_at DESC
LIMIT $2 OFFSET $3
`

type ListJournalEntriesByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListJournalEntriesByTenant(ctx context.Context, arg ListJournalEntriesByTenantParams) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, listJournalEntriesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalEntry{}
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.IdempotencyKey,
			&i.PostedAt,
			&i.EffectiveDate,
			&i.Description,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.ReversedBy,
			&i.ReversalOf,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntriesInDateRange = `-- name: ListJournalEntriesInDateRange :many
SELECT id, tenant_id, idempotency_key, posted_at, effective_date, description, reference_type, reference_id, reversed_by, reversal_of, metadata, created_at FROM journal_entries
WHERE tenant_id = $1
  AND posted_at >= $2
  AND posted_at < $3
ORDER BY posted_at DESC
LIMIT $4 OFFSET $5
`

type ListJournalEntriesInDateRangeParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	PostedAt   time.Time   `json:"posted_at"`
	PostedAt_2 time.Time   `json:"posted_at_2"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListJournalEntriesInDateRange(ctx context.Context, arg ListJournalEntriesInDateRangeParams) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, listJournalEntriesInDateRange,
		arg.TenantID,
		arg.PostedAt,
		arg.PostedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalEntry{}
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.IdempotencyKey,
			&i.PostedAt,
			&i.EffectiveDate,
			&i.Description,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.ReversedBy,
			&i.ReversalOf,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemAccounts = `-- name: ListSystemAccounts :many
SELECT id, tenant_id, code, name, type, currency, normal_balance, parent_id, is_active, metadata, created_at, updated_at FROM accounts
WHERE tenant_id IS NULL
ORDER BY code
`

func (q *Queries) ListSystemAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listSystemAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.NormalBalance,
			&i.ParentID,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBalanceSnapshot = `-- name: UpsertBalanceSnapshot :one
INSERT INTO balance_snapshots (
    account_id, balance, last_entry_id, version
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (account_id) DO UPDATE SET
    balance = EXCLUDED.balance,
    last_entry_id = EXCLUDED.last_entry_id,
    version = EXCLUDED.version,
    updated_at = now()
RETURNING account_id, balance, last_entry_id, version, updated_at
`

type UpsertBalanceSnapshotParams struct {
	AccountID   uuid.UUID      `json:"account_id"`
	Balance     pgtype.Numeric `json:"balance"`
	LastEntryID pgtype.UUID    `json:"last_entry_id"`
	Version     int64          `json:"version"`
}

func (q *Queries) UpsertBalanceSnapshot(ctx context.Context, arg UpsertBalanceSnapshotParams) (BalanceSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertBalanceSnapshot,
		arg.AccountID,
		arg.Balance,
		arg.LastEntryID,
		arg.Version,
	)
	var i BalanceSnapshot
	err := row.Scan(
		&i.AccountID,
		&i.Balance,
		&i.LastEntryID,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
