// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ledgerdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            uuid.UUID   `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Code          string      `json:"code"`
	Name          string      `json:"name"`
	Type          string      `json:"type"`
	Currency      string      `json:"currency"`
	NormalBalance string      `json:"normal_balance"`
	ParentID      pgtype.UUID `json:"parent_id"`
	IsActive      bool        `json:"is_active"`
	Metadata      []byte      `json:"metadata"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type BalanceSnapshot struct {
	AccountID   uuid.UUID      `json:"account_id"`
	Balance     pgtype.Numeric `json:"balance"`
	LastEntryID pgtype.UUID    `json:"last_entry_id"`
	Version     int64          `json:"version"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type EntryLine struct {
	ID             uuid.UUID      `json:"id"`
	JournalEntryID uuid.UUID      `json:"journal_entry_id"`
	AccountID      uuid.UUID      `json:"account_id"`
	EntryType      string         `json:"entry_type"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	Description    pgtype.Text    `json:"description"`
	CreatedAt      time.Time      `json:"created_at"`
}

type EntryLinesDefault struct {
	ID             uuid.UUID      `json:"id"`
	JournalEntryID uuid.UUID      `json:"journal_entry_id"`
	AccountID      uuid.UUID      `json:"account_id"`
	EntryType      string         `json:"entry_type"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	Description    pgtype.Text    `json:"description"`
	CreatedAt      time.Time      `json:"created_at"`
}

type EntryLinesY2026m03 struct {
	ID             uuid.UUID      `json:"id"`
	JournalEntryID uuid.UUID      `json:"journal_entry_id"`
	AccountID      uuid.UUID      `json:"account_id"`
	EntryType      string         `json:"entry_type"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	Description    pgtype.Text    `json:"description"`
	CreatedAt      time.Time      `json:"created_at"`
}

type EntryLinesY2026m04 struct {
	ID             uuid.UUID      `json:"id"`
	JournalEntryID uuid.UUID      `json:"journal_entry_id"`
	AccountID      uuid.UUID      `json:"account_id"`
	EntryType      string         `json:"entry_type"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	Description    pgtype.Text    `json:"description"`
	CreatedAt      time.Time      `json:"created_at"`
}

type EntryLinesY2026m05 struct {
	ID             uuid.UUID      `json:"id"`
	JournalEntryID uuid.UUID      `json:"journal_entry_id"`
	AccountID      uuid.UUID      `json:"account_id"`
	EntryType      string         `json:"entry_type"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	Description    pgtype.Text    `json:"description"`
	CreatedAt      time.Time      `json:"created_at"`
}

type EntryLinesY2026m06 struct {
	ID             uuid.UUID      `json:"id"`
	JournalEntryID uuid.UUID      `json:"journal_entry_id"`
	AccountID      uuid.UUID      `json:"account_id"`
	EntryType      string         `json:"entry_type"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	Description    pgtype.Text    `json:"description"`
	CreatedAt      time.Time      `json:"created_at"`
}

type EntryLinesY2026m07 struct {
	ID             uuid.UUID      `json:"id"`
	JournalEntryID uuid.UUID      `json:"journal_entry_id"`
	AccountID      uuid.UUID      `json:"account_id"`
	EntryType      string         `json:"entry_type"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	Description    pgtype.Text    `json:"description"`
	CreatedAt      time.Time      `json:"created_at"`
}

type EntryLinesY2026m08 struct {
	ID             uuid.UUID      `json:"id"`
	JournalEntryID uuid.UUID      `json:"journal_entry_id"`
	AccountID      uuid.UUID      `json:"account_id"`
	EntryType      string         `json:"entry_type"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	Description    pgtype.Text    `json:"description"`
	CreatedAt      time.Time      `json:"created_at"`
}

type JournalEntriesDefault struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	PostedAt       time.Time   `json:"posted_at"`
	EffectiveDate  pgtype.Date `json:"effective_date"`
	Description    string      `json:"description"`
	ReferenceType  pgtype.Text `json:"reference_type"`
	ReferenceID    pgtype.UUID `json:"reference_id"`
	ReversedBy     pgtype.UUID `json:"reversed_by"`
	ReversalOf     pgtype.UUID `json:"reversal_of"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}

type JournalEntriesY2026m03 struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	PostedAt       time.Time   `json:"posted_at"`
	EffectiveDate  pgtype.Date `json:"effective_date"`
	Description    string      `json:"description"`
	ReferenceType  pgtype.Text `json:"reference_type"`
	ReferenceID    pgtype.UUID `json:"reference_id"`
	ReversedBy     pgtype.UUID `json:"reversed_by"`
	ReversalOf     pgtype.UUID `json:"reversal_of"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}

type JournalEntriesY2026m04 struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	PostedAt       time.Time   `json:"posted_at"`
	EffectiveDate  pgtype.Date `json:"effective_date"`
	Description    string      `json:"description"`
	ReferenceType  pgtype.Text `json:"reference_type"`
	ReferenceID    pgtype.UUID `json:"reference_id"`
	ReversedBy     pgtype.UUID `json:"reversed_by"`
	ReversalOf     pgtype.UUID `json:"reversal_of"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}

type JournalEntriesY2026m05 struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	PostedAt       time.Time   `json:"posted_at"`
	EffectiveDate  pgtype.Date `json:"effective_date"`
	Description    string      `json:"description"`
	ReferenceType  pgtype.Text `json:"reference_type"`
	ReferenceID    pgtype.UUID `json:"reference_id"`
	ReversedBy     pgtype.UUID `json:"reversed_by"`
	ReversalOf     pgtype.UUID `json:"reversal_of"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}

type JournalEntriesY2026m06 struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	PostedAt       time.Time   `json:"posted_at"`
	EffectiveDate  pgtype.Date `json:"effective_date"`
	Description    string      `json:"description"`
	ReferenceType  pgtype.Text `json:"reference_type"`
	ReferenceID    pgtype.UUID `json:"reference_id"`
	ReversedBy     pgtype.UUID `json:"reversed_by"`
	ReversalOf     pgtype.UUID `json:"reversal_of"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}

type JournalEntriesY2026m07 struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	PostedAt       time.Time   `json:"posted_at"`
	EffectiveDate  pgtype.Date `json:"effective_date"`
	Description    string      `json:"description"`
	ReferenceType  pgtype.Text `json:"reference_type"`
	ReferenceID    pgtype.UUID `json:"reference_id"`
	ReversedBy     pgtype.UUID `json:"reversed_by"`
	ReversalOf     pgtype.UUID `json:"reversal_of"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}

type JournalEntriesY2026m08 struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	PostedAt       time.Time   `json:"posted_at"`
	EffectiveDate  pgtype.Date `json:"effective_date"`
	Description    string      `json:"description"`
	ReferenceType  pgtype.Text `json:"reference_type"`
	ReferenceID    pgtype.UUID `json:"reference_id"`
	ReversedBy     pgtype.UUID `json:"reversed_by"`
	ReversalOf     pgtype.UUID `json:"reversal_of"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}

type JournalEntry struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	PostedAt       time.Time   `json:"posted_at"`
	EffectiveDate  pgtype.Date `json:"effective_date"`
	Description    string      `json:"description"`
	ReferenceType  pgtype.Text `json:"reference_type"`
	ReferenceID    pgtype.UUID `json:"reference_id"`
	ReversedBy     pgtype.UUID `json:"reversed_by"`
	ReversalOf     pgtype.UUID `json:"reversal_of"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}
