// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ledgerdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntryLine(ctx context.Context, arg CreateEntryLineParams) (EntryLine, error)
	CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error)
	GetAccount(ctx context.Context, id uuid.UUID) (Account, error)
	// Get balance for an account by its code from balance_snapshots.
	// Returns NULL if no snapshot exists yet (handled as zero by caller).
	GetAccountBalanceByCode(ctx context.Context, code string) (pgtype.Numeric, error)
	GetAccountByCode(ctx context.Context, code string) (Account, error)
	GetBalanceSnapshot(ctx context.Context, accountID uuid.UUID) (BalanceSnapshot, error)
	GetJournalEntry(ctx context.Context, arg GetJournalEntryParams) (JournalEntry, error)
	GetJournalEntryByIdempotencyKey(ctx context.Context, arg GetJournalEntryByIdempotencyKeyParams) (JournalEntry, error)
	ListAccountsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Account, error)
	ListAllAccounts(ctx context.Context) ([]Account, error)
	ListBalanceSnapshots(ctx context.Context) ([]ListBalanceSnapshotsRow, error)
	ListBalanceSnapshotsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListBalanceSnapshotsByTenantRow, error)
	ListEntryLinesByAccount(ctx context.Context, arg ListEntryLinesByAccountParams) ([]EntryLine, error)
	ListEntryLinesByAccountInDateRange(ctx context.Context, arg ListEntryLinesByAccountInDateRangeParams) ([]EntryLine, error)
	ListEntryLinesByJournal(ctx context.Context, journalEntryID uuid.UUID) ([]EntryLine, error)
	ListJournalEntriesByReference(ctx context.Context, arg ListJournalEntriesByReferenceParams) ([]JournalEntry, error)
	ListJournalEntriesByTenant(ctx context.Context, arg ListJournalEntriesByTenantParams) ([]JournalEntry, error)
	ListJournalEntriesInDateRange(ctx context.Context, arg ListJournalEntriesInDateRangeParams) ([]JournalEntry, error)
	ListSystemAccounts(ctx context.Context) ([]Account, error)
	UpsertBalanceSnapshot(ctx context.Context, arg UpsertBalanceSnapshotParams) (BalanceSnapshot, error)
}

var _ Querier = (*Queries)(nil)
