// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package treasurydb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Position struct {
	ID            uuid.UUID      `json:"id"`
	TenantID      uuid.UUID      `json:"tenant_id"`
	Currency      string         `json:"currency"`
	Location      string         `json:"location"`
	Balance       pgtype.Numeric `json:"balance"`
	Locked        pgtype.Numeric `json:"locked"`
	MinBalance    pgtype.Numeric `json:"min_balance"`
	TargetBalance pgtype.Numeric `json:"target_balance"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type PositionHistory struct {
	ID          uuid.UUID      `json:"id"`
	PositionID  uuid.UUID      `json:"position_id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Balance     pgtype.Numeric `json:"balance"`
	Locked      pgtype.Numeric `json:"locked"`
	TriggerType pgtype.Text    `json:"trigger_type"`
	TriggerRef  pgtype.UUID    `json:"trigger_ref"`
	RecordedAt  time.Time      `json:"recorded_at"`
}

type PositionHistory202603 struct {
	ID          uuid.UUID      `json:"id"`
	PositionID  uuid.UUID      `json:"position_id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Balance     pgtype.Numeric `json:"balance"`
	Locked      pgtype.Numeric `json:"locked"`
	TriggerType pgtype.Text    `json:"trigger_type"`
	TriggerRef  pgtype.UUID    `json:"trigger_ref"`
	RecordedAt  time.Time      `json:"recorded_at"`
}

type PositionHistory202604 struct {
	ID          uuid.UUID      `json:"id"`
	PositionID  uuid.UUID      `json:"position_id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Balance     pgtype.Numeric `json:"balance"`
	Locked      pgtype.Numeric `json:"locked"`
	TriggerType pgtype.Text    `json:"trigger_type"`
	TriggerRef  pgtype.UUID    `json:"trigger_ref"`
	RecordedAt  time.Time      `json:"recorded_at"`
}

type PositionHistory202605 struct {
	ID          uuid.UUID      `json:"id"`
	PositionID  uuid.UUID      `json:"position_id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Balance     pgtype.Numeric `json:"balance"`
	Locked      pgtype.Numeric `json:"locked"`
	TriggerType pgtype.Text    `json:"trigger_type"`
	TriggerRef  pgtype.UUID    `json:"trigger_ref"`
	RecordedAt  time.Time      `json:"recorded_at"`
}

type PositionHistory202606 struct {
	ID          uuid.UUID      `json:"id"`
	PositionID  uuid.UUID      `json:"position_id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Balance     pgtype.Numeric `json:"balance"`
	Locked      pgtype.Numeric `json:"locked"`
	TriggerType pgtype.Text    `json:"trigger_type"`
	TriggerRef  pgtype.UUID    `json:"trigger_ref"`
	RecordedAt  time.Time      `json:"recorded_at"`
}

type PositionHistory202607 struct {
	ID          uuid.UUID      `json:"id"`
	PositionID  uuid.UUID      `json:"position_id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Balance     pgtype.Numeric `json:"balance"`
	Locked      pgtype.Numeric `json:"locked"`
	TriggerType pgtype.Text    `json:"trigger_type"`
	TriggerRef  pgtype.UUID    `json:"trigger_ref"`
	RecordedAt  time.Time      `json:"recorded_at"`
}

type PositionHistory202608 struct {
	ID          uuid.UUID      `json:"id"`
	PositionID  uuid.UUID      `json:"position_id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Balance     pgtype.Numeric `json:"balance"`
	Locked      pgtype.Numeric `json:"locked"`
	TriggerType pgtype.Text    `json:"trigger_type"`
	TriggerRef  pgtype.UUID    `json:"trigger_ref"`
	RecordedAt  time.Time      `json:"recorded_at"`
}

type PositionHistoryDefault struct {
	ID          uuid.UUID      `json:"id"`
	PositionID  uuid.UUID      `json:"position_id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Balance     pgtype.Numeric `json:"balance"`
	Locked      pgtype.Numeric `json:"locked"`
	TriggerType pgtype.Text    `json:"trigger_type"`
	TriggerRef  pgtype.UUID    `json:"trigger_ref"`
	RecordedAt  time.Time      `json:"recorded_at"`
}

type ReserveOp struct {
	ID        uuid.UUID      `json:"id"`
	TenantID  uuid.UUID      `json:"tenant_id"`
	Currency  string         `json:"currency"`
	Location  string         `json:"location"`
	Amount    pgtype.Numeric `json:"amount"`
	Reference uuid.UUID      `json:"reference"`
	OpType    string         `json:"op_type"`
	Completed bool           `json:"completed"`
	CreatedAt time.Time      `json:"created_at"`
}
