// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reserve_ops.sql

package treasurydb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupCompletedReserveOps = `-- name: CleanupCompletedReserveOps :exec
DELETE FROM reserve_ops r
WHERE r.created_at < $1
  AND (
      r.op_type IN ('commit', 'release', 'consume')
      OR EXISTS (
          SELECT 1 FROM reserve_ops c
          WHERE c.reference = r.reference
            AND c.op_type IN ('commit', 'release', 'consume')
      )
  )
`

func (q *Queries) CleanupCompletedReserveOps(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, cleanupCompletedReserveOps, createdAt)
	return err
}

const getUncommittedReserveOps = `-- name: GetUncommittedReserveOps :many
SELECT r.id, r.tenant_id, r.currency, r.location, r.amount, r.reference, r.op_type, r.created_at
FROM reserve_ops r
WHERE r.op_type = 'reserve'
  AND NOT EXISTS (
      SELECT 1 FROM reserve_ops c
      WHERE c.reference = r.reference
        AND c.op_type IN ('commit', 'release', 'consume')
  )
ORDER BY r.created_at ASC
`

type GetUncommittedReserveOpsRow struct {
	ID        uuid.UUID      `json:"id"`
	TenantID  uuid.UUID      `json:"tenant_id"`
	Currency  string         `json:"currency"`
	Location  string         `json:"location"`
	Amount    pgtype.Numeric `json:"amount"`
	Reference uuid.UUID      `json:"reference"`
	OpType    string         `json:"op_type"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) GetUncommittedReserveOps(ctx context.Context) ([]GetUncommittedReserveOpsRow, error) {
	rows, err := q.db.Query(ctx, getUncommittedReserveOps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUncommittedReserveOpsRow{}
	for rows.Next() {
		var i GetUncommittedReserveOpsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Currency,
			&i.Location,
			&i.Amount,
			&i.Reference,
			&i.OpType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReserveOp = `-- name: InsertReserveOp :exec
INSERT INTO reserve_ops (id, tenant_id, currency, location, amount, reference, op_type, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT DO NOTHING
`

type InsertReserveOpParams struct {
	ID        uuid.UUID      `json:"id"`
	TenantID  uuid.UUID      `json:"tenant_id"`
	Currency  string         `json:"currency"`
	Location  string         `json:"location"`
	Amount    pgtype.Numeric `json:"amount"`
	Reference uuid.UUID      `json:"reference"`
	OpType    string         `json:"op_type"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) InsertReserveOp(ctx context.Context, arg InsertReserveOpParams) error {
	_, err := q.db.Exec(ctx, insertReserveOp,
		arg.ID,
		arg.TenantID,
		arg.Currency,
		arg.Location,
		arg.Amount,
		arg.Reference,
		arg.OpType,
		arg.CreatedAt,
	)
	return err
}

const markReserveOpCompleted = `-- name: MarkReserveOpCompleted :exec
UPDATE reserve_ops SET completed = true WHERE id = $1
`

func (q *Queries) MarkReserveOpCompleted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markReserveOpCompleted, id)
	return err
}
