// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: treasury.sql

package treasurydb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const batchUpdatePositions = `-- name: BatchUpdatePositions :exec
UPDATE positions
SET balance = $2, locked = $3, updated_at = now()
WHERE id = $1
`

type BatchUpdatePositionsParams struct {
	ID      uuid.UUID      `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
	Locked  pgtype.Numeric `json:"locked"`
}

func (q *Queries) BatchUpdatePositions(ctx context.Context, arg BatchUpdatePositionsParams) error {
	_, err := q.db.Exec(ctx, batchUpdatePositions, arg.ID, arg.Balance, arg.Locked)
	return err
}

const createPositionHistory = `-- name: CreatePositionHistory :one
INSERT INTO position_history (
    position_id, tenant_id, balance, locked,
    trigger_type, trigger_ref
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, position_id, tenant_id, balance, locked, trigger_type, trigger_ref, recorded_at
`

type CreatePositionHistoryParams struct {
	PositionID  uuid.UUID      `json:"position_id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Balance     pgtype.Numeric `json:"balance"`
	Locked      pgtype.Numeric `json:"locked"`
	TriggerType pgtype.Text    `json:"trigger_type"`
	TriggerRef  pgtype.UUID    `json:"trigger_ref"`
}

func (q *Queries) CreatePositionHistory(ctx context.Context, arg CreatePositionHistoryParams) (PositionHistory, error) {
	row := q.db.QueryRow(ctx, createPositionHistory,
		arg.PositionID,
		arg.TenantID,
		arg.Balance,
		arg.Locked,
		arg.TriggerType,
		arg.TriggerRef,
	)
	var i PositionHistory
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.TenantID,
		&i.Balance,
		&i.Locked,
		&i.TriggerType,
		&i.TriggerRef,
		&i.RecordedAt,
	)
	return i, err
}

const deletePosition = `-- name: DeletePosition :exec
DELETE FROM positions WHERE id = $1
`

func (q *Queries) DeletePosition(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePosition, id)
	return err
}

const getPosition = `-- name: GetPosition :one
SELECT id, tenant_id, currency, location, balance, locked, min_balance, target_balance, updated_at FROM positions
WHERE tenant_id = $1 AND currency = $2 AND location = $3
`

type GetPositionParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Currency string    `json:"currency"`
	Location string    `json:"location"`
}

func (q *Queries) GetPosition(ctx context.Context, arg GetPositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, getPosition, arg.TenantID, arg.Currency, arg.Location)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Currency,
		&i.Location,
		&i.Balance,
		&i.Locked,
		&i.MinBalance,
		&i.TargetBalance,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPositions = `-- name: ListAllPositions :many
SELECT id, tenant_id, currency, location, balance, locked, min_balance, target_balance, updated_at FROM positions
ORDER BY tenant_id, currency, location
`

func (q *Queries) ListAllPositions(ctx context.Context) ([]Position, error) {
	rows, err := q.db.Query(ctx, listAllPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Currency,
			&i.Location,
			&i.Balance,
			&i.Locked,
			&i.MinBalance,
			&i.TargetBalance,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionHistory = `-- name: ListPositionHistory :many
SELECT id, position_id, tenant_id, balance, locked, trigger_type, trigger_ref, recorded_at FROM position_history
WHERE tenant_id = $1 AND position_id = $2
ORDER BY recorded_at DESC
LIMIT $3 OFFSET $4
`

type ListPositionHistoryParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	PositionID uuid.UUID `json:"position_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListPositionHistory(ctx context.Context, arg ListPositionHistoryParams) ([]PositionHistory, error) {
	rows, err := q.db.Query(ctx, listPositionHistory,
		arg.TenantID,
		arg.PositionID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PositionHistory{}
	for rows.Next() {
		var i PositionHistory
		if err := rows.Scan(
			&i.ID,
			&i.PositionID,
			&i.TenantID,
			&i.Balance,
			&i.Locked,
			&i.TriggerType,
			&i.TriggerRef,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionHistoryInDateRange = `-- name: ListPositionHistoryInDateRange :many
SELECT id, position_id, tenant_id, balance, locked, trigger_type, trigger_ref, recorded_at FROM position_history
WHERE tenant_id = $1
  AND recorded_at >= $2
  AND recorded_at < $3
ORDER BY recorded_at DESC
LIMIT $4 OFFSET $5
`

type ListPositionHistoryInDateRangeParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	RecordedAt   time.Time `json:"recorded_at"`
	RecordedAt_2 time.Time `json:"recorded_at_2"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListPositionHistoryInDateRange(ctx context.Context, arg ListPositionHistoryInDateRangeParams) ([]PositionHistory, error) {
	rows, err := q.db.Query(ctx, listPositionHistoryInDateRange,
		arg.TenantID,
		arg.RecordedAt,
		arg.RecordedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PositionHistory{}
	for rows.Next() {
		var i PositionHistory
		if err := rows.Scan(
			&i.ID,
			&i.PositionID,
			&i.TenantID,
			&i.Balance,
			&i.Locked,
			&i.TriggerType,
			&i.TriggerRef,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionsByTenant = `-- name: ListPositionsByTenant :many
SELECT id, tenant_id, currency, location, balance, locked, min_balance, target_balance, updated_at FROM positions
WHERE tenant_id = $1
ORDER BY currency, location
`

func (q *Queries) ListPositionsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositionsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Currency,
			&i.Location,
			&i.Balance,
			&i.Locked,
			&i.MinBalance,
			&i.TargetBalance,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionsPaginated = `-- name: ListPositionsPaginated :many
SELECT id, tenant_id, currency, location, balance, locked, min_balance, target_balance, updated_at FROM positions
ORDER BY tenant_id, currency, location
LIMIT $1 OFFSET $2
`

type ListPositionsPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPositionsPaginated(ctx context.Context, arg ListPositionsPaginatedParams) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositionsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Currency,
			&i.Location,
			&i.Balance,
			&i.Locked,
			&i.MinBalance,
			&i.TargetBalance,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePositionBalances = `-- name: UpdatePositionBalances :exec
UPDATE positions
SET balance = $2, locked = $3, updated_at = now()
WHERE id = $1
`

type UpdatePositionBalancesParams struct {
	ID      uuid.UUID      `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
	Locked  pgtype.Numeric `json:"locked"`
}

func (q *Queries) UpdatePositionBalances(ctx context.Context, arg UpdatePositionBalancesParams) error {
	_, err := q.db.Exec(ctx, updatePositionBalances, arg.ID, arg.Balance, arg.Locked)
	return err
}

const upsertPosition = `-- name: UpsertPosition :one
INSERT INTO positions (
    tenant_id, currency, location, balance, locked, min_balance, target_balance
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (tenant_id, currency, location) DO UPDATE SET
    balance = EXCLUDED.balance,
    locked = EXCLUDED.locked,
    min_balance = EXCLUDED.min_balance,
    target_balance = EXCLUDED.target_balance,
    updated_at = now()
RETURNING id, tenant_id, currency, location, balance, locked, min_balance, target_balance, updated_at
`

type UpsertPositionParams struct {
	TenantID      uuid.UUID      `json:"tenant_id"`
	Currency      string         `json:"currency"`
	Location      string         `json:"location"`
	Balance       pgtype.Numeric `json:"balance"`
	Locked        pgtype.Numeric `json:"locked"`
	MinBalance    pgtype.Numeric `json:"min_balance"`
	TargetBalance pgtype.Numeric `json:"target_balance"`
}

func (q *Queries) UpsertPosition(ctx context.Context, arg UpsertPositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, upsertPosition,
		arg.TenantID,
		arg.Currency,
		arg.Location,
		arg.Balance,
		arg.Locked,
		arg.MinBalance,
		arg.TargetBalance,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Currency,
		&i.Location,
		&i.Balance,
		&i.Locked,
		&i.MinBalance,
		&i.TargetBalance,
		&i.UpdatedAt,
	)
	return i, err
}
