#!/bin/bash
set -euo pipefail

echo "=== Settla Testnet Wallet Funding Guide ==="
echo ""
echo "Start the server first to generate wallet addresses:"
echo "  SETTLA_PROVIDER_MODE=testnet go run ./cmd/settla-server/..."
echo ""
echo "Then check the logs for lines like:"
echo '  registered system wallet chain=base address=0x...'
echo '  registered system wallet chain=tron address=T...'
echo '  registered system wallet chain=solana address=...'
echo '  registered system wallet chain=ethereum address=0x...'
echo ""
echo "=== Base Sepolia (recommended for demos — fastest confirmations) ==="
echo "  1. ETH (gas): https://www.alchemy.com/faucets/base-sepolia"
echo "     - Paste your Base address (0x...), request 0.5 ETH"
echo "  2. USDC (test tokens): https://faucet.circle.com/"
echo "     - Select 'Base Sepolia', paste address, mint USDC"
echo "  3. Verify: https://sepolia.basescan.org/address/<YOUR_ADDRESS>"
echo ""
echo "=== Tron Nile ==="
echo "  1. TRX (gas/energy): https://nileex.io/join/getJoinPage"
echo "     - Paste your Tron address (T...), request 1000 TRX"
echo "  2. USDT: Check if mintable at contract TXLAQ63Xg1NAzckPwKHvzw7CSEmLMEqcdj"
echo "     - If unavailable, see docs/TESTNET_INTEGRATION_PLAN.md Appendix B"
echo "  3. Verify: https://nile.tronscan.org/#/address/<YOUR_ADDRESS>"
echo ""
echo "=== Solana Devnet ==="
echo "  1. SOL (gas): solana airdrop 2 <ADDRESS> --url devnet"
echo "     - Or visit https://faucet.solana.com"
echo "  2. USDC (test tokens): https://faucet.circle.com/"
echo "     - Select 'Solana Devnet', paste address, mint USDC"
echo "  3. Verify: https://explorer.solana.com/address/<ADDRESS>?cluster=devnet"
echo ""
echo "=== Ethereum Sepolia ==="
echo "  1. ETH (gas): https://www.alchemy.com/faucets/ethereum-sepolia"
echo "     - Paste your Ethereum address (0x...), request 0.5 ETH"
echo "  2. USDC (test tokens): https://faucet.circle.com/"
echo "     - Select 'Ethereum Sepolia', paste address, mint USDC"
echo "  3. Verify: https://sepolia.etherscan.io/address/<YOUR_ADDRESS>"
echo ""
echo "=== Pre-Demo Checklist ==="
echo "  [ ] Base wallet has >= 0.1 ETH and >= 100 USDC"
echo "  [ ] Tron wallet has >= 500 TRX and >= 100 USDT"
echo "  [ ] Solana wallet has >= 2 SOL and >= 100 USDC"
echo "  [ ] All balances verified on block explorers"
