#!/usr/bin/env bash
# generate-report.sh — Generates a benchmark report combining Go benchmarks,
# load test results, and outbox/worker latency metrics.
#
# Usage: bash scripts/generate-report.sh
#        make report
set -euo pipefail

REPORT_DIR="tests/reports"
DATE=$(date +%Y-%m-%d)
REPORT_FILE="${REPORT_DIR}/benchmark-report-${DATE}.md"
BENCH_FILE="bench-results.txt"
GATEWAY_PORT="${SETTLA_GATEWAY_PORT:-3100}"
GATEWAY_URL="http://localhost:${GATEWAY_PORT}"

mkdir -p "${REPORT_DIR}"

echo "Generating benchmark report → ${REPORT_FILE}"
echo ""

# ── Section helper ────────────────────────────────────────────────────────
section() {
  echo "## $1" >> "${REPORT_FILE}"
  echo "" >> "${REPORT_FILE}"
}

# ── Header ────────────────────────────────────────────────────────────────
cat > "${REPORT_FILE}" <<HEADER
# Settla Benchmark Report — ${DATE}

## Executive Summary

Generated by \`make report\` on $(date -u '+%Y-%m-%d %H:%M UTC').

| Metric | Target | Status |
|--------|--------|--------|
| Sustained TPS | 580 TPS | — |
| Peak TPS | 3,000–5,000 TPS | — |
| Ledger writes/sec peak | 15,000–25,000 | — |
| Gateway auth lookup | <1μs (L1) | — |
| Treasury reserve latency | <10μs | — |
| Outbox relay throughput | >5,000 entries/sec | — |

## Test Environment

- **Platform**: $(uname -s) $(uname -m)
- **Go**: $(go version | awk '{print $3}')
- **Date**: ${DATE}
- **Gateway URL**: ${GATEWAY_URL}

HEADER

# ── 1. Unit Benchmarks ────────────────────────────────────────────────────
echo "Running unit benchmarks..."
section "1. Unit Benchmarks"

echo "Running: go test ./... -bench=Benchmark -benchmem -benchtime=5s"
if go test ./... -bench=Benchmark -benchmem -benchtime=5s -run='^$' -count=1 2>&1 | tee "${BENCH_FILE}"; then
  echo "" >> "${REPORT_FILE}"
  echo "\`\`\`" >> "${REPORT_FILE}"
  python3 scripts/parse_benchmarks.py < "${BENCH_FILE}" >> "${REPORT_FILE}" 2>&1 || true
  echo "\`\`\`" >> "${REPORT_FILE}"
  echo "" >> "${REPORT_FILE}"
  BENCH_STATUS="PASSED"
else
  echo "WARNING: benchmark run encountered errors" >&2
  BENCH_STATUS="ERRORS"
fi
echo "Benchmark status: ${BENCH_STATUS}" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"

# ── 2. Outbox Relay Throughput ────────────────────────────────────────────
section "2. Outbox Relay Throughput"

cat >> "${REPORT_FILE}" <<'OUTBOX'
The transactional outbox relay (settla-node) publishes intent entries from
the outbox table to NATS JetStream. Each published entry triggers a worker
(treasury, ledger, provider, blockchain, webhook).

| Component | Throughput target | Architecture |
|-----------|-------------------|--------------|
| Outbox relay poll | Every 50ms | Batch fetch + NATS publish |
| Treasury worker | >10,000 reserves/sec | In-memory atomic, no DB |
| Ledger worker | >15,000 posts/sec | TigerBeetle batch write |
| Provider worker | async, at-least-once | NATS JetStream + idempotency |
| Webhook worker | async, retry + DLQ | HMAC-SHA256 signed |

Outbox entry flow:
1. `Engine.FundTransfer()` writes transfer state change + `IntentTreasuryReserve` in one DB transaction
2. Outbox relay polls the DB (50ms interval), publishes to `SETTLA_INTENTS` NATS stream
3. Treasury worker consumes from NATS, calls `treasury.Manager.Reserve()` (in-memory, ~1μs)
4. Worker acks message — outbox entry marked `published=true`

At 5,000 TPS peak:
- 5,000 transfers × ~4 intent entries each = 20,000 outbox entries/sec
- Relay batches 1,000 entries per poll → 20 NATS publishes per 50ms poll → well within JetStream throughput

OUTBOX

# ── 3. Worker Latency ─────────────────────────────────────────────────────
section "3. Worker Latency"

cat >> "${REPORT_FILE}" <<'WORKERS'
Worker latency targets (measured via unit benchmarks):

| Worker type | Operation | Target latency | Architecture note |
|-------------|-----------|----------------|-------------------|
| Treasury | Reserve | <10μs | In-memory atomic; no DB round-trip |
| Treasury | Release | <10μs | In-memory atomic |
| Ledger | PostEntries (single) | <500μs | TigerBeetle gRPC call |
| Ledger | PostEntries (batch) | <10ms | Batched 5–50ms window |
| Provider | Execute | async | External HTTP, tracked via blockchain worker |
| Blockchain | PollTx | per-chain RPC | External; timeout 30s |
| Webhook | Dispatch | async retry | HMAC-SHA256, exp backoff, 7 attempts |

WORKERS

# ── 4. Load Test ─────────────────────────────────────────────────────────
section "4. Load Test (Quick)"

echo ""
echo "Running quick load test (500 TPS, 2 min)..."
echo "Running quick load test (500 TPS, 2 min) → ${GATEWAY_URL}" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"
echo "\`\`\`" >> "${REPORT_FILE}"

if go run ./tests/loadtest/ \
  -tps=500 -duration=2m -tenants=5 \
  -gateway="${GATEWAY_URL}" -drain=180s 2>&1 | tee -a "${REPORT_FILE}"; then
  LOAD_STATUS="PASSED"
else
  LOAD_STATUS="FAILED (see output above)"
fi

echo "\`\`\`" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"
echo "Load test status: ${LOAD_STATUS}" >> "${REPORT_FILE}"
echo "" >> "${REPORT_FILE}"

# ── 5. Summary ────────────────────────────────────────────────────────────
section "5. Summary"

cat >> "${REPORT_FILE}" <<SUMMARY
| Test suite | Status |
|------------|--------|
| Unit benchmarks | ${BENCH_STATUS} |
| Load test (quick) | ${LOAD_STATUS} |

Generated by: \`bash scripts/generate-report.sh\`
Full report: \`${REPORT_FILE}\`
SUMMARY

echo ""
echo "Report written to: ${REPORT_FILE}"
